// Plan catalog — pure data, safe to import from server components.
// Purchase logic lives in revenuecat.ts; keep SDK imports out of this file.

export const PLANS = {
  free: {
    name: 'Free',
    price: 0,
    aiReadings: 3,
    features: [
      'Daily horoscope (general)',
      'Natal chart overview (Sun, Moon, Rising)',
      '3 AI-powered readings per month',
      'Single tarot card draw',
      'Planetary hours calculator',
      '1 saved birth profile',
    ],
  },
  starter: {
    name: 'Starter',
    price: 4.99,
    annualPrice: 3.49,
    annualTotal: 41.88,
    annualSavings: 18,
    annualSavingsPercent: 30,
    aiReadings: 10,
    features: [
      '10 AI-powered readings per month',
      'Full natal chart (all planets)',
      'Daily personalized transit notifications',
      'Aura Mirror unlimited scans',
      'Cosmic Journal unlimited entries',
      'Soul Gifts & Soul Memory access',
    ],
  },
  light: {
    name: 'Light',
    price: 9,
    annualPrice: 6.49,
    annualTotal: 77.88,
    annualSavings: 30,
    annualSavingsPercent: 28,
    aiReadings: 30,
    features: [
      'Everything in Starter',
      '30 AI-powered readings per month',
      'Numerology life path reading',
      'Name analysis & cosmic matches',
      'Basic transit alerts',
      '5 saved chart readings',
    ],
  },
  premium: {
    name: 'Premium',
    price: 19,
    annualPrice: 13.49,
    annualTotal: 161.88,
    annualSavings: 66,
    annualSavingsPercent: 29,
    aiReadings: 100,
    features: [
      'Everything in Light',
      '100 AI-powered readings per month',
      'Full natal chart with aspects & patterns',
      'Progressed & solar return charts',
      'Synastry & composite compatibility',
      'Starseed & Human Design',
      'Financial astrology report',
      'All astrology courses',
    ],
  },
  pro: {
    name: 'Pro',
    price: 29,
    annualPrice: 20.49,
    annualTotal: 245.88,
    annualSavings: 102,
    annualSavingsPercent: 29,
    aiReadings: 300,
    features: [
      'Everything in Premium',
      '300 AI-powered readings per month',
      'Astro-cartography world maps',
      'Firdaria & zodiacal releasing',
      'Arabic parts & fixed stars',
      'Priority AI processing',
      'Unlimited saved profiles & readings',
      'Export professional reports',
    ],
  },
} as const;
