/**
 * Synastry Readings — what a connection between two people's charts MEANS
 * for them: what they do, feel, crave and fight about, the trap, the move.
 * Used by the synastry page and every synastry share (Top Strengths /
 * Growth Areas), covering every pair the compatibility engine weights.
 *
 * NO ANATOMY: never explain what a planet, point or aspect is. The heading
 * already names the pair. Do not add definitions here.
 *
 * DUPLICATED verbatim in align-web/src/lib/synastryReadings.ts and
 * align-app/src/services/synastryReadings.ts — keep both in sync.
 */

/** Keyed by the two bodies sorted alphabetically ("Mars-Venus"). */
const PAIR_READINGS: Record<string, { supportive: string; challenging: string }> = {
  "Ascendant-Juno": {
    supportive: "One of you walked into the room and the other thought 'that's a partner,' not a fling. You two look committed from the start, the kind of couple strangers assume is married. The devoted one loves the other's presence and style out in the world. The trap: loving the image more than the messy person underneath. The move: show each other your worst morning face early and often, and choose each other again anyway.",
    challenging: "One of you sees the other as marriage material on sight, and the other feels that expectation before they've even decided. The attraction comes with pressure: meeting parents too soon, jealousy over how the other dresses or who they talk to. You two argue about appearances and whose friends get to have opinions. The upside: the seriousness is real. The trap is committing to a first impression. The move: spend a full year learning each other before the big promises.",
  },
  "Ascendant-Jupiter": {
    supportive: "One of you met the other and felt instantly lucky: more generous, more hopeful, bigger somehow. You two travel, laugh loudly, and say yes to invitations other couples skip. Around this person, mistakes feel forgivable and confidence comes easy. The trap: overdoing everything, spending, eating, promising, booking trips you can't afford yet. The move: set a monthly limit on big yeses, then choose the best one together and enjoy it without guilt.",
    challenging: "One of you encourages the other a little too much, 'quit the job, it'll work out,' and then isn't around for the fallout. Big promises, weak follow-through. The one being cheered on starts to feel reckless or preached at, and resents both. The trap: optimism used to dodge practical questions. The move: before any big leap, sit down with a notebook, write the worst case and your plan for it, and only then decide.",
  },
  "Ascendant-Mars": {
    supportive: "The attraction was immediate and physical: one of you walked in and the other's pulse jumped. You two do things together, the gym, long hikes, rearranging furniture at midnight. You make each other feel brave and awake. The trap: all that heat turns into bickering the moment there's nothing to chase. The move: keep a shared challenge on the calendar, a race, a trip, a build, so the drive between you always has somewhere to go.",
    challenging: "One of you says something blunt and the other feels shoved. The first sparks were exciting, but now the more forceful one interrupts, rushes, and decides without asking. The other gets defensive and snaps back, and little things become fights in the car. The trap: calling it honesty when it lands as aggression. The move: the pushier one waits three seconds before answering, and the other says 'slow down' early instead of after exploding.",
  },
  "Ascendant-Moon": {
    supportive: "One of you felt safe the moment you met the other: easy to talk to, easy to cry in front of. You two read each other's moods from across a crowded room and quietly step in. Coming home to this person feels like finally putting the bags down. The trap: one of you becomes the permanent caretaker and the other forgets to ask back. The move: the one who always notices says out loud when they need looking after too.",
    challenging: "One of you reacts to everything the other does, a sigh, a look, a late reply, and takes it personally. The other feels like every facial expression is being monitored. Weekend plans fall apart over a tone that was never meant, and moods leak into every room. The trap: reading each other's faces instead of asking. The move: ask 'Is this about me?' before assuming anything, and believe the answer you get the first time.",
  },
  "Ascendant-North Node": {
    supportive: "From the first moment, one of you looked at the other like a door to a future life. Just being around each other pushes you forward: new friends, new city, a braver version of who you're turning into. People keep saying 'you've changed since you met,' and they mean it kindly. The trap: the future-minded one falling for a projection instead of the actual person at breakfast. The move: every few months, name one thing you love about each other that has nothing to do with growth.",
    challenging: "One of you walked in and the other felt yanked toward a whole new life, fast, too fast. The pull is real, and it often feels like being recruited into a destiny nobody asked for. You two argue about who's holding who back, and the more magnetic one gets blamed for changes the other secretly wanted all along. The upside: this is growth with a face. The move: say 'I'm choosing this' out loud when you take a big step, so nobody becomes the scapegoat.",
  },
  "Ascendant-Pluto": {
    supportive: "One of you felt the other's gaze and couldn't shake it. The attraction was intense from minute one, and one of you has been quietly remaking themselves ever since: new look, new habits, new backbone. You two see through each other's masks and like what's underneath. The trap: the intense one starts deciding how the other should present themselves to the world. The move: back the changes the other chooses, not the ones you would pick for them.",
    challenging: "One of you feels watched and analyzed by the other, starting from the first date. Clothes, friends, how you talk to the waiter: everything gets read and commented on. The observed one either rebels loudly or shrinks. The trap: fascination sliding into control. The move: the intense one names the fear directly instead of critiquing, and the other states clearly which topics are off-limits, then both of you respect that line without testing it.",
  },
  "Ascendant-Saturn": {
    supportive: "One of you seemed too serious at first and the other took a while to warm up, but that caution built something solid. You two act like grown-ups together: reliable, punctual, trusted by friends and in-laws. One steadies the other, and the other gives them a reason to commit. The trap: nobody ever loosens up, and the relationship starts to feel formal. The move: do one silly, unplanned thing a month and let it be messy.",
    challenging: "One of you corrects the other's posture, grammar, outfit or laugh, sometimes without saying a word. The corrected one feels judged and starts shrinking in public. The critic honestly believes they're helping. The first dates felt careful, and a year later it still feels like an interview. The trap: approval handed out like a grade. The move: the critical one keeps every correction private for a month and says two appreciations a day instead.",
  },
  "Ascendant-Sun": {
    supportive: "One of you noticed the other across the room and felt instantly recognized, like 'there you are.' You two look like a pair to outsiders, and each of you feels more comfortable in your own skin with the other around. The bold one boosts the other's presence; the other makes the bold one feel understood. The trap: performing the perfect couple in public and saving the real stuff for never. The move: ask each other one honest question in private every week.",
    challenging: "One of you takes up the whole room and the other starts to feel like the plus-one. The first meeting was electric, but now one of you corrects the other's stories at dinner. The quieter one bristles; the brighter one doesn't even notice. The trap: letting one personality become the couple's entire identity. The move: at the next party, the louder one asks the other a question, then lets them tell the whole story without a single interruption or correction.",
  },
  "Ascendant-Venus": {
    supportive: "The attraction started with looks and ease: one of you simply liked the way the other moved, dressed and laughed. You two still flirt in grocery store aisles. Being with this person makes you feel attractive, and you show each other that freely. The trap: mistaking pleasant for deep, so the first real conflict feels like it breaks the spell. The move: have a serious conversation about money or family plans early, and prove to each other the attraction survives it.",
    challenging: "One of you admires how the other looks and then tries to restyle them: hair, clothes, even friends. Compliments slowly turn into comments. The admired one feels like a makeover project; the admiring one feels ignored when their taste gets refused. Spending on appearances becomes a sore spot between you. The trap: loving the image more than the person. The move: stop suggesting changes for a month and praise only what the other chose for themselves.",
  },
  "Ascendant-Vesta": {
    supportive: "The first time one of you saw the other, it was their focus that pulled you in: bent over a guitar, a laptop, a notebook, completely absorbed. The absorbed one felt noticed without being interrupted, which almost never happens. You two still flirt best when one of you is working and the other is watching from the doorway. The trap: the watcher becomes an admiring audience and never steps into the room. The move: ask to learn one piece of what they do, and let them teach you badly.",
    challenging: "One of you shows up loud, charming and ready to go; the other is mid-task and reads that entrance as noise. From day one there was attraction and an eye-roll in the same look. The social one feels judged for how they come across, and the focused one feels dragged out of their shell to perform. You two clash over who leaves the party first. The trap: turning personality differences into moral ones. The move: plan arrivals together, one of you gets a quiet exit, the other stays without guilt.",
  },
  "Chiron-Moon": {
    supportive: "One of you cries in front of the other, and it's the first time in years that crying didn't cost anything. You two build a soft landing: the blanket, the tea, the no-questions night in after a brutal call with a parent. The one doing the comforting learns their own tenderness isn't weakness. The trap: the relationship turning into a recovery ward where nobody is allowed to be strong. The move: plan one ridiculous, carefree day where the past is off the agenda.",
    challenging: "One of you needs comfort, and the other, meaning well, offers it in the exact tone that used to mean trouble at home. Moods become landmines; a sigh gets heard as rejection, and a closed door becomes a silent treatment neither of you intended. You two end up mothering and resenting each other in the same evening. The upside: the rawness is real, and real is fixable. The trap is guessing. The move: agree on one plain word that means 'I'm hurting, not angry.'",
  },
  "Chiron-Sun": {
    supportive: "One of you walks in with the confidence the other lost somewhere around age twelve, and it doesn't feel like a threat, it feels like a loan. Being around each other makes the wounded one braver in meetings, at family dinners, on the dance floor. The steadier one gets something back too: someone who notices when the bravado is covering a hurt. The trap: the confident one getting praised as the rescuer and quietly liking it. The move: let the healed one lead one big decision this month.",
    challenging: "One of you shines without trying, and the other feels that shine like a flashlight in a sore eye. Offhand jokes land as verdicts, and the brighter one is baffled to be cast as the villain of a story they never read. You two keep reenacting someone else's childhood at your kitchen table. The upside: this is the relationship where the wound finally gets named out loud. The trap is performing hurt or performing innocence. The move: ask 'who did I just sound like?' and listen to the answer.",
  },
  "Chiron-Venus": {
    supportive: "One of you was taught that love has to be earned, and the other keeps handing it over for free until the flinching stops. You two turn small gestures into repairs: the saved seat, the bill paid without a speech, the compliment that lands where an old insult used to live. Friends notice one of you laughs differently now. The trap: the gentler one becoming a full-time nurse instead of a lover. The move: once a week, let the healed one spoil the healer, no explaining allowed.",
    challenging: "One of you gives affection the way you were never given it, and the other goes cold at exactly the moment it arrives. A thoughtful gift turns into a fight about what it's supposed to mean, and money spent on each other feels like a test someone keeps failing. You two keep pressing the bruise you both swear is healed. The upside: nobody else gets this close to the real ache. The move: when a kind gesture stings, say 'that hit an old spot' before you say anything sharper.",
  },
  "Descendant-Sun": {
    supportive: "One of you is exactly the kind of person the other always said they'd end up with, and it shows. You two look like a pair in photos and fall into roles naturally, one lighting up the room and one glowing beside them. Partnership feels less like compromise and more like recognition. The trap: the admired one becoming the headliner and the other a supporting act. The move: at the next party, trade places and let the quieter one take the spotlight on purpose.",
    challenging: "One of you is the other's type so completely that it's almost irritating. The attraction comes with projection: one of you sees in the other the pride and confidence they won't claim for themselves, then resents it. You two fight over who's more selfish while both desperate to be chosen. The upside: this mirror shows you what you're hiding. The trap is making your partner carry the ego you disown. The move: name one thing you admire about them, then go do it yourself.",
  },
  "Descendant-Venus": {
    supportive: "One of you checks every box on the other's old wish list, down to the laugh and the taste in shoes. You two fall into romance easily: dinners that run long, shared playlists, a partner who makes the other feel beautiful just by looking. Friends call you the easy couple. The trap: niceness replacing honesty, where nobody raises the money issue because it's not romantic. The move: once a month, have the unsexy talk about spending, chores and resentments while holding hands.",
    challenging: "One of you is the other's type, and the other knows it and uses it. Charm smooths over conflicts that never actually get solved, and gifts show up where apologies should be. You two agree in public and simmer in private, especially over money and who gives more. The upside: real affection lives under the politeness. The trap is keeping the peace instead of keeping it real. The move: say the unflattering truth kindly, and let your partner still like you afterward.",
  },
  "IC-Moon": {
    supportive: "One of you walks into the other's kitchen and it smells like childhood. You two nest fast: shared groceries by week three, holidays with each other's families that actually feel warm, a couch that becomes the center of the world. Relatives adopt the new partner quickly. The trap: getting so cozy that nobody leaves the house or grows. The move: host the family dinner, then book one trip that has nothing to do with home.",
    challenging: "One of you makes the other feel at home, which also means old family ghosts move in with you. Holidays turn tense, one of you sides with a parent without meaning to, and the kitchen becomes the courtroom. You two reenact the arguments you watched as kids. The upside: this is where family patterns finally get rewritten. The trap is blaming your partner for your mother's tone. The move: before every family visit, agree on an exit signal and a time to leave.",
  },
  "Juno-Juno": {
    supportive: "You two want the same kind of commitment, and it shows early: the same idea of loyalty, the same timeline, the same deal-breakers. Neither of you has to explain why a late-night text from an ex matters. Commitment feels like agreement rather than negotiation. The trap: assuming you're so in sync that you stop talking about what you actually want. The move: every year, renew your promises out loud, with specifics about what's changed.",
    challenging: "You two both care deeply about loyalty but define it completely differently. One of you thinks commitment means total transparency; the other thinks it means trust without checking. Your arguments sound identical: 'that's not what a partner does.' The upside: nobody takes this lightly. The trap is each believing your version is the obvious one. The move: write your separate definitions of loyalty and compare them before the next jealous fight.",
  },
  "Juno-Jupiter": {
    supportive: "One of you makes commitment feel like an adventure rather than a cage. You two dream big together: the destination wedding, the house abroad, the family that throws the best holidays. Generosity is the glue, with gifts, trips, and saying yes to each other. The trap: overspending on the dream and overpromising on the plans. The move: pick the one big thing you want most this year and put a real budget on it.",
    challenging: "One of you wants a loyal, settled partner; the other wants a bigger life and keeps adding to it. More travel, more friends, more plans, and less time at home. Commitment feels like it's competing with opportunity. You two fight about excess: money spent, promises made to other people. The upside: nobody feels trapped. The trap is growth that leaves one partner behind. The move: before saying yes to anything big, ask 'does this fit us?'",
  },
  "Juno-Mars": {
    supportive: "One of you fights for the relationship, and the other feels chosen by that fire. You two defend each other in public, want each other in private, and treat commitment as something you actively build rather than wait on. The desire doesn't fade after you move in. The trap: getting so protective that jealousy starts passing for passion. The move: channel that heat into a shared project, like training for a race together or gutting a room.",
    challenging: "One of you wants a committed partner, and the other wants to never be told what to do. Jealousy flares quickly: a coworker's name, a late reply, a dance with a friend. Doors slam, voices rise, and then make-up sex resets everything until next time. You two confuse intensity with loyalty. The upside: nobody's indifferent here. The trap is using anger to test commitment. The move: agree on what's actually off-limits, specifically, before the next party.",
  },
  "Juno-Moon": {
    supportive: "One of you makes the other feel safe enough to promise forever. You two turn commitment into daily comfort: the saved leftovers, the call on the drive home, knowing exactly what calms each other during a panic. Moving in together feels natural rather than risky. The trap: settling into a cocoon where the romance quietly falls asleep. The move: keep the domestic rituals and add one dressed-up date a month where nobody talks about bills.",
    challenging: "One of you needs commitment to feel safe; the other needs to feel safe before committing. That loop plays out in moods, silent nights, and sudden fears about whether this is actually forever. Jealousy shows up as feelings instead of words: a sulk after a friend's text, a clingy week after a party. You two love hard and reassure badly. The upside: the bond runs deep. The move: ask plainly for reassurance instead of testing for it.",
  },
  "Juno-North Node": {
    supportive: "This partnership feels like the reason you both took the long way here. One of you brings a loyalty that pushes the other toward a bigger life: a new city, a family, a career brave enough to scare them. You two grow up together, even as adults. The trap: treating the relationship as destiny so nobody puts in the daily work. The move: every anniversary, name one way you've grown and one thing you'll build next.",
    challenging: "One of you sees commitment as the next step, and the other feels it as a step into a life they aren't sure they want. The relationship keeps pushing you both past comfort, which feels fated one week and like pressure the next. You two argue about timing: marriage, moving, children. The upside: this bond does not let either of you stall. The trap is resenting growth because it arrived through love. The move: separate 'I'm scared' from 'I don't want this' out loud.",
  },
  "Juno-Pluto": {
    supportive: "You two love each other like it's a vow, even without the paperwork. One of you gives total loyalty, and the other brings a depth that makes that loyalty feel worth it. Crises pull you closer, and secrets get shared that nobody else will ever hear. The trap: the bond becoming so all-consuming that friends drift and outside life shrinks. The move: each of you protects one friendship fully, and you let the intensity breathe.",
    challenging: "One of you wants commitment, the other wants control, and both call it love. Password sharing becomes surveillance, jealousy turns into interrogations, and breakups end in 'I'll never let you go' rather than goodbye. You two are fiercely bound and quietly afraid of each other. The upside: this is where power games finally get faced. The trap is possession disguised as devotion. The move: agree that privacy is not betrayal, and say it out loud.",
  },
  "Juno-Saturn": {
    supportive: "You two take commitment seriously in a way that feels old-fashioned and steady. One of you brings structure, the other brings devotion, and together you build something that survives layoffs, illness and in-laws. Joint accounts and mortgages don't scare you. Friends call you the adults of the group. The trap: the relationship becoming a duty where nobody remembers to flirt. The move: schedule romance the way you schedule bills, and guard it just as seriously.",
    challenging: "One of you wants a real promise; the other keeps delaying it, sometimes for years. Commitment turns into a checklist of conditions: after the promotion, after the debt, after you prove yourself. The waiting one feels judged, and the cautious one feels pressured. You two stay loyal and resentful in the same breath. The upside: what you build lasts. The trap is love on probation. The move: set a real date for the decision, and keep it.",
  },
  "Juno-Sun": {
    supportive: "One of you looks at the other and thinks 'this is the one I'd marry,' sometimes before the second date. You two take each other seriously: meeting parents early, planning a real future, bragging about each other in public. Loyalty is part of the attraction. The trap: the admired one getting put on a pedestal while the devoted one disappears behind them. The move: celebrate the devoted partner's wins as loudly as the admired one's, starting this week.",
    challenging: "One of you wants a partner who's loyal, the other wants a partner who's impressed, and those aren't always the same person on the same night. Commitment turns into a stage: whose name goes first, whose career decides the move, who gets the credit. You two feel married and unseen at once. The upside: neither of you takes the bond lightly. The trap is loyalty becoming an audience. The move: tell each other one private thing you admire that nobody else will ever hear.",
  },
  "Juno-Venus": {
    supportive: "You two feel like a wedding waiting to happen: matching taste, shared plans for the home, a partner you're proud to introduce. One of you shows love through gifts and touch, and the other receives it as a promise. Money conversations feel collaborative instead of scary. The trap: making the relationship so pretty that problems get decorated rather than solved. The move: before the next big purchase, talk honestly about the thing that actually bothers you.",
    challenging: "One of you wants romance, the other wants commitment on paper, and the gap shows up at every anniversary. Flirting with others becomes a sore subject, and spending on each other feels like keeping score. You two argue about what a real relationship looks like, using gifts as evidence. The upside: you both care deeply about getting this right. The trap is proving love with money. The move: write down together what loyalty means to each of you, with specifics.",
  },
  "Juno-Vesta": {
    supportive: "You two treat the relationship itself like a vow you both keep choosing, not a feeling you wait on. One of you wants the ring, the joint lease, the promise said out loud; the other shows loyalty by showing up for the mundane every single day. The big dates matter, and so do weekday errands. The trap: you get so faithful to the structure that you stop checking whether the person inside it is happy. The move: once a year, renegotiate the vow out loud, including what has changed.",
    challenging: "One of you married a person; the other feels married to a mission too, and the first one knows they are sharing. Holidays get shortened for deadlines, family events get skipped for retreats, and the committed one wonders where they rank. The devoted one feels loyalty being measured in hours. You two keep having the 'am I your priority' fight in new outfits. The trap: forcing a choice between partner and calling. The move: agree in writing on the non-negotiable dates the calling never touches.",
  },
  "Jupiter-Jupiter": {
    supportive: "You two expand together: the same appetite for travel, learning, big dinners and bigger plans. You believe in each other's wild ideas and say yes far more than no. Life together feels like an adventure with a generous budget and an open door for friends. The trap: nobody hits the brakes, so debt, commitments and waistlines grow unchecked. The move: agree on one shared limit, a spending number or a calendar cap, and treat it as the thing that keeps the fun going.",
    challenging: "You two believe in different things with equal conviction. One of you wants the spiritual retreat, the other wants the business course; one person's faith or politics grates on the other. Both of you are sure you are right, and both of you preach. Generosity turns into a contest over who gives more. The trap: turning growth into a debate about whose worldview wins. The move: attend one event in the other's world, stay curious, and correct no one on the drive home.",
  },
  "Jupiter-Moon": {
    supportive: "One of you walks in upset and the other shrinks the problem in five minutes: food, a joke, a big hug, a plan. Home with you two is generous, a place where friends crash and holidays overflow. The anxious one feels safe; the upbeat one feels needed. The trap: comfort through excess, too much food, too much spending, too much 'it'll be fine' instead of sitting with a sad feeling. The move: sometimes just stay in the bad mood together without cheering it up.",
    challenging: "One of you shares a feeling and the other hands back a pep talk. 'Look on the bright side' lands like 'your feelings are too much.' The optimist overpromises comfort and then is not there when it counts, so the sensitive one starts trusting words less. Family holidays turn into overcommitment wars nobody enjoys. The trap: blowing past pain with positivity. The move: the upbeat one repeats back what they heard, word for word, before offering anything hopeful.",
  },
  "Jupiter-Saturn": {
    supportive: "One of you dreams big, the other asks what it costs, and together you two build what neither could alone. The optimist finds the house, the trip, the business; the realist makes sure it does not collapse. You balance each other at the bank and in family decisions, and friends trust your advice as a couple. The trap: the dreamer resents feeling edited, and the realist resents always being the adult. The move: trade roles for one decision a year, fully, and live with the result.",
    challenging: "One of you books the flights before checking the balance; the other finds out from the credit card alert. Generosity collides with fear: the big tips, the lavish gifts and 'we'll figure it out' against the spreadsheet and the tight jaw. You two fight about money but really about faith versus fear. The trap: the spender feels controlled, the saver feels unsafe, and both feel alone. The move: create a monthly 'yes' fund the generous one spends freely, and a floor the careful one never has to defend.",
  },
  "Jupiter-Sun": {
    supportive: "One of you believes in the other more than anyone ever has. You two cheer each other's promotions and wild ideas, and plans get bigger just from talking over coffee. The confident one grows under the other's praise, and the encourager gets to feel wise. The trap: nobody wants to be the one who asks 'can we actually afford this?' The move: before every big leap, each of you names one risk out loud, then you decide together.",
    challenging: "One of you inflates the other's ego and then lectures them about it. Advice comes wrapped in a sermon; praise comes with an agenda. The bright one feels either spoiled or preached at, and the generous one feels unappreciated for all that belief. The trap: competing over who is wiser and who taught whom. The move: offer an opinion only when asked, and start every big talk with 'what do you think?'",
  },
  "Jupiter-Venus": {
    supportive: "You two are generous with each other in every direction: gifts, time, praise, surprise weekends away. Friends love being around you because your home feels like a party. One of you makes the other feel lucky simply to be loved. The trap: spending and indulging to avoid the rare hard talk. The move: keep a shared fun fund with a firm number, and when something hurts, say it before booking the next treat.",
    challenging: "One of you gives too much and the other starts expecting it. Overspending, overeating, over-promising: it feels good tonight and costs a lot later. The generous one quietly keeps a tally; the other thinks love means never hearing no. The trap: using gifts and splurges as proof of love. The move: once a month, plan a date that costs nothing, where the only gift is full attention and phones stay in a drawer.",
  },
  "MC-North Node": {
    supportive: "One of you walks into the other's professional life and things start moving: the promotion, the brave pivot, the public launch. You two operate like a power couple in the making, the kind friends quietly envy online. Ambition here feels meaningful rather than cold. The trap: the relationship becoming a career strategy and date night turning into a pitch meeting. The move: ban work talk one night a week and remember why you liked each other before the resume.",
    challenging: "One of you pushes the other's career harder than they asked for, and the push feels like fate and pressure at once. Status creeps into the bedroom: who earns more, whose job moves the family, whose success is 'the real one.' You two cheer publicly and keep score privately. The upside: neither of you settles for a smaller life. The trap is love turning into a management plan. The move: ask 'do you want my advice or my applause?' before every career conversation.",
  },
  "Mars-Mars": {
    supportive: "You two move at the same speed. Decisions get made in the car, furniture gets assembled in one furious afternoon, and the bedroom has no shortage of heat. Fights are loud and over fast, and you actually like each other more afterward. Friends find your competitiveness exhausting; you find it foreplay. The trap: turning everything into a race, including who apologizes last. The move: pick one arena, board games, the gym, cooking, to compete in, and play the rest of life on the same team.",
    challenging: "Two people who both reach for the steering wheel. One of you pushes, the other pushes back harder, and a disagreement about parking becomes a standoff about respect. The sex is hottest right after fights, which is part of the problem. Neither of you backs down first, so small things fester for days. The trap: needing to win more than needing to be close. The move: when voices rise, one of you calls a twenty-minute walk apart, and you both come back to finish it sitting down.",
  },
  "Mars-Mercury": {
    supportive: "Conversations between you two have heat. You debate politics over dinner like a sport, flirt through arguments, and solve problems fast because nobody is afraid to say the direct thing. One of you has the idea, the other is already booking it. Sexting comes naturally. The trap: sharpness becomes the default, and a joke cuts deeper than intended. The move: when a comeback feels too good to hold, hold it for three seconds and check whether you are playing or wounding.",
    challenging: "One of you talks, the other hears an attack. A simple 'did you pay the bill?' lands like an accusation, and the reply comes back in all caps. You two have fights over text that would never happen face to face, and screenshots get sent to friends. The quick-tongued one wins arguments and loses warmth. The trap: arguing to be right while the relationship keeps losing. The move: any fight longer than two messages moves to a phone call or the couch.",
  },
  "Mars-Moon": {
    supportive: "One of you makes the other feel safe enough to want boldly, and the other makes wanting feel like coming home. You two get physical when you're emotional, which means make-up sex, protective instincts, and a partner who will absolutely confront the rude neighbor. The tender one gets braver; the fierce one softens at the edges. The trap: using desire to skip the talk. The move: after the heat, stay in bed five more minutes and say one true feeling out loud.",
    challenging: "One of you acts fast; the other feels everything that speed ran over. A slammed cupboard or a blunt 'just get over it' lands like a slap, and the hurt one sulks until the impatient one explodes. You two go from cuddling to crying in one bad sentence. The desire is real, and so is the flinching. The upside: you learn to fight without leaving bruises. The move: anger gets a walk around the block before it gets a voice.",
  },
  "Mars-Neptune": {
    supportive: "Desire between you two feels almost dreamlike. One of you acts, the other softens it into something tender and imaginative, and the bedroom becomes a place for fantasy without shame. You fight gently, apologize quickly, and inspire each other to chase creative or spiritual goals. The trap: avoiding direct asks, so wants get hinted at instead of stated and slowly dissolve. The move: every so often, say exactly what you want in plain words, and trust it will not break the spell.",
    challenging: "One of you wants something clear; the other slips away from confrontation into vague promises and 'we'll see.' Anger has nowhere to land, so it turns into passive aggression, drinking, or silent withdrawal. Sex swings between intoxicating and confusing. The direct one starts to feel crazy, and the evasive one feels attacked. The trap: fog instead of honesty. The move: when something is wrong, both of you finish this sentence out loud: 'What I actually want right now is...'",
  },
  "Mars-North Node": {
    supportive: "One of you lights a fire under the other, and suddenly they're signing up, speaking up and moving forward. You two act fast together, and every push seems to land somewhere that matters. The driven one lends the other courage they didn't know they had. The trap: pushing so hard the other never gets to choose their own pace. The move: ask 'do you want me to push, or back off?' before each big leap.",
    challenging: "One of you shoves the other toward a future before they're ready: deadlines, ultimatums, 'now or never.' The pushed one digs in; the pusher gets angry and pushes harder. Your fights are about pace, not direction, but they feel like fights about everything. The trap: turning a shared calling into a forced march. The move: agree on the goal first, let the slower one set the next step, and drop the subject for a full week.",
  },
  "Mars-Pluto": {
    supportive: "When you two want something, it gets done: the move, the business, the marathon, the renovation nobody thought you'd finish. Sex is intense and so is anger, but neither of you runs from either. One of you pushes, the other matches the push, and you respect each other more for it. The trap: turning every disagreement into a contest neither of you will lose. The move: aim that force outward and pick a shared goal hard enough to need both of you.",
    challenging: "Arguments between you go from zero to scorched earth in three sentences. One of you pushes; the other pushes back harder, and both remember every word for months. Desire is huge and so is the urge to control who drives, who decides, and who apologizes first. The trap: winning the fight and wrecking the trust. The move: agree on a stop word, walk away for twenty minutes when either of you says it, and come back to finish calmly.",
  },
  "Mars-Saturn": {
    supportive: "One of you has the fire, the other knows how to make it last. The impulsive one wants to quit the job tomorrow; the steady one turns it into a twelve-month exit plan that actually works. In bed, patience meets hunger, and it is better than either of you expected. You two get serious things done: debts cleared, bodies trained, businesses built. The trap: the planner becomes the brake on every joy. The move: say yes to one reckless idea a season, no spreadsheet.",
    challenging: "One of you wants to go; the other says 'not yet' so often it sounds like 'never.' Desire gets met with caution, and the eager one starts feeling like a child asking permission. The careful one feels bulldozed and goes cold, including in bed. You two have the same argument about money, travel and sex: speed versus safety. The trap: one of you floors the gas while the other rides the brake until something burns out. The move: put a real deadline on every 'not yet,' then honor it.",
  },
  "Mars-Sun": {
    supportive: "One of you lights up, and the other wants to chase whatever made that happen. You two push each other at the gym, in business, in bed, and neither wants to be the one who quits first. There's a competitive heat that reads as flirting to everyone watching. Arguments are loud, quick and over by dessert. The trap: treating everything as a race, including who apologizes. The move: pick one shared goal a season and aim that fire at it together.",
    challenging: "One of you wants to be admired and the other wants to win, and those two needs collide in the car, in the kitchen, over the thermostat. A simple 'you're doing it wrong' starts a war over who's in charge. The sex is hot after the fight, which quietly teaches you to keep fighting. The upside: nobody lets the other coast. The trap is scorekeeping. The move: before firing back, ask what you're actually defending, the idea or your pride.",
  },
  "Mars-Uranus": {
    supportive: "Nothing about you two is predictable. One of you proposes a road trip at midnight, and the other already has the keys. Sex is experimental and fun, and boredom never settles in. You push each other to quit jobs that were killing you, move cities, and try things neither would try alone. The trap: excitement becomes the only glue, and when life gets ordinary you both start looking for the next jolt elsewhere. The move: build one steady ritual you never break, then let everything else stay wild.",
    challenging: "One of you flares up; the other vanishes. Anger meets sudden distance, and fights end with a slammed door or a night away. The attraction is electric but unstable: on, off, on again, breakups by text. The restless one needs space, the heated one needs a reaction, and each sets the other off. The trap: chaos that feels like passion. The move: agree now, while calm, on a pause word that means stepping away for one hour and coming back, not leaving.",
  },
  "Mars-Venus": {
    supportive: "The pull was physical before it was anything else, and months later it still is; one of you only has to lean in the doorway. One chases, the other lets themselves be caught, and both secretly love the game. Fights between you end in bed more often than they end in agreement. The trap: using sex as the apology so the real issue never gets said. The move: settle the argument out loud with clothes on first, then go have the make-up.",
    challenging: "One of you wants slow, candlelit and talked-about; the other wants now, and takes a no personally. Heat runs high, and so does resentment: one feels used, the other feels rejected, and both go cold for days. Money fights have the same shape, with one spending on beautiful things and the other calling it waste. The trap: punishing each other by withholding touch. The move: name your pace plainly, 'tonight I want slow,' and treat a pause as information, not a verdict.",
  },
  "Mars-Vesta": {
    supportive: "You two make a dangerous team: one of you brings raw drive, the other points it at one target and refuses to let it scatter. Side businesses actually launch, marathons actually get run, the house actually gets renovated. Heat between you often shows up as working side by side until 1 a.m. and then collapsing into each other. The trap: all that hunger gets spent on the project and the bed goes cold for weeks. The move: when the task wraps each night, turn the drive back toward each other before sleep.",
    challenging: "One of you wants sex, action or a fight right now; the other has gone inward and treats the interruption like an insult. Desire gets turned down politely, over and over, until the hungry one stops asking and starts sulking at the gym. The focused one feels pressured and pulls further into work. The trap: you two turn wanting each other into a scheduling conflict nobody names. The move: say plainly 'I want you, not a favor,' and the other answers with a real time, not 'later.'",
  },
  "Mercury-Mercury": {
    supportive: "You two can talk for five hours and still send voice notes afterward. Jokes land, references match, and arguing is basically a hobby. One of you finishes the other's thoughts; the other edits your emails before you hit send. The trap: talking about feelings instead of feeling them, and winning debates instead of understanding each other. The move: once a week, put the phones away and let one person talk for ten minutes with zero replies.",
    challenging: "One of you texts in paragraphs; the other replies 'k.' Tone gets misread, plans get misheard, and every disagreement turns into a trial about what was actually said. You two keep having the same fight in different cars. The trap: fighting over words instead of meaning. The move: repeat back what you heard before answering, 'so you're saying...', and never let a serious conversation happen over text.",
  },
  "Mercury-Moon": {
    supportive: "One of you can put words to the other's mood before they've even noticed it, and it feels like being read gently. You two send voice notes instead of texts, recap the day in bed, and remember the tiny details, like the coworker's name and the dream from Tuesday. Hard talks end in a hug instead of a verdict. The trap: processing feelings endlessly instead of changing anything. The move: end every long heart-to-heart with one sentence that starts 'So tomorrow I'll...'",
    challenging: "One of you says exactly what you mean; the other hears exactly how it felt. Logic arrives where comfort was wanted, and the feeling one answers facts with a wounded silence. Texts get reread for tone, and 'fine' becomes the most dangerous word in the house. You two are both right and both unheard. The upside: you teach each other a second language. The move: when it's heated, the talker repeats the feeling back before offering a single fact.",
  },
  "Mercury-Neptune": {
    supportive: "You two talk in half-sentences and still understand each other, and it feels a little like telepathy. One of you writes long, poetic messages; the other reads between lines nobody else would catch. Late conversations drift into dreams, music, and what happens after death. The trap: the vagueness spills into logistics, and nobody actually confirmed the flight time. The move: keep the magic in the talking, and put every date, bill and promise in a shared note in plain words.",
    challenging: "One of you says one thing, and the other hears a softer, prettier version of it. White lies creep in to avoid conflict, 'I'll handle it' means nothing gets handled, and you both remember the same conversation differently. You two are gentle with words and foggy with facts. The upside: there's real empathy under the confusion. The trap is agreeing just to end the talk. The move: repeat important agreements back in one sentence and text it, no poetry allowed.",
  },
  "Mercury-Pluto": {
    supportive: "Conversations between you two go deep fast. You talk until 3 a.m. about childhood, secrets, the thing you never told anyone. One of you asks the piercing question, and the other finally answers honestly. Nothing stays surface-level, and you both feel profoundly understood. The trap: probing turns into interrogating, and privacy starts to feel like betrayal. The move: agree that some thoughts are allowed to stay unspoken, and ask 'do you want to talk about this?' before digging.",
    challenging: "One of you reads between every line; the other starts choosing words like they are under oath. Phones get checked, texts get reread, old arguments get quoted back verbatim. Words become weapons: the cutting remark, the silent treatment, the thing said only to win. The trap: using what you know about each other as leverage. The move: ban quoting past fights, and when suspicion rises, ask one direct question and accept the answer.",
  },
  "Mercury-Saturn": {
    supportive: "One of you thinks out loud; the other listens, asks the hard question, and helps the idea grow a spine. Plans you two make actually happen because someone writes them down. The chatty one feels taken seriously, and the serious one finally gets to laugh. Leases, budgets and awkward family phone calls are easy between you. The trap: every conversation becomes a meeting and the playful talk dries up. The move: keep one daily conversation that has no agenda and no problem to solve, just stories.",
    challenging: "One of you speaks and the other corrects: the grammar, the facts, the date of the thing that happened three years ago. The talkative one gradually stops sharing ideas, and the careful one wonders why the house got so quiet. Texts go unanswered for hours because someone is composing the perfect reply. The trap: silence mistaken for peace. The move: the corrector lets five things slide this week without comment, and the quieted one says 'I'm not asking for edits' when they just want to be heard.",
  },
  "Mercury-Sun": {
    supportive: "One of you says the thing the other has been circling for weeks, and suddenly the plan exists. You two are the couple narrating each other's stories at dinner, finishing punchlines, drafting the career email together at midnight. Being understood this fast makes both of you bolder. The trap: talking about the life so well that you forget to live it, or one of you becoming the other's publicist. The move: turn the next great conversation into one booked date, one sent application, one real step.",
    challenging: "One of you talks to think; the other hears every half-formed thought as a comment on who they are. A text like 'you sure about that?' becomes a two-hour dispute about respect. The quick talker feels censored, and the proud one feels picked apart in public. You two edit each other's sentences at parties and both go home stung. The upside: nobody else sharpens your ideas like this. The move: before correcting, ask 'brainstorm or decision?' and match your tone to the answer.",
  },
  "Mercury-Uranus": {
    supportive: "You two talk like two browser tabs open at once: wild theories, sudden plans, memes at 2 a.m. that turn into a business idea. One of you says the unthinkable and the other says 'yes, and.' Conversations never go stale, and friends drop out of the group chat trying to keep up. The trap: brilliant ideas with no follow-through and a calendar full of 'we should.' The move: every time you get excited, one of you puts a real date on it before the conversation ends.",
    challenging: "One of you likes to finish a thought, and the other interrupts with a totally different one. Plans get changed by text an hour before, opinions flip mid-argument, and 'I was just being honest' becomes a weapon. You two feel electric and exhausted in the same conversation. The upside: nobody lets the other think small. The trap is surprise as a habit. The move: big changes get said in person, with a day's notice, never dropped in the chat.",
  },
  "Mercury-Venus": {
    supportive: "You two text like you are still courting: the voice notes, the inside jokes, the song sent at 11 p.m. with no explanation needed. One of you says things beautifully and the other actually hears them. Compliments land, apologies land, even arguments end with someone laughing. Shopping together is easy because your taste lines up. The trap: charm smooths over things that need a harder conversation. The move: when something bothers you, say it plainly first and sweeten it second, not the other way around.",
    challenging: "One of you communicates in facts and the other hears every fact as a verdict on love. 'That shirt's a bit tight' becomes a two-day wound. The sensitive one sends long texts about feelings; the literal one replies with a thumbs-up and genuinely thinks that is enough. You two argue about tone more than content. The trap: debating wording while the actual hurt goes untouched. The move: the blunt one opens with what they love before any critique, and the tender one asks 'what did you mean?' once before reacting.",
  },
  "Moon-Moon": {
    supportive: "You two feel like home within weeks: same comfort food, same need for a quiet night after a loud week, same way of sulking. Neither of you has to explain why the sad movie hit so hard. Your place fills up with inside jokes, blankets, and little rituals nobody else understands. The trap: you get so cozy you stop inviting the world in, and friends quietly drift. The move: keep one standing night a month out with other people, together or apart.",
    challenging: "You both need looking after at the exact same moment, and nobody is left to do the looking after. One of you goes silent when hurt; the other wants to talk it through at midnight. Family holidays turn into a contest over whose traditions count and whose mother gets Christmas. The trap: two tired people waiting for the other to be the grown-up first. The move: take turns on purpose, say out loud whose bad day it is tonight, and the other one leads.",
  },
  "Moon-Neptune": {
    supportive: "You two feel each other's moods through walls. One of you tears up at a film and the other is already reaching over. Home becomes a soft place with candles, late talks and dreams you tell nobody else, a tenderness friends find almost embarrassing. The trap: you escape together instead of facing things, so bills, family drama and resentments sit under the rug in a haze. The move: pair every cozy night in with one hard, practical conversation, sober and in daylight.",
    challenging: "One of you says 'I'm fine' and the other believes it because believing is easier. Feelings get guessed at instead of stated, and the guesses are often wrong. One of you becomes the rescuer, the other the one who needs rescuing, and nobody notices the extra drinks, the vague excuses or the unanswered texts. The trap: loving the version of each other you imagine. The move: replace 'I thought you knew' with specific sentences: what happened, what you felt, what you need tonight.",
  },
  "Moon-North Node": {
    supportive: "One of you makes the other feel safe enough to finally change. Around each other old fears loosen: the one who never cried in front of anyone does, the one who never left their hometown starts looking at flights. Your kitchen table is where the big life decisions get made. The trap: the nurturing one becomes the other's only safe place, and the growth stalls there. The move: cheer on a friendship, a therapist, or a trip the other takes without you.",
    challenging: "One of you wants to stay cozy; the other feels pulled forward by this bond and gets restless on the couch. Comfort starts to feel like a cage to one of you, and progress feels like abandonment to the other. You fight about moving, about kids, about 'why can't things just stay like this.' The trap: holding each other in place out of fear of losing what you have. The move: pick the next big step together and let the nervous one set the timeline.",
  },
  "Moon-Pluto": {
    supportive: "One of you feels completely seen by the other, even in the parts they hide from their own family. You two talk about childhood, grief, and shame in ways neither of you has with anyone else. The bond runs deep and loyal, and every crisis only tightens it. The trap: the intense one starts managing the other's moods like a secret project. The move: ask before you dig, 'Do you want to go there tonight?', and accept a no without sulking.",
    challenging: "One of you picks up every shift in the other's mood and can't leave it alone. The more sensitive one feels watched and starts hiding feelings; the watcher feels shut out and pushes harder. Home and family turn into a battleground: whose mother, whose house, whose way of doing the holidays. The trap: emotional control disguised as closeness. The move: the intense one trusts an 'I'm fine' for one full day before asking again, and the other checks back in first.",
  },
  "Moon-Saturn": {
    supportive: "One of you feels things fast and the other makes those feelings safe to have. You two are the couple that keeps showing up: after the funeral, through the layoff, in the hospital hallway at 3am. Tenderness here looks like follow-through, not poetry. The trap: the stable one never admits being scared, so the sensitive one carries all the visible emotion for both of you. The move: the steady one says one real worry out loud each week, and the other simply listens.",
    challenging: "One of you comes home raw and the other says 'you're overreacting.' Moods get policed, tears get timed, and the softer one learns to cry in the car before walking in. The stricter one isn't cruel; they grew up in a house where feelings cost too much. The trap: love turning into supervision. The move: the steady one makes a private promise, no advice for ten minutes, and just stays in the room with a hand on a shoulder.",
  },
  "Moon-Sun": {
    supportive: "One of you walks in and the room gets brighter; the other quietly makes sure there's food, a blanket, and someone asking how the day actually went. You two fall into a household rhythm fast: who drives, who plans the birthday, who calls the mother back. Friends say you finish each other's sentences, and it's true. The trap: the shining one stops asking what the caring one needs, because they never complain. The move: once a week, trade places, and the quiet one gets looked after for a whole evening.",
    challenging: "One of you wants applause for the promotion; the other wants you home by seven and noticed you didn't text. Pride and hurt collide in the kitchen: one says 'you never celebrate me,' the other hears 'your needs are small.' You love each other loudly and misread each other nightly. The trap: keeping score of who gave up more for whom. The move: before any big announcement, ask 'Do you need me to cheer or to sit with you?' and give exactly that.",
  },
  "Moon-Uranus": {
    supportive: "One of you finally feels safe being strange, and the other finally feels at home somewhere unconventional. You two build a nest that looks nothing like your parents' place: odd hours, open plans, pets named after philosophers. Moods shift fast, and neither of you panics about it. The trap: so much freedom that nobody knows who's actually showing up on the hard day. The move: pick two reliable rituals, like a nightly check-in call, and keep them no matter what.",
    challenging: "One of you needs to know the other is coming home; the other needs to not be asked. Sudden distance after closeness leaves the tender one staring at their phone and blaming themselves, while the free one feels smothered by a simple 'where are you?' You two swing between cuddling and ghosting in the same week. The upside: you learn security that isn't clinging. The trap is punishing need with more space. The move: send a two-word text when plans change, every single time.",
  },
  "Moon-Venus": {
    supportive: "One of you cooks the favorite meal after a rough week before the other even mentions it. Sweetness is the daily language between you two: pet names, soft texts at lunch, the good side of the bed given up without a word. Friends call you the easy couple, and they're mostly right. The trap: avoiding every uncomfortable topic because neither of you wants to spoil the mood. The move: pick one unsaid irritation a month and say it gently over that same favorite meal.",
    challenging: "One of you needs comfort and gets charm instead; the other offers a date night and gets a sulk back. You two want the same closeness but speak it differently, one through hugs and staying in, the other through outings, gifts and looking nice. Hurt piles up quietly and comes out as pouting about money or plans. The trap: both waiting to be loved the right way without ever saying what that is. The move: each of you writes down three things that actually feel like love, then swap lists.",
  },
  "Moon-Vesta": {
    supportive: "Between you, love looks like chores done without being asked: the coffee made the way they like it, the sheets washed before the hard week. One of you finds comfort in routine, and the other turns that routine into a small private ritual you both protect. Friends notice your home feels calm in a way theirs never does. The trap: you become the best-run household with the quietest bedroom. The move: schedule one evening a week where nothing gets cleaned, fixed or planned, only touched.",
    challenging: "One of you needs to fall apart on the couch; the other copes by reorganizing the pantry at midnight. The emotional one reads that focus as abandonment, and the focused one feels smothered when feelings interrupt the task that keeps them sane. You two end up going to bed at different hours and calling it a schedule difference. The trap: each of you guards a way of coping the other is never let into. The move: the busy one sits down for ten full minutes before returning to the work, no phone.",
  },
  "Neptune-Sun": {
    supportive: "One of you looks at the other and sees someone luminous, and the seen one starts becoming that person. Creative, spiritual and compassionate dreams grow inside this relationship. You two share a sense of meaning that friends find a little mysterious. The trap: the idealizing one ignores flaws until reality hits hard, and the idealized one feels pressure to never disappoint. The move: tell each other one unflattering truth about yourselves this month, and love the real version anyway.",
    challenging: "One of you falls in love with a projection and then feels betrayed when the actual human shows up. The other feels unseen and starts bending into the fantasy or hiding who they really are. Lies creep in, small at first: where you were, how much it cost, how you really feel. The trap: loving a picture instead of a person. The move: ask 'what's something about you I keep getting wrong?' and do not argue with the answer.",
  },
  "Neptune-Venus": {
    supportive: "This is the storybook romance: playlists, long night drives, notes left on pillows. One of you sees the other as nearly perfect, and somehow makes them want to live up to it. Music, art, and slow mornings bind you two more than plans do. The trap: ignoring bills, red flags, and ordinary boredom because the dream feels too good to interrupt. The move: hold one practical meeting a month about money, calendar and chores, then light the candle afterward.",
    challenging: "One of you fell for who the other could be, not who they are. Promises get fuzzy, money quietly disappears, and small lies feel kinder than disappointing each other. The dreamier one feels betrayed when reality shows up; the other feels they can never be enough. The trap: loving a fantasy and resenting the human who keeps interrupting it. The move: say one unglamorous truth each week, and keep shared accounts visible to both of you at all times.",
  },
  "North Node-Sun": {
    supportive: "From the first conversation it felt like this person was supposed to show up. One of you walks in confident, and the other suddenly wants to be braver: apply for the job, move cities, stop shrinking in rooms. You two push each other toward a bigger life without nagging. The trap: the bold one becomes the whole plan and the other forgets their own compass. The move: every year, each of you names one goal that has nothing to do with the other, and you both fund it.",
    challenging: "One of you keeps pulling the other toward a future they're not sure they asked for. It feels fated, which makes it hard to argue with and easy to resent when it gets uncomfortable. The more visible one gets tired of being the mentor; the other feels pushed and small at their own dinner table. The trap: calling it destiny so nobody has to negotiate. The move: say 'I want this' or 'I don't' plainly, and let the relationship be a choice, not a prophecy.",
  },
  "North Node-Venus": {
    supportive: "This love feels like the next chapter was written with both of you in it. One of you makes the other's growth feel attractive instead of scary. You two pick up new tastes, cities and friends together, and each year looks different from the last. The trap: the loving one smooths every hard lesson away so nothing actually changes. The move: let the other struggle through one real challenge on their own this year, and cheer from nearby.",
    challenging: "One of you offers comfort and pleasure; the other feels pulled toward a harder, bigger life. Romance starts to feel like a detour instead of the road. The comfortable one feels outgrown; the ambitious one feels guilty for wanting more. The trap: treating love and growth like rivals competing for the same weekends. The move: plan the next big change together, and build one ritual of pleasure into it so neither of you gets left behind.",
  },
  "North Node-Vesta": {
    supportive: "One of you shows up in the other's life at exactly the moment they needed a teacher, coach or example, and the lessons stick. The devoted one's steady habits pull the other toward a future they had only daydreamed about: the degree, the move, the practice finally started. It feels meant, like you two were supposed to find each other now. The trap: the helper becomes a permanent mentor and the relationship stays lopsided. The move: let the student lead one real decision, and follow.",
    challenging: "One of you is racing toward a new life; the other is loyal to a routine that feels like quicksand to the first. The one moving forward calls it growth; the steady one calls it abandonment and doubles down on what they know. You two argue about moving cities, changing jobs, leaving the old church or friend group. The trap: treating devotion as dead weight or change as betrayal. The move: pick one old ritual to carry into the new life together, and one to bury.",
  },
  "Pluto-Sun": {
    supportive: "One of you walked into the other's life and changed its direction: career, confidence, sometimes even the city you live in. You two bring out a harder, stronger version of each other, and people who knew you before notice. Nothing about this bond is casual or small. The trap: the one doing the transforming quietly starts steering the other's choices. The move: celebrate the decisions the other makes without you, especially the ones you would have made differently.",
    challenging: "One of you wants to be seen; the other wants to be in charge of how. Every success turns into a question of who gets credit, and every setback into who's to blame. The confident one feels pressured and picked apart; the intense one feels dismissed and pushes harder. The trap: a power struggle you pretend is about the dishes. The move: divide decisions openly, so each of you fully owns certain areas of life with no second-guessing from the other.",
  },
  "Pluto-Venus": {
    supportive: "This attraction is magnetic and slightly frightening: one of you can't stop thinking about the other, and the other secretly loves being wanted that much. You two go deep fast, secrets by week two and fused lives by month four. Loving each other changes both of you for good. The trap: devotion sliding into checking phones and needing to know where the other is. The move: each of you keeps one friendship, one hobby, and one evening a week that belong only to you.",
    challenging: "One of you loves intensely and the other feels owned by it. Jealousy flares over exes, coworkers, even a liked photo, and gifts start arriving with strings. The desired one pulls back, which makes the intense one grip harder. The trap: power games dressed up as passion, the silent treatments, the withheld affection, the little loyalty tests. The move: say the fear itself, 'I'm scared you'll leave,' instead of acting it out, and never go through each other's messages.",
  },
  "Pluto-Vesta": {
    supportive: "One of you has a calling, and the other wants to go all the way down into it with them. Together you two treat a shared cause, faith or craft like a life-or-death mission, and you actually change things: sobriety held, a company rebuilt, a family pattern ended. That intensity bonds you tighter than romance alone would. The trap: the cause becomes the relationship, and nothing is left when it ends. The move: keep one part of your life together that has no mission attached, just the two of you.",
    challenging: "One of you is jealous of the other's work, practice or faith, and it shows up as control dressed as concern. Questions about late hours become interrogations; the gym, the studio or the church starts to feel like a rival lover. The devoted one gets secretive to protect what matters to them, which confirms the fear. You two keep fighting about the thing neither of you calls jealousy. The trap: trying to own someone's purpose. The move: the jealous one visits that world once and asks what it gives them.",
  },
  "Saturn-Saturn": {
    supportive: "You two take commitment the same way: slowly, seriously, and for keeps. Neither of you rushes, and neither of you ghosts. You understand each other's fear of failing without needing to explain it, and you build a life with real foundations: savings, routines, promises kept. Hard years bend you but do not break you. The trap: two responsible adults who forget how to be silly. The move: plan one ridiculous thing per season, karaoke or a road trip with no hotel booked, and actually go.",
    challenging: "You two carry the same weight at the same moments, so when one of you panics about money or getting older, the other panics too, and nobody holds the flashlight. Criticism flows both ways and feels deserved. You meet years of obligations but rarely say the tender thing. The trap: a relationship that functions perfectly and feels like a job. The move: once a week, each of you names one fear out loud, and the other simply says 'I'm here' without fixing it.",
  },
  "Saturn-Sun": {
    supportive: "One of you shines; the other gives that shine a spine. You two are the couple who actually builds the business, finishes the renovation, and shows up to every family obligation on time. The steadier one is proud without gushing, and the brighter one learns to trust that quiet pride. The trap: the relationship turns into a project plan where praise only arrives after results. The move: say 'I'm proud of you' before the outcome is known, not only once it's a win.",
    challenging: "One of you walks in with an idea and the other lists five reasons it won't work. The bold one starts pitching less; the cautious one feels like the only adult in the house. Respect is real, warmth is rationed, and criticism arrives faster than applause. The trap: parenting each other instead of partnering. The move: the careful one answers every new idea with one genuine 'yes, and' before any concern, and the bold one asks for the honest risks on purpose.",
  },
  "Saturn-Venus": {
    supportive: "This love is built to last, not to dazzle. One of you shows affection with sweetness and small gifts; the other shows it by fixing the car, paying the bill on time, and still being there in year six. You two budget well together and your joint plans actually stick. The trap: romance gets filed under 'later' once the mortgage is sorted. The move: put a real date in the calendar every month and protect it like a bill that cannot bounce.",
    challenging: "One of you reaches for affection and gets a raised eyebrow or a lecture about spending. The warmer one starts to feel like too much; the stricter one feels taken for granted and quietly counts favors. You stay together out of loyalty long after the play has gone out of it. The trap: love turning into a ledger of what you owe each other. The move: once a week the careful one gives something unearned, a compliment, a gift, a yes, with no conditions attached.",
  },
  "Saturn-Vesta": {
    supportive: "You two build like people planning for fifty years: the savings account, the practice, the business, the garden nobody else would wait on. One of you brings patience and structure; the other brings a quiet devotion that makes the grind feel meaningful. Friends call you boring and then come to you for advice. The trap: duty crowds out delight until you forget you are also lovers. The move: put one completely useless, joyful thing on the calendar each month and treat it as seriously as a deadline.",
    challenging: "One of you grades the other's commitment, and the other secretly believes they will never be disciplined enough to pass the test. Every missed workout, abandoned course or late invoice gets noticed and filed. The devoted one works harder to prove themselves and resents the stopwatch. You two become supervisor and employee in your own kitchen. The trap: love that feels conditional on output. The move: the critical one names three things the other kept showing up for, without adding 'but.'",
  },
  "Sun-Sun": {
    supportive: "You two recognize yourselves in each other, and it feels easy. Your pride points in compatible directions, so one person's win genuinely thrills the other. You make a striking pair at parties and cheer each other on in public, and goals line up without negotiation. The trap: you mirror each other so well that blind spots double, and nobody calls out the shared ego. The move: invite one honest friend to tell you both what you are not seeing, and listen without defending.",
    challenging: "Two people who both want to be the main character. One of you tells the story at dinner and the other corrects the ending. Promotions, compliments, even who the dog loves more become quiet competitions. You respect each other and still feel overshadowed. The trap: needing to shine by dimming the other. The move: take turns having a 'your night' where one of you gets the full spotlight, the stories and the choices, and the other plays the proud supporting role.",
  },
  "Sun-Uranus": {
    supportive: "One of you shows up and the other's whole life gets rearranged in the best way: new city, new haircut, new belief about what's possible. You two are the couple who elopes, quits jobs together, or books the trip on a whim. Neither of you wants a partner who asks for permission. The trap: mistaking restlessness for growth and burning through stability for fun. The move: keep one boring, unbreakable ritual, like the same weekend breakfast, to anchor all the chaos.",
    challenging: "One of you wants to be the center of the other's world; the other needs to prove nobody owns them. Cancelled plans, a solo trip announced like a weather report, a sudden cold spell right after a big moment together. The proud one feels humiliated, and the free one feels caged. You two keep daring each other to leave. The upside: nothing goes stale here. The trap is testing loyalty with distance. The move: name how much space you need, in actual days, before you take it.",
  },
  "Sun-Venus": {
    supportive: "One of you lights up when the other walks in, and doesn't bother hiding it. Compliments come easily, gifts are well chosen, and you two look good together in photos without trying. There's real admiration here, not just attraction, and friends feel it at dinner. The trap: you both dodge anything unflattering, so hard news gets swallowed to keep the glow. The move: agree that one blunt conversation a month doesn't cancel the romance, then have it and still go out afterward.",
    challenging: "One of you pours out affection and the other soaks it up but forgets to send it back. Charm is everywhere and depth is scarce: you two are great at parties and awkward over bills. The admiring one starts to feel like an audience instead of a partner. The trap: flattering each other instead of being honest about who is carrying more. The move: the one who receives more plans the next three dates, pays for one, and asks what the other actually wants.",
  },
  "Sun-Vesta": {
    supportive: "One of you walks into a room wanting to be seen, and the other quietly makes sure the lighting is right. You two turn one person's ambition into a joint mission: the late-night rehearsals, the proofread pitch deck, the partner who shows up to every gig. The quieter one feels chosen by being useful, and the brighter one grows faster than they would alone. The trap: the helper disappears inside the other's spotlight. The move: once a month, put the helper's project at the center and show up for it just as loudly.",
    challenging: "One of you wants applause, the other wants the work done right, and neither says it out loud. The focused one rolls their eyes at the performing, and the proud one feels like a hobby next to the other's real commitments. You fight about phones at dinner, about who cancelled for work, about whose goal gets the weekend. Underneath, both of you are begging to be taken seriously. The trap: keeping score of sacrifices. The move: say exactly what you admire about the other's pursuit, in front of someone else.",
  },
  "Uranus-Venus": {
    supportive: "The attraction hit fast and felt unlike anything either of you had before. You two keep romance weird on purpose: surprise weekend trips, strange dates, a relationship deal you wrote yourselves. One of you makes the other feel desired without feeling owned. Friends call you unconventional and a little enviable. The trap: needing constant novelty to feel the spark. The move: plan one surprise a month and one completely ordinary night in, and treat both as sacred.",
    challenging: "One of you falls in love with the thrill, the other with the person, and that mismatch shows up the minute things get steady. Hot-and-cold texting, a flirtation that's 'nothing,' money spent on impulse and called spontaneity. You two break up and get back together more often than you tell your friends. The upside: the chemistry never goes dull. The trap is using unpredictability to test love. The move: define exclusivity and budget out loud, in words, before the next wild idea.",
  },
  "Venus-Venus": {
    supportive: "You two like the same things: the same restaurants, the same music, the same kind of lazy weekend morning. Decorating a home is easy, gifts actually get used, and affection feels natural, never forced. Friends say you look like you belong together. The trap: you avoid friction so well that real disagreements never get aired, and both of you swallow small resentments to keep things pretty. The move: have one honest, uncomfortable conversation a month where keeping the peace is not the goal.",
    challenging: "You two love differently and keep offering what you would want instead of what the other wants. One of you buys gifts; the other wanted time. One of you plans a fancy dinner; the other craved takeout on the couch. Taste clashes show up in the apartment, the wardrobe, even how to spend a bonus. The trap: feeling unloved while being loved in the wrong language. The move: each of you writes three specific gestures that make you feel adored, swaps lists, and uses them.",
  },
  "Venus-Vesta": {
    supportive: "One of you courts; the other treats being courted like something sacred and never takes it for granted. Date nights become rituals you two refuse to cancel, and small gifts carry more weight than they would with anyone else. You spend money on the same few things you both consider worth it and skip everything flashy. The trap: romance turns so ceremonial that spontaneous flirting starts to feel off-script. The move: break the ritual on purpose, a random weeknight kiss in the kitchen, and let it be messy.",
    challenging: "One of you wants to be adored on a Friday night, and the other is still in monk mode, finishing something that apparently matters more. The affectionate one starts dressing up for no one, and the devoted one feels guilty and resentful in the same breath. You two argue about money spent on pleasure versus money saved for the mission. The trap: one of you becomes a distraction and the other becomes a closed door. The move: agree on protected hours for work and protected hours for each other, and honor both.",
  },
  "Vesta-Vesta": {
    supportive: "You two recognize something rare in each other: the same way of disappearing into what matters. Neither of you takes it personally when the other goes quiet for three hours, because you do it too. You protect each other's focus like it is sacred, and working in the same room feels like intimacy. The trap: two people forgetting dinner, forgetting friends, forgetting to touch. The move: set one alarm a day that means stop, find each other, and sit close for twenty minutes.",
    challenging: "You two are devoted to different altars and each quietly thinks theirs is holier. One of you sacrifices for career, the other for family or faith, and every weekend becomes a silent vote on whose calling wins. You both work hard, both feel unappreciated, both keep lists. The trap: comparing sacrifices like receipts at a return counter. The move: spend one weekend fully inside the other's world, doing their tasks their way, and say nothing about how you would do it better.",
  },
};

const PASSION_READINGS: Record<string, string> = {
  Volcanic: "You two can't share a room without it turning into something. The pull hits before logic does, which is why your fights and your make-ups blur together. The trap: mistaking heat for resolution. The move: finish the argument before you touch.",
  High: "The spark didn't burn out after the first months, and both of you know it. Touch is how you settle things, check in and say sorry without words. The trap: letting chemistry cover for conversations you keep skipping. The move: say the hard sentence first, then reach for each other.",
  Moderate: "Desire between you two builds with trust instead of hitting on sight. The heat shows up once you both feel safe, and it stalls the moment one of you feels rushed or judged. The trap: deciding the spark is missing when it's just waiting. The move: make time that has no agenda except each other.",
  Low: "Attraction isn't the glue here; respect, humor or loyalty is. You two have to build chemistry on purpose instead of waiting for it to strike. The trap: quietly comparing this to a past fling that burned hot. The move: plan the date, the trip, the night, and treat desire as something you practice.",
};

const MARRIAGE_READINGS: Record<string, string> = {
  Exceptional: "This is the kind of bond people build a whole life on: shared home, shared money, shared plans ten years out. It feels so settled that the danger is coasting. The move: keep choosing each other out loud, especially when it's boring.",
  Strong: "You two handle the unglamorous parts well: bills, chores, showing up when nothing exciting is happening. That's what long-term actually runs on. The trap: becoming great roommates and forgetting to flirt.",
  Promising: "The foundation is there, but it only holds with agreements said out loud: money, space, whose family gets the holidays. Leave those unspoken and resentment fills the gaps.",
  Possible: "Commitment works for you two only if you design it on your own terms. Copying the standard script (same house, same timeline as everyone else) will chafe. Write your own rules and revisit them every year.",
  Unlikely: "This connection is built for intensity or growth more than a quiet shared mortgage. If forever is what you want, you'll have to build the structure deliberately, because it won't form on its own.",
};

const BODY_ALIASES: Record<string, string> = {
  ASC: 'Ascendant', Rising: 'Ascendant', DSC: 'Descendant', Midheaven: 'MC', 'True Node': 'North Node', 'Mean Node': 'North Node',
};

function body(name: string): string {
  return BODY_ALIASES[name] || name;
}

/** Reading for a synastry pair, or null when that pair has none written. */
export function getSynastryPairReading(planet1: string, planet2: string, supportive: boolean): string | null {
  const entry = PAIR_READINGS[[body(planet1), body(planet2)].sort().join('-')];
  if (!entry) return null;
  return supportive ? entry.supportive : entry.challenging;
}

export function getPassionReading(intensity: string | null | undefined): string | null {
  return (intensity && PASSION_READINGS[intensity]) || null;
}

export function getMarriageReading(level: string | null | undefined): string | null {
  return (level && MARRIAGE_READINGS[level]) || null;
}
