'use client';

import { useTranslation } from 'react-i18next';
import Link from 'next/link';
import { ArrowLeft, FileText } from 'lucide-react';

export default function TermsPage() {
  const { t } = useTranslation();
  return (
    <div className="max-w-2xl mx-auto">
      <Link href="/settings" className="btn-ghost p-2 inline-flex items-center gap-1 mb-4">
        <ArrowLeft className="w-4 h-4" /> {t('common.settings')}
      </Link>

      <h1 className="text-2xl font-display font-bold text-text-primary mb-6 flex items-center gap-3">
        <FileText className="w-7 h-7 text-accent-primary" />
        {t('settings.termsPage.title')}
      </h1>

      <div className="card space-y-6">
        <p className="text-xs text-accent-secondary">Effective Date: March 21, 2026</p>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">1. Acceptance of Terms</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            By downloading, installing, or using Align (&quot;the App&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">2. Eligibility</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            You must be at least 18 years old to use Align. By using the App, you represent that you meet this age requirement.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">3. Account Registration</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate birth information for chart calculations. You may update your information at any time through the Profile settings.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">4. Subscription Plans</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            Align offers four subscription tiers:
          </p>
          <ul className="text-sm text-text-secondary mt-2 space-y-1 list-disc list-inside">
            <li>Free — $0/month</li>
            <li>Light — $9/month</li>
            <li>Premium — $19/month</li>
            <li>Pro — $29/month</li>
          </ul>
          <p className="text-sm text-text-secondary leading-relaxed mt-2">
            Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current billing period. You can manage and cancel subscriptions through your App Store or Google Play account settings.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">5. Free Trial</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            If a free trial is offered, it will automatically convert to a paid subscription at the end of the trial period unless cancelled. You will not be charged during the trial.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">6. AI-Generated Content</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            Align uses artificial intelligence (Claude by Anthropic) to generate chart interpretations and readings. AI-generated content is for entertainment, self-reflection, and educational purposes only. It should not be considered professional advice of any kind — medical, financial, legal, or psychological.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">7. Financial Report Disclaimer</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            The Financial Report feature provides astrological perspectives on financial themes in your chart. This is NOT financial advice. Do not make investment, business, or financial decisions based on astrological readings. Always consult a qualified financial advisor.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">8. Acceptable Use</h3>
          <p className="text-sm text-text-secondary leading-relaxed">You agree not to:</p>
          <ul className="text-sm text-text-secondary mt-2 space-y-1 list-disc list-inside">
            <li>Use the App for any unlawful purpose</li>
            <li>Attempt to reverse-engineer or copy the App</li>
            <li>Scrape, harvest, or automate data collection</li>
            <li>Share your account credentials with others</li>
            <li>Resell or redistribute readings generated by the App</li>
          </ul>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">9. Intellectual Property</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            All content, features, and functionality of Align — including the design, algorithms, text, graphics, and AI interpretations — are owned by Align and protected by copyright and intellectual property laws.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">10. Limitation of Liability</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            Align provides its services &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the App, including but not limited to decisions made based on astrological readings.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">11. Termination</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            We reserve the right to suspend or terminate your account at any time for violation of these Terms. You may delete your account at any time through the App settings.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">12. Governing Law</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to conflict of law principles.
          </p>
        </section>

        <section>
          <h3 className="text-sm font-semibold text-text-primary mb-2">13. Contact</h3>
          <p className="text-sm text-text-secondary leading-relaxed">
            For questions about these Terms, contact us at: Tametryol@gmail.com
          </p>
        </section>

        <p className="text-xs text-text-muted text-center pt-4">&copy; 2026 Align. All rights reserved.</p>
      </div>
    </div>
  );
}
