import type { ZodiacSign } from './types';

export interface NodeAxisMeaning {
  southSign: ZodiacSign;
  northSign: ZodiacSign;
  oldSuperpower: string;
  comfortTrap: string;
  shadowMisuse: string;
  purposeDoor: string;
  purposeDemand: string;
  emotionalWound: string;
  coreGift: string;
  mainFear: string;
  mainTemptation: string;
  relationshipPattern: string;
  careerPattern: string;
  missionStyle: string;
  settings: string[];
  archetypes: string[];
  comfortVerbs: string[];
  shadowVerbs: string[];
  purposeVerbs: string[];
  scar: string;
  scarGift: string;
  relicName: string;
  relicMemory: string;
  prophecy: string;
}

export const NODE_AXIS_MEANINGS: Record<ZodiacSign, NodeAxisMeaning> = {
  Aries: {
    southSign: 'Aries',
    northSign: 'Libra',
    oldSuperpower: 'You have survived by moving first, fighting alone, and becoming the blade before anyone could raise one against you.',
    comfortTrap: 'The soul reaches for speed, conquest, and solitude when tenderness asks for patience.',
    shadowMisuse: 'Courage becomes domination, desire becomes impatience, and every bond becomes a battlefield.',
    purposeDoor: 'The next life opens through alliance, listening, beauty, and the dangerous grace of choosing together.',
    purposeDemand: 'Let another soul matter without making them an enemy to defeat.',
    emotionalWound: 'Someone once taught you that needing help was the beginning of defeat.',
    coreGift: 'fearless ignition',
    mainFear: 'being slowed down by love',
    mainTemptation: 'winning quickly and standing alone afterward',
    relationshipPattern: 'you attract mirrors who ask whether victory is worth loneliness',
    careerPattern: 'warrior, pioneer, guard, athlete, champion, first responder',
    missionStyle: 'turn conflict into conscious partnership',
    settings: ['a border fortress', 'a rebel camp', 'a dueling academy'],
    archetypes: ['The Lone Blade', 'The First Fire', 'The Treaty Breaker'],
    comfortVerbs: ['strike first', 'walk out', 'claim the prize alone'],
    shadowVerbs: ['humiliate the rival', 'turn desire into conquest', 'make peace impossible'],
    purposeVerbs: ['ask for counsel', 'share the victory', 'choose the vow over the crown'],
    scar: 'Fear of dependence',
    scarGift: 'brave interdependence',
    relicName: 'The Split Shield',
    relicMemory: 'You remember the day victory felt hollow because no one was left beside you.',
    prophecy: 'The sword lowers only when the hand beside yours stops feeling like a threat.',
  },
  Taurus: {
    southSign: 'Taurus',
    northSign: 'Scorpio',
    oldSuperpower: 'You know how to build, endure, preserve, and make the body safe when the world becomes unreliable.',
    comfortTrap: 'The soul clings to what can be touched, owned, eaten, saved, or controlled through habit.',
    shadowMisuse: 'Stability becomes possession, pleasure becomes numbness, and loyalty becomes refusal to transform.',
    purposeDoor: 'The next life opens through surrender, intimacy, truth, shared power, and the courage to enter the underworld cleanly.',
    purposeDemand: 'Stop mistaking stillness for safety when the soul is asking to shed its skin.',
    emotionalWound: 'A loss taught you that anything loved must be held tightly or buried before it can leave.',
    coreGift: 'embodied value mastery',
    mainFear: 'losing security, money, body, land, or love',
    mainTemptation: 'choosing comfort even when the old life is already dead',
    relationshipPattern: 'you return to bonds where trust requires shared vulnerability, not ownership',
    careerPattern: 'builder, farmer, singer, banker, artisan, land keeper',
    missionStyle: 'exchange possession for transformation',
    settings: ['a prosperous valley with buried secrets', 'a merchant city', 'a temple of gold and grief'],
    archetypes: ['The Keeper of the Vault', 'The Garden Builder', 'The Body Oracle'],
    comfortVerbs: ['hold the treasure', 'stay with the familiar', 'protect the body from every risk'],
    shadowVerbs: ['buy loyalty', 'refuse change', 'make love prove itself through possession'],
    purposeVerbs: ['enter the hidden room', 'share the burden', 'trust the death that makes life possible'],
    scar: 'Fear of loss',
    scarGift: 'deep trust and regenerative courage',
    relicName: 'The Buried Coin',
    relicMemory: 'You remember a field bought with silence, and the secret it could not keep buried.',
    prophecy: 'The treasure is not stolen. It is transformed when you finally open your hands.',
  },
  Gemini: {
    southSign: 'Gemini',
    northSign: 'Sagittarius',
    oldSuperpower: 'You have lived by listening fast, changing names, carrying messages, and escaping through cleverness.',
    comfortTrap: 'The soul gathers fragments, rumors, options, and exits instead of committing to the truth that burns.',
    shadowMisuse: 'Language becomes manipulation, knowledge becomes avoidance, and every road becomes a reason not to choose.',
    purposeDoor: 'The next life opens through meaning, faith, honest teaching, long journeys, and one truth spoken from the whole body.',
    purposeDemand: 'Trade the clever answer for the honest pilgrimage.',
    emotionalWound: 'You learned to stay safe by never letting anyone know which version of you was real.',
    coreGift: 'adaptive intelligence',
    mainFear: 'being trapped by one truth',
    mainTemptation: 'talking your way around the lesson',
    relationshipPattern: 'you meet souls who force words to become vows',
    careerPattern: 'messenger, translator, trader, scribe, spy, storyteller',
    missionStyle: 'turn scattered knowledge into lived wisdom',
    settings: ['a border market', 'a tower of forbidden maps', 'a road between warring kingdoms'],
    archetypes: ['The Silver Messenger', 'The Many-Named Scribe', 'The Road-Tongued Trickster'],
    comfortVerbs: ['change the subject', 'trade the secret', 'keep every option alive'],
    shadowVerbs: ['lie beautifully', 'sell both sides the same promise', 'turn truth into performance'],
    purposeVerbs: ['tell the whole truth', 'tell the truth on the road that has no shortcut', 'teach what cost you something'],
    scar: 'Fear of commitment',
    scarGift: 'truth-speaking wisdom',
    relicName: 'The Sealed Letter',
    relicMemory: 'You remember the message you delivered but never dared to read aloud.',
    prophecy: 'The map becomes a door only after the messenger stops running.',
  },
  Cancer: {
    southSign: 'Cancer',
    northSign: 'Capricorn',
    oldSuperpower: 'You know how to protect, remember, feed, hide, and keep a family alive through storms.',
    comfortTrap: 'The soul retreats into the old house, the old ache, the old loyalty, and calls it love.',
    shadowMisuse: 'Care becomes control, memory becomes guilt, and tenderness becomes a chain around the future.',
    purposeDoor: 'The next life opens through structure, authority, self-respect, public mastery, and clean responsibility.',
    purposeDemand: 'Build the life your younger self needed instead of living forever inside the wound.',
    emotionalWound: 'The child inside this lifetime is still waiting at the door where someone once left and never came back.',
    coreGift: 'ancestral memory and protection',
    mainFear: 'abandonment',
    mainTemptation: 'keeping everyone close by staying needed',
    relationshipPattern: 'you meet souls who test whether care can exist without clinging',
    careerPattern: 'caretaker, innkeeper, family heir, midwife, protector, memory keeper',
    missionStyle: 'turn private pain into mature stewardship',
    settings: ['an ancestral coastal house', 'a village after famine', 'a royal nursery with locked doors'],
    archetypes: ['The House Keeper', 'The Moon-Wounded Heir', 'The Protector of Names'],
    comfortVerbs: ['return home', 'save everyone first', 'hide inside loyalty'],
    shadowVerbs: ['make guilt sound like love', 'punish anyone who leaves', 'refuse adulthood'],
    purposeVerbs: ['take authority', 'build a boundary', 'become the shelter without becoming the cage'],
    scar: 'Fear of abandonment',
    scarGift: 'emotional independence',
    relicName: 'The Childs Toy',
    relicMemory: 'You remember a small hand waiting for a promise that never came back.',
    prophecy: 'The house stops haunting you when you become its foundation, not its prisoner.',
  },
  Leo: {
    southSign: 'Leo',
    northSign: 'Aquarius',
    oldSuperpower: 'You have known radiance, performance, command, romance, and the sacred heat of being witnessed.',
    comfortTrap: 'The soul reaches for applause, specialness, courtly drama, and the throne it already knows how to hold.',
    shadowMisuse: 'Light becomes vanity, leadership becomes spectacle, and love becomes proof that the soul still matters.',
    purposeDoor: 'The next life opens through friendship, community, systems, future vision, and service to something larger than personal glory.',
    purposeDemand: 'Let the gift belong to the circle without making your heart disappear.',
    emotionalWound: 'A lifetime taught you that being unseen felt like being erased.',
    coreGift: 'creative radiance',
    mainFear: 'being ordinary or forgotten',
    mainTemptation: 'choosing drama because it feels like proof of life',
    relationshipPattern: 'you meet souls who ask whether love is still real when nobody is applauding',
    careerPattern: 'performer, sovereign, artist, royal child, champion, patron',
    missionStyle: 'turn personal shine into collective liberation',
    settings: ['a royal theater', 'a palace before a revolution', 'a city of inventors who distrust kings'],
    archetypes: ['The Fallen Star', 'The Golden Child', 'The Heart Sovereign'],
    comfortVerbs: ['take center stage', 'make the wound theatrical', 'demand proof of devotion'],
    shadowVerbs: ['steal the circle light', 'turn love into worship', 'banish the rival performer'],
    purposeVerbs: ['share the stage', 'protect the strange ones', 'lead without needing a throne'],
    scar: 'Fear of being unseen',
    scarGift: 'heart-led leadership',
    relicName: 'The Broken Crown',
    relicMemory: 'You remember the crown cracking in your hands while the people outside kept singing.',
    prophecy: 'The star becomes a constellation only when it stops fearing the other lights.',
  },
  Virgo: {
    southSign: 'Virgo',
    northSign: 'Pisces',
    oldSuperpower: 'You have mastered craft, medicine, discipline, diagnosis, service, and the sacred repair of broken systems.',
    comfortTrap: 'The soul tries to earn safety by being useful, flawless, prepared, and impossible to criticize.',
    shadowMisuse: 'Discernment becomes judgment, service becomes martyrdom, and skill becomes a wall against grace.',
    purposeDoor: 'The next life opens through surrender, mercy, imagination, mystery, forgiveness, and trust in the unseen.',
    purposeDemand: 'Let the ritual be holy without needing every thread under control.',
    emotionalWound: 'You were loved for what you fixed, then forgot you were allowed to be held when you could fix nothing.',
    coreGift: 'sacred precision',
    mainFear: 'being useless, messy, or wrong',
    mainTemptation: 'perfecting the cage instead of leaving it',
    relationshipPattern: 'you meet souls who cannot be repaired, only loved',
    careerPattern: 'healer, apprentice, archivist, ritual keeper, midwife, analyst',
    missionStyle: 'turn control into compassion',
    settings: ['a plague infirmary', 'a monastery workshop', 'a flooded archive of prayers'],
    archetypes: ['The Sacred Healer', 'The Needle Keeper', 'The Perfect Servant'],
    comfortVerbs: ['correct the flaw', 'work until collapse', 'make a plan for the unknowable'],
    shadowVerbs: ['shame the wounded', 'withhold help until it is earned', 'turn purity into punishment'],
    purposeVerbs: ['forgive the unfinished', 'follow the dream', 'offer mercy before certainty'],
    scar: 'Fear of imperfection',
    scarGift: 'healing mercy',
    relicName: 'The Healers Bowl',
    relicMemory: 'You remember washing blood from your hands and still feeling unclean.',
    prophecy: 'The wound closes when the healer lets the water touch them too.',
  },
  Libra: {
    southSign: 'Libra',
    northSign: 'Aries',
    oldSuperpower: 'You know charm, treaty, elegance, listening, alliance, and the art of surviving through relationship.',
    comfortTrap: 'The soul waits for permission, reads the room, softens the truth, and calls self-erasure peace.',
    shadowMisuse: 'Harmony becomes manipulation, beauty becomes leverage, and love becomes a mirror with no self behind it.',
    purposeDoor: 'The next life opens through direct desire, courage, clean anger, self-claiming, and the first honest move.',
    purposeDemand: 'Choose yourself without turning love into a trial.',
    emotionalWound: 'A vow once taught you that being chosen mattered more than being true.',
    coreGift: 'relational intelligence',
    mainFear: 'losing love by wanting something',
    mainTemptation: 'keeping peace by betraying the self',
    relationshipPattern: 'you keep meeting the same soul in different faces because the vow was never completed',
    careerPattern: 'diplomat, artist, spouse, negotiator, court adviser, matchmaker',
    missionStyle: 'turn pleasing into courageous choice',
    settings: ['a marriage court', 'a diplomatic city', 'a ballroom before a duel'],
    archetypes: ['The Unchosen Bride', 'The Silver Diplomat', 'The Mirror-Bound Lover'],
    comfortVerbs: ['make everyone comfortable', 'wait to be chosen', 'hide the anger'],
    shadowVerbs: ['seduce the decision', 'betray privately to preserve beauty', 'make love a negotiation'],
    purposeVerbs: ['speak first', 'leave the room cleanly', 'fight for the life with your name on it'],
    scar: 'Fear of rejection',
    scarGift: 'self-honoring courage',
    relicName: 'The Lovers Ring',
    relicMemory: 'You remember a ring that fit perfectly and still felt like a locked door.',
    prophecy: 'The vow heals when the soul stops asking love to choose in its place.',
  },
  Scorpio: {
    southSign: 'Scorpio',
    northSign: 'Taurus',
    oldSuperpower: 'You have survived darkness through instinct, strategy, passion, secrecy, and emotional x-ray vision.',
    comfortTrap: 'The soul returns to crisis, control, suspicion, revenge, and the old feeling that danger is home.',
    shadowMisuse: 'Depth becomes obsession, protection becomes manipulation, and love becomes a war for power.',
    purposeDoor: 'The next life opens through peace, self-worth, body wisdom, simplicity, money mastery, beauty, and calm power.',
    purposeDemand: 'Stop needing chaos to feel alive, and build something that does not require a wound to keep it burning.',
    emotionalWound: 'A betrayal trained your nervous system to call peace suspicious.',
    coreGift: 'survival intelligence',
    mainFear: 'trusting what cannot be controlled',
    mainTemptation: 'entering the underworld again just to feel powerful',
    relationshipPattern: 'you attract souls who test whether intimacy can exist without control',
    careerPattern: 'detective, occultist, strategist, healer, survivor, keeper of secrets',
    missionStyle: 'turn crisis power into embodied peace',
    settings: ['an ancient coastal village with forbidden rites', 'a palace of spies', 'a valley hiding a family curse'],
    archetypes: ['The Underworld Survivor', 'The Secret Keeper', 'The Storm-Blood Healer'],
    comfortVerbs: ['investigate the betrayal', 'control the lover', 'destroy the threat first'],
    shadowVerbs: ['use fear as currency', 'make obsession look like devotion', 'win through hidden influence'],
    purposeVerbs: ['plant the seed', 'trust the slow vow', 'choose the body over the battle'],
    scar: 'Fear of betrayal',
    scarGift: 'discernment and peaceful power',
    relicName: 'The Mystics Mirror',
    relicMemory: 'You remember seeing the truth in everyone except the part of you that wanted rest.',
    prophecy: 'The door opens only after you refuse the old crown of crisis.',
  },
  Sagittarius: {
    southSign: 'Sagittarius',
    northSign: 'Gemini',
    oldSuperpower: 'You have lived as a prophet, traveler, outlaw, teacher, and keeper of the far horizon.',
    comfortTrap: 'The soul escapes through certainty, distance, doctrine, humor, or the next road out.',
    shadowMisuse: 'Truth becomes arrogance, freedom becomes abandonment, and belief becomes a weapon.',
    purposeDoor: 'The next life opens through listening, questions, local bonds, nuance, and the humility to learn from the small road.',
    purposeDemand: 'Let curiosity interrupt certainty before the soul mistakes escape for wisdom.',
    emotionalWound: 'You were once punished for staying, so the horizon began to feel safer than home.',
    coreGift: 'visionary faith',
    mainFear: 'being trapped in a small life',
    mainTemptation: 'leaving before the lesson becomes intimate',
    relationshipPattern: 'you meet souls who ask you to stay long enough to hear them',
    careerPattern: 'pilgrim, judge, teacher, explorer, preacher, storyteller',
    missionStyle: 'turn certainty into living dialogue',
    settings: ['a desert pilgrimage road', 'a foreign court', 'a school built on disputed doctrine'],
    archetypes: ['The Wandering Oracle', 'The Laughing Exile', 'The Heretic Teacher'],
    comfortVerbs: ['ride away', 'preach the answer', 'mock the small concern'],
    shadowVerbs: ['use truth to wound', 'abandon the dependent', 'turn faith into law'],
    purposeVerbs: ['ask the next question', 'listen to the nearby voice', 'stay for the unfinished conversation'],
    scar: 'Fear of confinement',
    scarGift: 'humble wisdom',
    relicName: 'The Exiles Map',
    relicMemory: 'You remember every road out and the one face you never returned to.',
    prophecy: 'The horizon kneels inside the question you almost refused to ask.',
  },
  Capricorn: {
    southSign: 'Capricorn',
    northSign: 'Cancer',
    oldSuperpower: 'You know duty, ambition, strategy, restraint, authority, and how to survive winter with no witness.',
    comfortTrap: 'The soul hardens, performs, climbs, controls, and calls loneliness maturity.',
    shadowMisuse: 'Mastery becomes coldness, authority becomes punishment, and success becomes a fortress without a hearth.',
    purposeDoor: 'The next life opens through tenderness, family repair, emotional honesty, rest, home, and the courage to need.',
    purposeDemand: 'Let the heart become a place of authority too.',
    emotionalWound: 'You were made responsible before you were allowed to be young.',
    coreGift: 'long-game mastery',
    mainFear: 'softness making you unsafe',
    mainTemptation: 'choosing the title over the person waiting at home',
    relationshipPattern: 'you meet souls who ask whether duty can include warmth',
    careerPattern: 'ruler, builder, elder, general, judge, mountain guide',
    missionStyle: 'turn achievement into emotional guardianship',
    settings: ['a snowbound court', 'a mountain citadel', 'a city built on debt and discipline'],
    archetypes: ['The Winter Sovereign', 'The Burdened Heir', 'The Stone-Bound Master'],
    comfortVerbs: ['carry it alone', 'choose duty over feeling', 'make a law for the wound'],
    shadowVerbs: ['punish weakness', 'trade love for rank', 'make fear sound responsible'],
    purposeVerbs: ['return home', 'cry without bargaining', 'protect tenderness as seriously as power'],
    scar: 'Fear of vulnerability',
    scarGift: 'nurturing authority',
    relicName: 'The Judges Seal',
    relicMemory: 'You remember stamping the sentence and feeling the child inside you go silent.',
    prophecy: 'The mountain bows when the ruler learns the language of the hearth.',
  },
  Aquarius: {
    southSign: 'Aquarius',
    northSign: 'Leo',
    oldSuperpower: 'You have survived as the outsider, inventor, observer, rebel, and future signal inside a frightened world.',
    comfortTrap: 'The soul detaches, analyzes, leaves the body of the heart, and calls exile freedom.',
    shadowMisuse: 'Genius becomes contempt, rebellion becomes rupture, and cool distance becomes punishment.',
    purposeDoor: 'The next life opens through warmth, art, play, loyal love, creative risk, and being personally seen.',
    purposeDemand: 'Let the strange future have a human heartbeat.',
    emotionalWound: 'A village once made you safer outside the circle than inside your own heart.',
    coreGift: 'liberating vision',
    mainFear: 'being swallowed by ordinary emotion',
    mainTemptation: 'staying untouchable so rejection cannot land',
    relationshipPattern: 'you meet souls who ask you to stop saving humanity while avoiding one heart',
    careerPattern: 'inventor, rebel, astrologer, scientist, reformer, exile',
    missionStyle: 'turn detachment into radiant participation',
    settings: ['an observatory under persecution', 'a city before revolution', 'a workshop of forbidden machines'],
    archetypes: ['The Star Exile', 'The Future Thief', 'The Lightning Friend'],
    comfortVerbs: ['leave the circle', 'explain the feeling away', 'choose theory over touch'],
    shadowVerbs: ['make the group pay for misunderstanding you', 'burn the system without sheltering people', 'use distance as cruelty'],
    purposeVerbs: ['step into the light', 'make the art personal', 'love one soul where all can see'],
    scar: 'Fear of belonging',
    scarGift: 'original heart leadership',
    relicName: 'The Rebels Torch',
    relicMemory: 'You remember a crowd chanting your idea while no one knew your name.',
    prophecy: 'The future trusts you after the heart stops hiding behind the signal.',
  },
  Pisces: {
    southSign: 'Pisces',
    northSign: 'Virgo',
    oldSuperpower: 'You have crossed dreams, temples, oceans, grief, music, and invisible worlds without losing the thread of compassion.',
    comfortTrap: 'The soul dissolves, rescues, sacrifices, escapes, and waits for the universe to choose the shape.',
    shadowMisuse: 'Mysticism becomes avoidance, mercy becomes self-erasure, and longing becomes addiction to the unreachable.',
    purposeDoor: 'The next life opens through craft, boundaries, health, practical service, timing, and the holy precision of daily work.',
    purposeDemand: 'Give the dream a body, a schedule, and hands that finish the medicine.',
    emotionalWound: 'You once became everything for everyone until no one knew where you had gone.',
    coreGift: 'mystical compassion',
    mainFear: 'hard edges, ordinary limits, and disappointing the suffering',
    mainTemptation: 'disappearing into the dream instead of building the altar',
    relationshipPattern: 'you meet souls who test whether rescue is love or avoidance',
    careerPattern: 'mystic, singer, healer, poet, monk, dream interpreter',
    missionStyle: 'turn spiritual longing into embodied service',
    settings: ['a sea temple', 'a monastery at the edge of fog', 'a hospital where dreams speak'],
    archetypes: ['The Dream-Touched Healer', 'The Lost Saint', 'The Veiled Singer'],
    comfortVerbs: ['forgive without boundary', 'escape into vision', 'sacrifice the self again'],
    shadowVerbs: ['use helplessness as a spell', 'make confusion holy', 'drown the vow in longing'],
    purposeVerbs: ['name the boundary', 'practice the craft', 'serve one real body at a time'],
    scar: 'Fear of boundaries',
    scarGift: 'embodied devotion',
    relicName: 'The Priestess Veil',
    relicMemory: 'You remember the veil that made everyone call you holy while nobody asked if you were tired.',
    prophecy: 'The vision descends only when the dream learns to keep time.',
  },
};
