import type { ZodiacSign } from './types';

export interface NodeAxisMeaning {
  southSign: ZodiacSign;
  northSign: ZodiacSign;
  oldSuperpower: string;
  comfortTrap: string;
  shadowMisuse: string;
  purposeDoor: string;
  purposeDemand: string;
  emotionalWound: string;
  coreGift: string;
  mainFear: string;
  mainTemptation: string;
  relationshipPattern: string;
  careerPattern: string;
  missionStyle: string;
  settings: string[];
  archetypes: string[];
  comfortVerbs: string[];
  shadowVerbs: string[];
  purposeVerbs: string[];
  scar: string;
  scarGift: string;
  relicName: string;
  relicMemory: string;
  prophecy: string;
}

export const NODE_AXIS_MEANINGS: Record<ZodiacSign, NodeAxisMeaning> = {
  Aries: {
    southSign: 'Aries',
    northSign: 'Libra',
    oldSuperpower: 'You have survived by moving first, fighting alone, and becoming the blade before anyone could raise one against you.',
    comfortTrap: 'The soul reaches for speed, conquest, and solitude when tenderness asks for patience.',
    shadowMisuse: 'Courage becomes domination, desire becomes impatience, and every bond becomes a battlefield.',
    purposeDoor: 'The next life opens through alliance, listening, beauty, and the dangerous grace of choosing together.',
    purposeDemand: 'Let another soul matter without making them an enemy to defeat.',
    emotionalWound: 'Someone once taught you that needing help was the beginning of defeat.',
    coreGift: 'fearless ignition',
    mainFear: 'being slowed down by love',
    mainTemptation: 'winning quickly and standing alone afterward',
    relationshipPattern: 'you attract mirrors who ask whether victory is worth loneliness',
    careerPattern: 'warrior, pioneer, guard, athlete, champion, first responder',
    missionStyle: 'turn conflict into conscious partnership',
    settings: ['a border fortress', 'a rebel camp', 'a dueling academy', 'a gladiator arena beneath a dying empire', 'a warlord encampment on scorched earth', 'a forge where heroes temper blades with blood oaths', 'a tribal outpost beyond the last known map', 'a siege tower overlooking a city that refused to kneel'],
    archetypes: ['The Lone Blade', 'The First Fire', 'The Treaty Breaker', 'The Scar-Crowned Champion', 'The Blood Oath Keeper', 'The War Orphan Who Became the General', 'The Flame That Refuses the Altar', 'The Shield Turned Weapon'],
    comfortVerbs: ['strike first', 'walk out', 'claim the prize alone', 'refuse to negotiate', 'burn the bridge before crossing it', 'make the first wound count'],
    shadowVerbs: ['humiliate the rival', 'turn desire into conquest', 'make peace impossible', 'mistake rage for righteousness', 'destroy what cannot be dominated', 'declare war on tenderness'],
    purposeVerbs: ['ask for counsel', 'share the victory', 'choose the vow over the crown', 'hold the sword and still embrace', 'listen before striking', 'let the enemy become the ally'],
    scar: 'Fear of dependence',
    scarGift: 'brave interdependence',
    relicName: 'The Split Shield',
    relicMemory: 'You remember the day victory felt hollow because no one was left beside you.',
    prophecy: 'The sword lowers only when the hand beside yours stops feeling like a threat.',
  },
  Taurus: {
    southSign: 'Taurus',
    northSign: 'Scorpio',
    oldSuperpower: 'You know how to build, endure, preserve, and make the body safe when the world becomes unreliable.',
    comfortTrap: 'The soul clings to what can be touched, owned, eaten, saved, or controlled through habit.',
    shadowMisuse: 'Stability becomes possession, pleasure becomes numbness, and loyalty becomes refusal to transform.',
    purposeDoor: 'The next life opens through surrender, intimacy, truth, shared power, and the courage to enter the underworld cleanly.',
    purposeDemand: 'Stop mistaking stillness for safety when the soul is asking to shed its skin.',
    emotionalWound: 'A loss taught you that anything loved must be held tightly or buried before it can leave.',
    coreGift: 'embodied value mastery',
    mainFear: 'losing security, money, body, land, or love',
    mainTemptation: 'choosing comfort even when the old life is already dead',
    relationshipPattern: 'you return to bonds where trust requires shared vulnerability, not ownership',
    careerPattern: 'builder, farmer, singer, banker, artisan, land keeper',
    missionStyle: 'exchange possession for transformation',
    settings: ['a prosperous valley with buried secrets', 'a merchant city', 'a temple of gold and grief', 'a vineyard built on ancestral bones', 'a walled estate where nothing has changed for centuries', 'a treasury beneath a crumbling throne', 'a harvest village the night before the earthquake', 'a silk road caravansary hoarding forbidden spices'],
    archetypes: ['The Keeper of the Vault', 'The Garden Builder', 'The Body Oracle', 'The Hoarder of Beautiful Ruins', 'The Earth-Bound Sentinel', 'The Pleasure Alchemist Who Forgot Pain', 'The Orchard Widow', 'The Golden Chain Wearer'],
    comfortVerbs: ['hold the treasure', 'stay with the familiar', 'protect the body from every risk', 'store more than the soul can carry', 'repeat the comfort until it numbs', 'root so deeply that change becomes betrayal'],
    shadowVerbs: ['buy loyalty', 'refuse change', 'make love prove itself through possession', 'suffocate the beloved with safety', 'hoard beauty while the spirit starves', 'call stubbornness devotion'],
    purposeVerbs: ['enter the hidden room', 'share the burden', 'trust the death that makes life possible', 'release what has already left', 'let the earthquake remake the garden', 'surrender the key without knowing the door'],
    scar: 'Fear of loss',
    scarGift: 'deep trust and regenerative courage',
    relicName: 'The Buried Coin',
    relicMemory: 'You remember a field bought with silence, and the secret it could not keep buried.',
    prophecy: 'The treasure is not stolen. It is transformed when you finally open your hands.',
  },
  Gemini: {
    southSign: 'Gemini',
    northSign: 'Sagittarius',
    oldSuperpower: 'You have lived by listening fast, changing names, carrying messages, and escaping through cleverness.',
    comfortTrap: 'The soul gathers fragments, rumors, options, and exits instead of committing to the truth that burns.',
    shadowMisuse: 'Language becomes manipulation, knowledge becomes avoidance, and every road becomes a reason not to choose.',
    purposeDoor: 'The next life opens through meaning, faith, honest teaching, long journeys, and one truth spoken from the whole body.',
    purposeDemand: 'Trade the clever answer for the honest pilgrimage.',
    emotionalWound: 'You learned to stay safe by never letting anyone know which version of you was real.',
    coreGift: 'adaptive intelligence',
    mainFear: 'being trapped by one truth',
    mainTemptation: 'talking your way around the lesson',
    relationshipPattern: 'you meet souls who force words to become vows',
    careerPattern: 'messenger, translator, trader, scribe, spy, storyteller',
    missionStyle: 'turn scattered knowledge into lived wisdom',
    settings: ['a border market', 'a tower of forbidden maps', 'a road between warring kingdoms', 'a printing house where pamphlets topple thrones', 'a crossroads inn where every traveler lies', 'a library of stolen correspondence', 'a courier guild running messages through enemy lines', 'a bazaar of forged identities and second chances'],
    archetypes: ['The Silver Messenger', 'The Many-Named Scribe', 'The Road-Tongued Trickster', 'The Forger of Safe Passage', 'The Whisperer Between Courts', 'The Merchant of Half-Truths', 'The Rumor-Spinner Who Forgot Their Own Name', 'The Crossroads Orphan'],
    comfortVerbs: ['change the subject', 'trade the secret', 'keep every option alive', 'split the self into versions', 'charm the gatekeeper instead of facing the gate', 'collect information instead of meaning'],
    shadowVerbs: ['lie beautifully', 'sell both sides the same promise', 'turn truth into performance', 'betray with wit instead of malice', 'make loyalty a moving target', 'speak so fast the heart cannot object'],
    purposeVerbs: ['tell the whole truth', 'tell the truth on the road that has no shortcut', 'teach what cost you something', 'choose one name and stand behind it', 'burn the escape route for the sake of meaning', 'let silence carry what words once hid'],
    scar: 'Fear of commitment',
    scarGift: 'truth-speaking wisdom',
    relicName: 'The Sealed Letter',
    relicMemory: 'You remember the message you delivered but never dared to read aloud.',
    prophecy: 'The map becomes a door only after the messenger stops running.',
  },
  Cancer: {
    southSign: 'Cancer',
    northSign: 'Capricorn',
    oldSuperpower: 'You know how to protect, remember, feed, hide, and keep a family alive through storms.',
    comfortTrap: 'The soul retreats into the old house, the old ache, the old loyalty, and calls it love.',
    shadowMisuse: 'Care becomes control, memory becomes guilt, and tenderness becomes a chain around the future.',
    purposeDoor: 'The next life opens through structure, authority, self-respect, public mastery, and clean responsibility.',
    purposeDemand: 'Build the life your younger self needed instead of living forever inside the wound.',
    emotionalWound: 'The child inside this lifetime is still waiting at the door where someone once left and never came back.',
    coreGift: 'ancestral memory and protection',
    mainFear: 'abandonment',
    mainTemptation: 'keeping everyone close by staying needed',
    relationshipPattern: 'you meet souls who test whether care can exist without clinging',
    careerPattern: 'caretaker, innkeeper, family heir, midwife, protector, memory keeper',
    missionStyle: 'turn private pain into mature stewardship',
    settings: ['an ancestral coastal house', 'a village after famine', 'a royal nursery with locked doors', 'a flooded homestead where the family refuses to leave', 'a lighthouse tended by a grief-stricken widow', 'a kitchen where every meal is a memorial', 'a war-orphanage run by the eldest child', 'a burial island where the tides keep returning bones'],
    archetypes: ['The House Keeper', 'The Moon-Wounded Heir', 'The Protector of Names', 'The Mother Who Became the Fortress', 'The Tide-Bound Guardian', 'The Weeping Sentinel at the Threshold', 'The Memory Collector', 'The Cradle Builder in the Ruins'],
    comfortVerbs: ['return home', 'save everyone first', 'hide inside loyalty', 'feed the wound instead of healing it', 'make the family the whole world', 'remember the pain so no one else has to'],
    shadowVerbs: ['make guilt sound like love', 'punish anyone who leaves', 'refuse adulthood', 'weaponize tears', 'smother the beloved with worry', 'turn the home into a shrine no one may leave'],
    purposeVerbs: ['take authority', 'build a boundary', 'become the shelter without becoming the cage', 'lead the family forward instead of backward', 'let the children outgrow the nest', 'honor the ancestor without repeating them'],
    scar: 'Fear of abandonment',
    scarGift: 'emotional independence',
    relicName: 'The Childs Toy',
    relicMemory: 'You remember a small hand waiting for a promise that never came back.',
    prophecy: 'The house stops haunting you when you become its foundation, not its prisoner.',
  },
  Leo: {
    southSign: 'Leo',
    northSign: 'Aquarius',
    oldSuperpower: 'You have known radiance, performance, command, romance, and the sacred heat of being witnessed.',
    comfortTrap: 'The soul reaches for applause, specialness, courtly drama, and the throne it already knows how to hold.',
    shadowMisuse: 'Light becomes vanity, leadership becomes spectacle, and love becomes proof that the soul still matters.',
    purposeDoor: 'The next life opens through friendship, community, systems, future vision, and service to something larger than personal glory.',
    purposeDemand: 'Let the gift belong to the circle without making your heart disappear.',
    emotionalWound: 'A lifetime taught you that being unseen felt like being erased.',
    coreGift: 'creative radiance',
    mainFear: 'being ordinary or forgotten',
    mainTemptation: 'choosing drama because it feels like proof of life',
    relationshipPattern: 'you meet souls who ask whether love is still real when nobody is applauding',
    careerPattern: 'performer, sovereign, artist, royal child, champion, patron',
    missionStyle: 'turn personal shine into collective liberation',
    settings: ['a royal theater', 'a palace before a revolution', 'a city of inventors who distrust kings', 'a colosseum where artists compete for the emperors favor', 'a court of mirrors where every reflection lies', 'a festival city the night the dynasty falls', 'a sun temple where only one priest may sing', 'a guildhall of painters fighting over a single commission'],
    archetypes: ['The Fallen Star', 'The Golden Child', 'The Heart Sovereign', 'The Uncrowned Performer', 'The Muse Who Consumed the Artist', 'The Sun-Orphan Seeking Witnesses', 'The Beloved Tyrant', 'The Stage-Haunting Ghost'],
    comfortVerbs: ['take center stage', 'make the wound theatrical', 'demand proof of devotion', 'turn every room into a performance', 'measure love by the size of the audience', 'shine so brightly that no one else is visible'],
    shadowVerbs: ['steal the circle light', 'turn love into worship', 'banish the rival performer', 'confuse applause with intimacy', 'punish the one who looked away', 'make every story about the self'],
    purposeVerbs: ['share the stage', 'protect the strange ones', 'lead without needing a throne', 'celebrate someone else without dimming', 'let the art belong to the people', 'shine for the circle instead of over it'],
    scar: 'Fear of being unseen',
    scarGift: 'heart-led leadership',
    relicName: 'The Broken Crown',
    relicMemory: 'You remember the crown cracking in your hands while the people outside kept singing.',
    prophecy: 'The star becomes a constellation only when it stops fearing the other lights.',
  },
  Virgo: {
    southSign: 'Virgo',
    northSign: 'Pisces',
    oldSuperpower: 'You have mastered craft, medicine, discipline, diagnosis, service, and the sacred repair of broken systems.',
    comfortTrap: 'The soul tries to earn safety by being useful, flawless, prepared, and impossible to criticize.',
    shadowMisuse: 'Discernment becomes judgment, service becomes martyrdom, and skill becomes a wall against grace.',
    purposeDoor: 'The next life opens through surrender, mercy, imagination, mystery, forgiveness, and trust in the unseen.',
    purposeDemand: 'Let the ritual be holy without needing every thread under control.',
    emotionalWound: 'You were loved for what you fixed, then forgot you were allowed to be held when you could fix nothing.',
    coreGift: 'sacred precision',
    mainFear: 'being useless, messy, or wrong',
    mainTemptation: 'perfecting the cage instead of leaving it',
    relationshipPattern: 'you meet souls who cannot be repaired, only loved',
    careerPattern: 'healer, apprentice, archivist, ritual keeper, midwife, analyst',
    missionStyle: 'turn control into compassion',
    settings: ['a plague infirmary', 'a monastery workshop', 'a flooded archive of prayers', 'an apothecary where every cure demands a confession', 'a scriptorium copying sacred texts by dying candlelight', 'a war hospital sorting the saveable from the lost', 'a grain storehouse during a season of false prophets', 'a temple garden where every herb has a moral name'],
    archetypes: ['The Sacred Healer', 'The Needle Keeper', 'The Perfect Servant', 'The Fault-Finding Saint', 'The Apprentice Who Outlived the Master', 'The Sorter of the Worthy', 'The Wound Counter', 'The Ritual Perfectionist'],
    comfortVerbs: ['correct the flaw', 'work until collapse', 'make a plan for the unknowable', 'organize the chaos instead of feeling it', 'earn rest through exhaustion', 'diagnose instead of embrace'],
    shadowVerbs: ['shame the wounded', 'withhold help until it is earned', 'turn purity into punishment', 'confuse criticism with care', 'refuse grace because it was not scheduled', 'make the body a machine for proving worth'],
    purposeVerbs: ['forgive the unfinished', 'follow the dream', 'offer mercy before certainty', 'let the prayer be imperfect', 'trust the river instead of the blueprint', 'heal without needing to understand why'],
    scar: 'Fear of imperfection',
    scarGift: 'healing mercy',
    relicName: 'The Healers Bowl',
    relicMemory: 'You remember washing blood from your hands and still feeling unclean.',
    prophecy: 'The wound closes when the healer lets the water touch them too.',
  },
  Libra: {
    southSign: 'Libra',
    northSign: 'Aries',
    oldSuperpower: 'You know charm, treaty, elegance, listening, alliance, and the art of surviving through relationship.',
    comfortTrap: 'The soul waits for permission, reads the room, softens the truth, and calls self-erasure peace.',
    shadowMisuse: 'Harmony becomes manipulation, beauty becomes leverage, and love becomes a mirror with no self behind it.',
    purposeDoor: 'The next life opens through direct desire, courage, clean anger, self-claiming, and the first honest move.',
    purposeDemand: 'Choose yourself without turning love into a trial.',
    emotionalWound: 'A vow once taught you that being chosen mattered more than being true.',
    coreGift: 'relational intelligence',
    mainFear: 'losing love by wanting something',
    mainTemptation: 'keeping peace by betraying the self',
    relationshipPattern: 'you keep meeting the same soul in different faces because the vow was never completed',
    careerPattern: 'diplomat, artist, spouse, negotiator, court adviser, matchmaker',
    missionStyle: 'turn pleasing into courageous choice',
    settings: ['a marriage court', 'a diplomatic city', 'a ballroom before a duel', 'a peace summit where every delegate has a secret blade', 'a portrait gallery of forgotten spouses', 'a salon where compliments are currency', 'a garden wedding held to prevent a war', 'a courthouse where justice bends toward beauty'],
    archetypes: ['The Unchosen Bride', 'The Silver Diplomat', 'The Mirror-Bound Lover', 'The Peacekeeper Who Lost Their Own War', 'The Ornamental Spouse', 'The Agreement Maker Who Never Agreed', 'The Smiling Prisoner', 'The Vow-Polished Ghost'],
    comfortVerbs: ['make everyone comfortable', 'wait to be chosen', 'hide the anger', 'smile through the betrayal', 'adjust the self to fit the room', 'let someone else decide so the blame never lands'],
    shadowVerbs: ['seduce the decision', 'betray privately to preserve beauty', 'make love a negotiation', 'erase the self and call it grace', 'punish through withdrawal instead of words', 'trade honesty for harmony'],
    purposeVerbs: ['speak first', 'leave the room cleanly', 'fight for the life with your name on it', 'say no without apology', 'choose the self even when it costs the peace', 'let the anger become a compass'],
    scar: 'Fear of rejection',
    scarGift: 'self-honoring courage',
    relicName: 'The Lovers Ring',
    relicMemory: 'You remember a ring that fit perfectly and still felt like a locked door.',
    prophecy: 'The vow heals when the soul stops asking love to choose in its place.',
  },
  Scorpio: {
    southSign: 'Scorpio',
    northSign: 'Taurus',
    oldSuperpower: 'You have survived darkness through instinct, strategy, passion, secrecy, and emotional x-ray vision.',
    comfortTrap: 'The soul returns to crisis, control, suspicion, revenge, and the old feeling that danger is home.',
    shadowMisuse: 'Depth becomes obsession, protection becomes manipulation, and love becomes a war for power.',
    purposeDoor: 'The next life opens through peace, self-worth, body wisdom, simplicity, money mastery, beauty, and calm power.',
    purposeDemand: 'Stop needing chaos to feel alive, and build something that does not require a wound to keep it burning.',
    emotionalWound: 'A betrayal trained your nervous system to call peace suspicious.',
    coreGift: 'survival intelligence',
    mainFear: 'trusting what cannot be controlled',
    mainTemptation: 'entering the underworld again just to feel powerful',
    relationshipPattern: 'you attract souls who test whether intimacy can exist without control',
    careerPattern: 'detective, occultist, strategist, healer, survivor, keeper of secrets',
    missionStyle: 'turn crisis power into embodied peace',
    settings: ['an ancient coastal village with forbidden rites', 'a palace of spies', 'a valley hiding a family curse', 'a crypt beneath a cathedral where the dead still whisper', 'a poisoners guild disguised as a perfumery', 'a blood-oath tribunal hidden inside a mountain', 'a haunted estate where every mirror shows a different past', 'a night market where debts are paid in secrets'],
    archetypes: ['The Underworld Survivor', 'The Secret Keeper', 'The Storm-Blood Healer', 'The Venom Alchemist', 'The Oath-Bound Avenger', 'The Shadow Surgeon', 'The Betrayal Cartographer', 'The Grief-Forged Seer'],
    comfortVerbs: ['investigate the betrayal', 'control the lover', 'destroy the threat first', 'test loyalty with traps', 'guard the wound like a weapon', 'refuse peace because it feels naive'],
    shadowVerbs: ['use fear as currency', 'make obsession look like devotion', 'win through hidden influence', 'mistake jealousy for intuition', 'make the beloved prove themselves endlessly', 'turn intimacy into surveillance'],
    purposeVerbs: ['plant the seed', 'trust the slow vow', 'choose the body over the battle', 'let pleasure arrive without suspicion', 'build something that does not require crisis', 'accept the gift without scanning for poison'],
    scar: 'Fear of betrayal',
    scarGift: 'discernment and peaceful power',
    relicName: 'The Mystics Mirror',
    relicMemory: 'You remember seeing the truth in everyone except the part of you that wanted rest.',
    prophecy: 'The door opens only after you refuse the old crown of crisis.',
  },
  Sagittarius: {
    southSign: 'Sagittarius',
    northSign: 'Gemini',
    oldSuperpower: 'You have lived as a prophet, traveler, outlaw, teacher, and keeper of the far horizon.',
    comfortTrap: 'The soul escapes through certainty, distance, doctrine, humor, or the next road out.',
    shadowMisuse: 'Truth becomes arrogance, freedom becomes abandonment, and belief becomes a weapon.',
    purposeDoor: 'The next life opens through listening, questions, local bonds, nuance, and the humility to learn from the small road.',
    purposeDemand: 'Let curiosity interrupt certainty before the soul mistakes escape for wisdom.',
    emotionalWound: 'You were once punished for staying, so the horizon began to feel safer than home.',
    coreGift: 'visionary faith',
    mainFear: 'being trapped in a small life',
    mainTemptation: 'leaving before the lesson becomes intimate',
    relationshipPattern: 'you meet souls who ask you to stay long enough to hear them',
    careerPattern: 'pilgrim, judge, teacher, explorer, preacher, storyteller',
    missionStyle: 'turn certainty into living dialogue',
    settings: ['a desert pilgrimage road', 'a foreign court', 'a school built on disputed doctrine', 'a missionary outpost at the edge of the known world', 'a nomad camp debating the meaning of a comet', 'a trial of a philosopher accused of corrupting the youth', 'a burning library whose keepers argue over which books to save', 'a mountain pass where exiled prophets gather'],
    archetypes: ['The Wandering Oracle', 'The Laughing Exile', 'The Heretic Teacher', 'The Arrow-Tongued Preacher', 'The Horizon Addict', 'The Prophet Who Outran the Prophecy', 'The Pilgrim Without a Shrine', 'The Truth-Drunk Vagabond'],
    comfortVerbs: ['ride away', 'preach the answer', 'mock the small concern', 'mistake movement for progress', 'convert instead of connect', 'lecture the grieving instead of sitting with them'],
    shadowVerbs: ['use truth to wound', 'abandon the dependent', 'turn faith into law', 'crush doubt with doctrine', 'leave before the love gets ordinary', 'make the student feel small for asking'],
    purposeVerbs: ['ask the next question', 'listen to the nearby voice', 'stay for the unfinished conversation', 'learn from the one who never traveled', 'trade the sermon for a question', 'let the neighbor teach the pilgrim'],
    scar: 'Fear of confinement',
    scarGift: 'humble wisdom',
    relicName: 'The Exiles Map',
    relicMemory: 'You remember every road out and the one face you never returned to.',
    prophecy: 'The horizon kneels inside the question you almost refused to ask.',
  },
  Capricorn: {
    southSign: 'Capricorn',
    northSign: 'Cancer',
    oldSuperpower: 'You know duty, ambition, strategy, restraint, authority, and how to survive winter with no witness.',
    comfortTrap: 'The soul hardens, performs, climbs, controls, and calls loneliness maturity.',
    shadowMisuse: 'Mastery becomes coldness, authority becomes punishment, and success becomes a fortress without a hearth.',
    purposeDoor: 'The next life opens through tenderness, family repair, emotional honesty, rest, home, and the courage to need.',
    purposeDemand: 'Let the heart become a place of authority too.',
    emotionalWound: 'You were made responsible before you were allowed to be young.',
    coreGift: 'long-game mastery',
    mainFear: 'softness making you unsafe',
    mainTemptation: 'choosing the title over the person waiting at home',
    relationshipPattern: 'you meet souls who ask whether duty can include warmth',
    careerPattern: 'ruler, builder, elder, general, judge, mountain guide',
    missionStyle: 'turn achievement into emotional guardianship',
    settings: ['a snowbound court', 'a mountain citadel', 'a city built on debt and discipline', 'a frozen quarry where children mine for the crown', 'a council chamber where no one has laughed in decades', 'a fortress monastery that trains rulers through silence', 'a toll bridge kingdom that taxes grief', 'a dynasty hall lined with portraits of those who died working'],
    archetypes: ['The Winter Sovereign', 'The Burdened Heir', 'The Stone-Bound Master', 'The Frozen Patriarch', 'The Duty-Scarred Elder', 'The Child Crowned Too Young', 'The Mountain That Forgot the Valley', 'The Architect of Lonely Empires'],
    comfortVerbs: ['carry it alone', 'choose duty over feeling', 'make a law for the wound', 'endure instead of ask for help', 'build walls and call them wisdom', 'turn the heart to stone and call it strength'],
    shadowVerbs: ['punish weakness', 'trade love for rank', 'make fear sound responsible', 'starve the heart to feed the legacy', 'deny the child inside for the sake of the title', 'mistake coldness for composure'],
    purposeVerbs: ['return home', 'cry without bargaining', 'protect tenderness as seriously as power', 'let the child inside speak at the table', 'rest before the body demands it', 'build a home that is not a monument'],
    scar: 'Fear of vulnerability',
    scarGift: 'nurturing authority',
    relicName: 'The Judges Seal',
    relicMemory: 'You remember stamping the sentence and feeling the child inside you go silent.',
    prophecy: 'The mountain bows when the ruler learns the language of the hearth.',
  },
  Aquarius: {
    southSign: 'Aquarius',
    northSign: 'Leo',
    oldSuperpower: 'You have survived as the outsider, inventor, observer, rebel, and future signal inside a frightened world.',
    comfortTrap: 'The soul detaches, analyzes, leaves the body of the heart, and calls exile freedom.',
    shadowMisuse: 'Genius becomes contempt, rebellion becomes rupture, and cool distance becomes punishment.',
    purposeDoor: 'The next life opens through warmth, art, play, loyal love, creative risk, and being personally seen.',
    purposeDemand: 'Let the strange future have a human heartbeat.',
    emotionalWound: 'A village once made you safer outside the circle than inside your own heart.',
    coreGift: 'liberating vision',
    mainFear: 'being swallowed by ordinary emotion',
    mainTemptation: 'staying untouchable so rejection cannot land',
    relationshipPattern: 'you meet souls who ask you to stop saving humanity while avoiding one heart',
    careerPattern: 'inventor, rebel, astrologer, scientist, reformer, exile',
    missionStyle: 'turn detachment into radiant participation',
    settings: ['an observatory under persecution', 'a city before revolution', 'a workshop of forbidden machines', 'a commune that exiled its founder', 'an underground network of outlawed thinkers', 'a radio tower broadcasting to a world that stopped listening', 'a laboratory hidden beneath a collapsing republic', 'a council of outcasts planning a world they may never see'],
    archetypes: ['The Star Exile', 'The Future Thief', 'The Lightning Friend', 'The Frequency Nobody Could Hear', 'The Cold Architect of Utopia', 'The Rebel Who Forgot to Come Home', 'The Wire-Hearted Visionary', 'The Exile Who Built a Country for Strangers'],
    comfortVerbs: ['leave the circle', 'explain the feeling away', 'choose theory over touch', 'observe the heart from a safe distance', 'fix the system instead of the relationship', 'prefer the idea of people to actual people'],
    shadowVerbs: ['make the group pay for misunderstanding you', 'burn the system without sheltering people', 'use distance as cruelty', 'call indifference objectivity', 'intellectualize the wound until it disappears', 'abandon the personal in service to the abstract'],
    purposeVerbs: ['step into the light', 'make the art personal', 'love one soul where all can see', 'let the heart be as radical as the mind', 'stay warm in a room you could easily leave', 'risk being ordinary for the sake of being real'],
    scar: 'Fear of belonging',
    scarGift: 'original heart leadership',
    relicName: 'The Rebels Torch',
    relicMemory: 'You remember a crowd chanting your idea while no one knew your name.',
    prophecy: 'The future trusts you after the heart stops hiding behind the signal.',
  },
  Pisces: {
    southSign: 'Pisces',
    northSign: 'Virgo',
    oldSuperpower: 'You have crossed dreams, temples, oceans, grief, music, and invisible worlds without losing the thread of compassion.',
    comfortTrap: 'The soul dissolves, rescues, sacrifices, escapes, and waits for the universe to choose the shape.',
    shadowMisuse: 'Mysticism becomes avoidance, mercy becomes self-erasure, and longing becomes addiction to the unreachable.',
    purposeDoor: 'The next life opens through craft, boundaries, health, practical service, timing, and the holy precision of daily work.',
    purposeDemand: 'Give the dream a body, a schedule, and hands that finish the medicine.',
    emotionalWound: 'You once became everything for everyone until no one knew where you had gone.',
    coreGift: 'mystical compassion',
    mainFear: 'hard edges, ordinary limits, and disappointing the suffering',
    mainTemptation: 'disappearing into the dream instead of building the altar',
    relationshipPattern: 'you meet souls who test whether rescue is love or avoidance',
    careerPattern: 'mystic, singer, healer, poet, monk, dream interpreter',
    missionStyle: 'turn spiritual longing into embodied service',
    settings: ['a sea temple', 'a monastery at the edge of fog', 'a hospital where dreams speak', 'a flooded cathedral where the choir still sings', 'a lighthouse kept by a blind oracle', 'a shipwreck village where the survivors forgot their names', 'a dream market where memories are traded for sleep', 'a tidal cave where prayers wash in with the dead'],
    archetypes: ['The Dream-Touched Healer', 'The Lost Saint', 'The Veiled Singer', 'The Drowned Messenger', 'The Compassion Addict', 'The Nameless Monk Who Carried Everyone', 'The Tide-Walker Between Worlds', 'The Martyr Who Mistook Suffering for Holiness'],
    comfortVerbs: ['forgive without boundary', 'escape into vision', 'sacrifice the self again', 'dissolve instead of decide', 'let the dream replace the day', 'love everyone so no one can ask for specifics'],
    shadowVerbs: ['use helplessness as a spell', 'make confusion holy', 'drown the vow in longing', 'turn suffering into identity', 'vanish when the world needs hands instead of prayers', 'call avoidance surrender'],
    purposeVerbs: ['name the boundary', 'practice the craft', 'serve one real body at a time', 'let the dream walk on solid ground', 'choose the task over the trance', 'finish the medicine instead of praying for a miracle'],
    scar: 'Fear of boundaries',
    scarGift: 'embodied devotion',
    relicName: 'The Priestess Veil',
    relicMemory: 'You remember the veil that made everyone call you holy while nobody asked if you were tired.',
    prophecy: 'The vision descends only when the dream learns to keep time.',
  },
};
