/**
 * Galactic Clock: 144 Hour Lord + Minute Lord Interpretations
 *
 * 12 Hour Lords x 12 Minute Lords = 144 unique combinations.
 * Hour Lord = dominant climate/force of the moment.
 * Minute Lord = how that force is currently expressing itself.
 */

export interface HourMinuteInterpretation {
  title: string;
  summary: string;
  focus: string;
  caution: string;
  tags: string[];
  energyScore: number;      // 1-10
  stabilityScore: number;   // 1-10
  spiritualScore: number;   // 1-10
}

interface RulerMeaning {
  keywords: string;
  essence: string;
}

const RULER_MEANINGS: Record<string, RulerMeaning> = {
  Mars: { keywords: 'action, force, courage, drive, confrontation, initiation', essence: 'decisive action and courageous drive' },
  Venus: { keywords: 'attraction, beauty, pleasure, harmony, value, affection', essence: 'magnetic attraction and harmonious beauty' },
  Mercury: { keywords: 'thought, speech, trade, learning, analysis, movement', essence: 'swift thought and clear communication' },
  Moon: { keywords: 'emotion, intuition, nurture, receptivity, reflection, memory', essence: 'emotional depth and intuitive receptivity' },
  Sun: { keywords: 'visibility, leadership, vitality, creativity, confidence, purpose', essence: 'radiant vitality and confident purpose' },
  Vesta: { keywords: 'devotion, concentration, sacred work, discipline, purity, precision', essence: 'focused devotion and sacred discipline' },
  Juno: { keywords: 'partnership, commitment, fairness, union, agreements, loyalty', essence: 'committed partnership and balanced union' },
  Pluto: { keywords: 'depth, power, exposure, transformation, elimination, rebirth', essence: 'transformative power and deep renewal' },
  Jupiter: { keywords: 'growth, wisdom, teaching, opportunity, blessings, expansion', essence: 'expansive wisdom and abundant opportunity' },
  Saturn: { keywords: 'structure, restraint, effort, maturity, responsibility, endurance', essence: 'disciplined structure and mature endurance' },
  Uranus: { keywords: 'innovation, disruption, awakening, freedom, shock, originality', essence: 'radical innovation and liberating awakening' },
  Neptune: { keywords: 'spirituality, dreams, surrender, imagination, compassion, mysticism', essence: 'mystical surrender and spiritual imagination' },
};

export const GALACTIC_HOUR_MINUTE_INTERPRETATIONS: Record<string, Record<string, HourMinuteInterpretation>> = {

  // ─────────────────────────────────────────────
  // MARS HOUR
  // ─────────────────────────────────────────────
  Mars: {
    Mars: {
      title: 'Pure Momentum',
      summary: 'This is a time of raw, undiluted action. Every instinct pushes forward. Momentum is at its peak — whatever you initiate now carries the full force of your will behind it. Nothing is subtle here; this is direct, unapologetic, and powerful.',
      focus: 'Act decisively on what matters most — hesitation costs more than action.',
      caution: 'Avoid impulsive aggression or burning bridges you may need later.',
      tags: ['Action', 'Initiative', 'Courage'],
      energyScore: 10,
      stabilityScore: 3,
      spiritualScore: 2,
    },
    Venus: {
      title: 'Assertive Attraction',
      summary: 'Desire meets drive. This moment blends pursuit with magnetism — you are both reaching for what you want and drawing it toward you. It favors bold moves in love, beauty, and money. There is charm inside the courage.',
      focus: 'Pursue what you desire with confidence and grace.',
      caution: 'Do not confuse intensity with depth — attraction is not yet commitment.',
      tags: ['Desire', 'Love', 'Money'],
      energyScore: 8,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Mercury: {
      title: 'Sharp Strategy',
      summary: 'The mind is fast and the tongue is sharp. This is a time for decisive communication, rapid analysis, and strategic debate. Words carry the force of action — what you say now has impact.',
      focus: 'Speak with precision and move quickly on important decisions.',
      caution: 'Watch for verbal aggression or saying something you cannot take back.',
      tags: ['Strategy', 'Communication', 'Speed'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 2,
    },
    Moon: {
      title: 'Emotional Charge',
      summary: 'Feeling fuels force. Emotions are running hot and instincts are sharp. This moment favors protective action — defending what you care about, responding to what matters viscerally, and trusting your gut.',
      focus: 'Channel emotional intensity into purposeful action.',
      caution: 'The trap here is reactive outbursts or letting hurt feelings drive reckless choices.',
      tags: ['Protection', 'Instinct', 'Emotion'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 4,
    },
    Sun: {
      title: 'Bold Leadership',
      summary: 'Confidence and courage merge into visible, commanding energy. This is a time to step forward, take charge, and be seen. Your presence carries authority and your actions speak louder than words.',
      focus: 'Lead from the front — this moment rewards visible, decisive action.',
      caution: 'Steer clear of dominating others or letting ego override wisdom.',
      tags: ['Leadership', 'Confidence', 'Visibility'],
      energyScore: 9,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Vesta: {
      title: 'Sacred Drive',
      summary: 'Effort becomes devotion. This is a time for disciplined, focused action — not scattered energy, but concentrated force applied to what truly matters. Work done now has a ritual quality to it.',
      focus: 'Pour your energy into your most important task with total concentration.',
      caution: 'Be wary of burning out through relentless effort without rest.',
      tags: ['Discipline', 'Deep Work', 'Focus'],
      energyScore: 8,
      stabilityScore: 7,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Active Partnership',
      summary: 'Relationships require direct engagement now. This moment favors honest negotiation, defending a bond, or actively building an alliance. It is not a time for passivity in partnership.',
      focus: 'Show up fully in your most important relationships and agreements.',
      caution: 'The risk: turning partnership into a battlefield.',
      tags: ['Partnership', 'Negotiation', 'Commitment'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Pluto: {
      title: 'Power Surge',
      summary: 'Intense, transformative force is moving through the hour. Confrontation with truth, power, and the hidden becomes the weather. What you face now has the leverage to fundamentally shift something that has been stuck.',
      focus: 'Face what needs to be confronted — power is available for transformation.',
      caution: 'Careful — power struggles that serve ego rather than truth.',
      tags: ['Transformation', 'Power', 'Intensity'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Bold Expansion',
      summary: 'Courage meets opportunity. This moment carries expansive, optimistic force — it favors taking risks, stepping into something bigger, and trusting that the leap will be rewarded. Fortune favors the brave.',
      focus: 'Take a calculated risk that aligns with your larger vision.',
      caution: 'The shadow side is overconfidence or biting off more than you can chew.',
      tags: ['Expansion', 'Risk', 'Opportunity'],
      energyScore: 9,
      stabilityScore: 4,
      spiritualScore: 4,
    },
    Saturn: {
      title: 'Controlled Force',
      summary: 'Discipline channels raw power. This moment demands effort with precision — not wild action, but steady, strategic push. Endurance matters more than speed. Build something that can withstand pressure.',
      focus: 'Apply sustained effort to your most demanding challenge.',
      caution: 'Keep an eye on frustration when progress feels slower than your ambition.',
      tags: ['Endurance', 'Strategy', 'Discipline'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Electric Breakthrough',
      summary: 'Expect the unexpected. This moment crackles with disruptive energy — sudden moves, radical shifts, and the courage to break from convention. It favors innovation, rebellion, and lightning-fast change.',
      focus: 'Act on the unconventional insight that just arrived.',
      caution: 'Avoid reckless disruption or change for its own sake.',
      tags: ['Breakthrough', 'Innovation', 'Disruption'],
      energyScore: 9,
      stabilityScore: 2,
      spiritualScore: 4,
    },
    Neptune: {
      title: 'Inspired Force',
      summary: 'Action meets the invisible. This moment blends drive with spiritual sensitivity — it can produce inspired effort or confused direction. The key is to act from intuition, not ego. Sacrifice may be part of the equation.',
      focus: 'Let inner guidance direct your outer actions.',
      caution: 'Watch for acting on unclear motives or fighting battles that are not yours.',
      tags: ['Inspiration', 'Surrender', 'Spiritual Action'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 7,
    },
  },

  // ─────────────────────────────────────────────
  // VENUS HOUR
  // ─────────────────────────────────────────────
  Venus: {
    Mars: {
      title: 'Passionate Magnetism',
      summary: 'Attraction becomes pursuit. This is a moment where what you love compels you to move — desire is not passive here, it is alive and reaching. Bold romantic gestures, direct financial moves, and magnetic pursuit are all favored.',
      focus: 'Go after what your heart wants with unapologetic directness.',
      caution: 'The trap here is confusing passion with possession — let desire breathe.',
      tags: ['Desire', 'Love', 'Passion'],
      energyScore: 8,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Venus: {
      title: 'Pure Harmony',
      summary: 'Beauty, love, and pleasure are fully available. This is a time of deep receptivity — the senses are heightened, connections feel rich, and the world seems softer. Allow yourself to receive without guilt or analysis.',
      focus: 'Open yourself to beauty, comfort, and the pleasures that nourish you.',
      caution: 'Steer clear of indulgence that creates regret or avoidance disguised as enjoyment.',
      tags: ['Love', 'Beauty', 'Harmony'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Mercury: {
      title: 'Charming Words',
      summary: 'Language becomes art. This moment favors sweet diplomacy, social grace, and messages that charm rather than confront. Communication flows through beauty — writing, negotiation, and creative expression all carry an extra polish.',
      focus: 'Express yourself with elegance and let your words open doors.',
      caution: 'Be wary of flattery that masks insincerity or avoids necessary honesty.',
      tags: ['Communication', 'Art', 'Social'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Moon: {
      title: 'Tender Bond',
      summary: 'Emotional warmth fills the atmosphere. This is a time of gentle nurturing, soft affection, and quiet comfort. Relationships deepen through care rather than drama. The heart is open and the mood is trusting.',
      focus: 'Nurture the bonds that matter most with presence and gentleness.',
      caution: 'The risk: emotional dependency or clinging to comfort zones that limit growth.',
      tags: ['Nurturing', 'Love', 'Comfort'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Radiant Grace',
      summary: 'Charisma meets warmth. This moment lights up your natural magnetism — you are both attractive and confidently visible. Creative expression, romantic gestures, and public charm are all amplified. People notice you.',
      focus: 'Let your warmth and creativity shine without hesitation.',
      caution: 'Careful — performing for approval rather than expressing from authenticity.',
      tags: ['Creativity', 'Magnetism', 'Warmth'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 4,
    },
    Vesta: {
      title: 'Devoted Beauty',
      summary: 'Pleasure becomes practice. This is a time where beauty serves a higher purpose — art made with devotion, love expressed through careful attention, and value cultivated with precision. There is sacredness in what you cherish.',
      focus: 'Tend to what you love with the focus and care of a craftsperson.',
      caution: 'The shadow side is rigidity in matters of the heart — devotion should not become control.',
      tags: ['Devotion', 'Refinement', 'Sacred'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Union Harmony',
      summary: 'Partnership is at its most graceful. This moment favors commitment, mutual appreciation, and the beauty of a balanced bond. Whether romantic or professional, relationships benefit from shared values and open-hearted negotiation.',
      focus: 'Strengthen your most important partnership through genuine appreciation.',
      caution: 'Keep an eye on sacrificing your own needs to maintain a false harmony.',
      tags: ['Partnership', 'Commitment', 'Harmony'],
      energyScore: 5,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Pluto: {
      title: 'Magnetic Depth',
      summary: 'Attraction pulls you into deeper waters. The charm on offer reaches past surface and touches something primal. Relationships, values, and creative work all carry the potential for intense, meaningful shifts under this current.',
      focus: 'Allow yourself to be drawn toward what transforms you.',
      caution: 'Avoid obsessive attachment or mistaking intensity for love.',
      tags: ['Intensity', 'Attraction', 'Depth'],
      energyScore: 7,
      stabilityScore: 4,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Abundant Grace',
      summary: 'Generosity and beauty overflow. This moment is rich with blessings — open-hearted joy, fortunate encounters, and a sense that there is more than enough to go around. Love, money, and pleasure are all expanding.',
      focus: 'Receive the good that is flowing toward you and share it freely.',
      caution: 'Watch for excess that turns abundance into waste.',
      tags: ['Abundance', 'Joy', 'Blessings'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Mature Love',
      summary: 'Affection matures into loyalty. This moment favors lasting commitments over fleeting pleasures — stable partnerships, disciplined finances, and beauty that endures because it is built on substance. Trust what has proven itself.',
      focus: 'Invest in the relationships and values that stand the test of time.',
      caution: 'The trap here is coldness or withholding warmth in the name of practicality.',
      tags: ['Loyalty', 'Stability', 'Finance'],
      energyScore: 5,
      stabilityScore: 9,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Electric Chemistry',
      summary: 'Attraction sparks in unexpected places. This moment brings exciting, unconventional connections and sudden shifts in what you value. Love and creativity feel electric, unpredictable, and refreshingly free from convention.',
      focus: 'Welcome the surprising connection or creative impulse that appears.',
      caution: 'Steer clear of mistaking novelty for compatibility or abandoning stability for thrill.',
      tags: ['Excitement', 'Freedom', 'Chemistry'],
      energyScore: 8,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Neptune: {
      title: 'Dream Love',
      summary: 'Romance becomes transcendent. This moment dissolves the boundary between love and spirituality — connections feel destined, beauty feels otherworldly, and imagination saturates everything. The heart sees beyond what the eyes can measure.',
      focus: 'Let yourself dream, create, and love without needing to define it.',
      caution: 'Be wary of idealization that blinds you to reality or deception disguised as romance.',
      tags: ['Romance', 'Dreams', 'Spirituality'],
      energyScore: 5,
      stabilityScore: 4,
      spiritualScore: 8,
    },
  },

  // ─────────────────────────────────────────────
  // MERCURY HOUR
  // ─────────────────────────────────────────────
  Mercury: {
    Mars: {
      title: 'Cutting Edge',
      summary: 'Thoughts arrive like blades — sharp, fast, and decisive. This is a time for cutting through confusion, winning arguments, and making rapid decisions. The mind is a weapon, and it wants to be used.',
      focus: 'Strike while your thinking is clear — make the call you have been delaying.',
      caution: 'The risk: using words as weapons or making snap judgments you will regret.',
      tags: ['Speed', 'Debate', 'Decision'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 2,
    },
    Venus: {
      title: 'Eloquent Grace',
      summary: 'Language wears its finest clothes. This moment favors diplomatic speech, artistic writing, and conversations that build rapport rather than tear it down. Beauty enters through the mind — ideas feel elegant and communication flows smoothly.',
      focus: 'Use your words to create harmony, persuade gently, and express beauty.',
      caution: 'Careful — prioritizing style over substance or telling people only what they want to hear.',
      tags: ['Diplomacy', 'Art', 'Communication'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Mercury: {
      title: 'Pure Mind',
      summary: 'Mental clarity is at its peak. This is a time for analysis, writing, learning, and planning — the mind is both swift and precise. Information flows freely and connections between ideas appear effortlessly. This is your intellectual prime time.',
      focus: 'Tackle your most demanding mental work while clarity is at its highest.',
      caution: 'The shadow side is overthinking or mistaking analysis for action.',
      tags: ['Study', 'Analysis', 'Planning'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Moon: {
      title: 'Inner Dialogue',
      summary: 'Thought meets feeling. This is a time for emotional processing through words — journaling, reflective conversation, and listening to the quiet voice within. The mind is receptive, and intuition informs your reasoning.',
      focus: 'Write down what you are feeling — clarity comes through expression.',
      caution: 'Keep an eye on rationalizing emotions away or letting mood cloud your judgment.',
      tags: ['Reflection', 'Intuition', 'Writing'],
      energyScore: 5,
      stabilityScore: 5,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Confident Voice',
      summary: 'Your ideas carry weight and your voice commands attention. This moment favors presentations, publishing, and any communication that puts your thinking in the spotlight. Speak with authority — people are listening.',
      focus: 'Share your ideas boldly — this is a time to be heard.',
      caution: 'Avoid intellectual arrogance or dismissing perspectives that differ from yours.',
      tags: ['Expression', 'Clarity', 'Confidence'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Vesta: {
      title: 'Precision Mind',
      summary: 'Concentration sharpens to a fine point. This is a time for meticulous study, careful planning, and detailed analysis. The mind is not wandering — it is locked on its target with devotional precision.',
      focus: 'Apply your full mental focus to the most intricate problem before you.',
      caution: 'Watch for perfectionism that delays progress or obsessive detail at the expense of the bigger picture.',
      tags: ['Focus', 'Study', 'Precision'],
      energyScore: 6,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Juno: {
      title: 'Fair Exchange',
      summary: 'Communication serves partnership. This is a time for negotiation, contract review, mediation, and any dialogue where balance and fairness are essential. Words build bridges between people and seal meaningful agreements.',
      focus: 'Negotiate clearly and seek agreements that honor both sides.',
      caution: 'The trap here is over-compromising or using logic to manipulate a partner.',
      tags: ['Negotiation', 'Balance', 'Agreements'],
      energyScore: 6,
      stabilityScore: 7,
      spiritualScore: 3,
    },
    Pluto: {
      title: 'Deep Investigation',
      summary: 'The mind descends into hidden layers. This is a time for piercing analysis, psychological insight, and uncovering what has been concealed. Research, detective work, and therapeutic conversations are all powerfully supported.',
      focus: 'Look beneath the surface — the truth you seek is in the details others missed.',
      caution: 'Steer clear of paranoid thinking or using knowledge as a tool for manipulation.',
      tags: ['Investigation', 'Truth', 'Depth'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Expansive Learning',
      summary: 'The mind reaches outward. This is a time for big-picture thinking, teaching, publishing, and absorbing wisdom from diverse sources. Ideas feel expansive and the desire to share knowledge is strong.',
      focus: 'Teach what you know or study what expands your worldview.',
      caution: 'Be wary of intellectual overreach or preaching without listening.',
      tags: ['Teaching', 'Wisdom', 'Publishing'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Strategic Planning',
      summary: 'Thought becomes structure. This is a time for serious communication, long-term planning, and realistic assessment. The mind is sober, precise, and unwilling to entertain illusions. Build your strategy on facts.',
      focus: 'Plan with discipline and communicate only what is essential and true.',
      caution: 'The risk: pessimistic thinking or dismissing creative ideas as impractical.',
      tags: ['Strategy', 'Planning', 'Structure'],
      energyScore: 6,
      stabilityScore: 9,
      spiritualScore: 2,
    },
    Uranus: {
      title: 'Genius Download',
      summary: 'Brilliant ideas arrive without warning. This is a time of radical insight, unconventional solutions, and mental breakthroughs that rewrite the rules. The mind is electric — trust the flash of inspiration even if it defies logic.',
      focus: 'Capture the breakthrough idea before it disappears — write it down now.',
      caution: 'Careful — dismissing conventional wisdom entirely or confusing chaos with creativity.',
      tags: ['Innovation', 'Genius', 'Breakthrough'],
      energyScore: 8,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Neptune: {
      title: 'Poetic Mind',
      summary: 'Imagination saturates thought. This is a time for poetry, creative writing, spiritual messages, and insights that arrive through dreams rather than logic. The mind is open to the invisible — but clarity may require patience.',
      focus: 'Create from your imagination and trust the messages that arrive softly.',
      caution: 'The shadow side is confusion, deception, or making important decisions when thinking feels foggy.',
      tags: ['Poetry', 'Imagination', 'Vision'],
      energyScore: 5,
      stabilityScore: 3,
      spiritualScore: 8,
    },
  },

  // ─────────────────────────────────────────────
  // MOON HOUR
  // ─────────────────────────────────────────────
  Moon: {
    Mars: {
      title: 'Fierce Protection',
      summary: 'Emotion ignites into action. This is a time of protective instinct — a fierce, courageous response to anything that threatens what you love. The heart is not passive; it is ready to fight for what it cares about.',
      focus: 'Defend what matters to you with emotional conviction and decisive action.',
      caution: 'Keep an eye on reactive aggression driven by fear rather than genuine threat.',
      tags: ['Protection', 'Instinct', 'Courage'],
      energyScore: 7,
      stabilityScore: 4,
      spiritualScore: 4,
    },
    Venus: {
      title: 'Gentle Comfort',
      summary: 'Sweetness permeates the moment. This is a time of emotional harmony, quiet affection, and the simple pleasures that soothe the soul. Comfort food, soft music, and warm embraces are all medicine right now.',
      focus: 'Nourish yourself and others with tenderness and simple beauty.',
      caution: 'Avoid emotional eating, spending, or comfort-seeking that avoids deeper feelings.',
      tags: ['Comfort', 'Love', 'Softness'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Mercury: {
      title: 'Reflective Mind',
      summary: 'Feelings find words. This is a time for journaling, emotional processing through conversation, and reflective thought. The mind serves the heart — understanding comes from naming what you feel, not analyzing it away.',
      focus: 'Give language to your emotions — write, talk, or process what moves you.',
      caution: 'Watch for intellectualizing feelings to the point of disconnection.',
      tags: ['Reflection', 'Processing', 'Writing'],
      energyScore: 5,
      stabilityScore: 5,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Deep Feeling',
      summary: 'Sensitivity is at its fullest. This is a time of pure emotional immersion — intuition speaks clearly, inner life is vivid, and the boundary between self and world feels thin. Honor your feelings without judgment.',
      focus: 'Listen to your intuition and give yourself permission to simply feel.',
      caution: 'The trap here is absorbing others\' emotions or retreating too far into emotional isolation.',
      tags: ['Intuition', 'Rest', 'Sensitivity'],
      energyScore: 3,
      stabilityScore: 5,
      spiritualScore: 7,
    },
    Sun: {
      title: 'Heart Glow',
      summary: 'Emotional warmth radiates outward. This is a time where feelings become visible — heart-centered expression, nurturing leadership, and confident vulnerability. You can be both open and strong at the same time.',
      focus: 'Express what you feel with warmth and let your emotional truth shine.',
      caution: 'Steer clear of dramatic displays that seek attention rather than genuine connection.',
      tags: ['Heart', 'Warmth', 'Expression'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Vesta: {
      title: 'Sacred Retreat',
      summary: 'The inner flame burns quietly. This is a time for solitude, spiritual self-care, and focused emotional tending. Retreat from noise and tend to the sacred inner space that only you can access. Healing happens in stillness.',
      focus: 'Create a quiet space for emotional renewal and inner devotion.',
      caution: 'Be wary of withdrawing so deeply that you disconnect from those who need you.',
      tags: ['Retreat', 'Devotion', 'Care'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 8,
    },
    Juno: {
      title: 'Bonded Hearts',
      summary: 'Emotional loyalty deepens. This is a time where partnership is felt, not just agreed upon — closeness, shared vulnerability, and the quiet comfort of knowing you belong to someone. Bonds strengthen through presence.',
      focus: 'Show your loyalty through emotional availability and genuine closeness.',
      caution: 'The risk: codependency or expecting your partner to carry your emotional weight.',
      tags: ['Bonding', 'Loyalty', 'Closeness'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Pluto: {
      title: 'Emotional Depths',
      summary: 'Hidden feelings surface with force. This is a time of emotional catharsis — old wounds, buried memories, and unprocessed grief may demand attention. It is uncomfortable but deeply healing when met with courage.',
      focus: 'Allow what has been buried to rise — healing requires honesty with yourself.',
      caution: 'Careful — emotional manipulation or wallowing without moving toward resolution.',
      tags: ['Catharsis', 'Depth', 'Transformation'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 6,
    },
    Jupiter: {
      title: 'Hopeful Heart',
      summary: 'Optimism warms the emotional landscape. This is a time of healing hope, emotional generosity, and a sense that things will work out. Faith comes naturally and the desire to uplift others is strong.',
      focus: 'Let hope guide your feelings and share your warmth with those around you.',
      caution: 'The shadow side is spiritual bypassing or using positivity to avoid processing real pain.',
      tags: ['Hope', 'Healing', 'Generosity'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 6,
    },
    Saturn: {
      title: 'Steady Emotions',
      summary: 'Feelings meet containment. This is a time where emotional maturity is both required and rewarded — restraint is not suppression, it is the wisdom to hold space for difficult feelings without being overwhelmed by them.',
      focus: 'Practice emotional discipline — feel deeply, but respond with maturity.',
      caution: 'Keep an eye on emotional repression or mistaking numbness for strength.',
      tags: ['Maturity', 'Stability', 'Restraint'],
      energyScore: 4,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Uranus: {
      title: 'Emotional Awakening',
      summary: 'Mood shifts arrive without warning. This is a time of emotional surprise — sudden insights about how you feel, unexpected shifts in perspective, and the liberating realization that old emotional patterns can be broken.',
      focus: 'Welcome the emotional surprise that shakes loose something you have outgrown.',
      caution: 'Avoid mistaking instability for awakening or making emotional decisions impulsively.',
      tags: ['Awakening', 'Surprise', 'Insight'],
      energyScore: 6,
      stabilityScore: 2,
      spiritualScore: 5,
    },
    Neptune: {
      title: 'Psychic Flow',
      summary: 'The veil between worlds thins. This is a time of extraordinary psychic sensitivity, vivid dreams, and boundless empathy. The soul speaks in images, feelings, and whispers. Surrender to what cannot be explained.',
      focus: 'Trust your psychic impressions and allow yourself to dissolve into the mystery.',
      caution: 'Watch for losing yourself in others\' emotions or confusing fantasy with intuition.',
      tags: ['Psychic', 'Dreams', 'Surrender'],
      energyScore: 3,
      stabilityScore: 3,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // SUN HOUR
  // ─────────────────────────────────────────────
  Sun: {
    Mars: {
      title: 'Heroic Action',
      summary: 'This is the moment of the hero. Leadership meets action in a blaze of visible courage — you are called to step forward, take command, and move decisively. Your energy is contagious and your authority is earned through doing.',
      focus: 'Lead by example and take action that others will follow.',
      caution: 'The trap here is reckless bravado or seeking glory at the expense of others.',
      tags: ['Leadership', 'Courage', 'Action'],
      energyScore: 9,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Venus: {
      title: 'Radiant Charm',
      summary: 'You glow with magnetism. This is a time where creativity, warmth, and personal beauty are amplified — others are drawn to your light. Art, romance, and self-expression all benefit from this naturally charismatic energy.',
      focus: 'Create something beautiful and let your natural magnetism do its work.',
      caution: 'Steer clear of vanity or defining your worth solely through the admiration of others.',
      tags: ['Charm', 'Creativity', 'Beauty'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 4,
    },
    Mercury: {
      title: 'Brilliant Voice',
      summary: 'Intellect meets confidence. This is a time for authoritative communication — presentations, pitches, and conversations where your ideas need to land with impact. The mind is sharp and the delivery is commanding.',
      focus: 'Say what needs to be said with clarity and conviction.',
      caution: 'Be wary of intellectual showmanship or talking over others to prove a point.',
      tags: ['Expression', 'Clarity', 'Authority'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Moon: {
      title: 'Luminous Heart',
      summary: 'Emotional radiance fills the moment. This is a time where heart and visibility merge — your feelings are not hidden, they illuminate you. Nurturing others feels natural, and your warmth creates a sense of safety.',
      focus: 'Let your emotional openness be a source of light for those around you.',
      caution: 'The risk: emotional performance or exposing vulnerable feelings to untrustworthy audiences.',
      tags: ['Heart', 'Radiance', 'Nurturing'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Full Radiance',
      summary: 'Vitality is at its peak. This is a time of maximum visibility, creative authority, and unshakeable confidence. You are in the spotlight and the light is yours — recognition, self-expression, and personal power are all at their zenith.',
      focus: 'Step fully into who you are and let the world see it.',
      caution: 'Careful — arrogance or blinding yourself with your own light.',
      tags: ['Power', 'Recognition', 'Vitality'],
      energyScore: 9,
      stabilityScore: 6,
      spiritualScore: 4,
    },
    Vesta: {
      title: 'Sacred Purpose',
      summary: 'Visibility serves devotion. This is a time where your purpose becomes clear and your discipline makes you shine. Leadership is not about ego here — it is about serving something greater than yourself with focused dedication.',
      focus: 'Align your actions with your deepest purpose and let that alignment be visible.',
      caution: 'The shadow side is martyrdom or losing yourself in duty at the expense of joy.',
      tags: ['Purpose', 'Dedication', 'Leadership'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Partnership Light',
      summary: 'Commitment steps into the light. This is a time where partnerships are celebrated, visible, and balanced. Whether in business or love, the bond you share with another is a source of strength and mutual pride.',
      focus: 'Honor your partnerships publicly and lead through collaboration.',
      caution: 'Keep an eye on competing with your partner for the spotlight.',
      tags: ['Partnership', 'Balance', 'Leadership'],
      energyScore: 6,
      stabilityScore: 7,
      spiritualScore: 4,
    },
    Pluto: {
      title: 'Magnetic Truth',
      summary: 'Power and identity undergo a reckoning. This is a time where hidden truths emerge into the light — you may be confronted with your own shadow or forced to reveal something previously concealed. Authenticity is the only path forward.',
      focus: 'Embrace the truth about who you are, even the parts that are difficult to show.',
      caution: 'Avoid using personal power to control or intimidate others.',
      tags: ['Truth', 'Power', 'Magnetism'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Golden Blessing',
      summary: 'Success and expansion converge in a rare, generous blend. Confidence meets opportunity and the result is growth on several fronts at once — recognition, reward, and the feeling that the room is tilting in your favor.',
      focus: 'Say yes to the opportunity that has been building — this is its moment.',
      caution: 'Watch for hubris or assuming success will come without continued effort.',
      tags: ['Success', 'Blessing', 'Growth'],
      energyScore: 9,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Earned Authority',
      summary: 'Leadership meets responsibility. This is a time for mature, long-term vision — the authority you carry now is not borrowed, it is earned. Others trust you because you have done the work. Lead with seriousness and integrity.',
      focus: 'Accept the weight of leadership and use your authority to build something lasting.',
      caution: 'The trap here is rigidity or letting responsibility drain the joy from your accomplishments.',
      tags: ['Authority', 'Discipline', 'Mastery'],
      energyScore: 7,
      stabilityScore: 9,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Original Fire',
      summary: 'Self-expression becomes revolutionary. This is a time where your uniqueness demands to be seen — radical creativity, breakthrough visibility, and the courage to show the world something it has never seen before.',
      focus: 'Express the part of yourself that refuses to be conventional.',
      caution: 'Steer clear of rebellion without purpose or shocking people just for attention.',
      tags: ['Originality', 'Breakthrough', 'Rebellion'],
      energyScore: 8,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Neptune: {
      title: 'Inspired Glow',
      summary: 'Spiritual radiance softens your presence. This is a time where identity dissolves into something larger — creative vision, compassionate leadership, and a sense that you are a vessel for something beyond yourself.',
      focus: 'Let your creativity flow from a spiritual source and trust where it leads.',
      caution: 'Be wary of losing your sense of self or allowing others to project illusions onto you.',
      tags: ['Inspiration', 'Vision', 'Spirituality'],
      energyScore: 6,
      stabilityScore: 4,
      spiritualScore: 8,
    },
  },

  // ─────────────────────────────────────────────
  // VESTA HOUR
  // ─────────────────────────────────────────────
  Vesta: {
    Mars: {
      title: 'Disciplined Force',
      summary: 'Sacred work meets warrior energy. This is a time for purification through effort — hard, focused labor applied to what you are devoted to. The body is an instrument of the will, and every action is an offering.',
      focus: 'Attack your most important work with the intensity it deserves.',
      caution: 'The risk: forcing results or confusing exhaustion with accomplishment.',
      tags: ['Work', 'Discipline', 'Effort'],
      energyScore: 8,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Venus: {
      title: 'Sacred Beauty',
      summary: 'Devotion meets pleasure. This is a time where beauty is not frivolous — it is sacred. Careful attention to aesthetic detail, loving craftsmanship, and the refinement of anything you value are all richly supported.',
      focus: 'Create or tend to something beautiful with the reverence it deserves.',
      caution: 'Careful — being so devoted to perfection that you cannot enjoy what already exists.',
      tags: ['Beauty', 'Devotion', 'Refinement'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 6,
    },
    Mercury: {
      title: 'Focused Study',
      summary: 'The mind becomes a precision instrument. This is a time for concentrated study, careful documentation, and meticulous planning. Ritual writing, journaling with intention, and any mental work that requires sustained attention thrive now.',
      focus: 'Give your undivided attention to the study or plan that matters most.',
      caution: 'The shadow side is mental rigidity or getting lost in details without seeing the purpose.',
      tags: ['Study', 'Precision', 'Concentration'],
      energyScore: 6,
      stabilityScore: 8,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Inner Flame',
      summary: 'Devotion turns inward. This is a time for emotional purification — quietly tending to your inner life, releasing what no longer serves, and caring for your spirit with the same attention you would give a sacred flame.',
      focus: 'Tend to your emotional and spiritual well-being with quiet, devoted care.',
      caution: 'Keep an eye on emotional suppression in the name of discipline or duty.',
      tags: ['Purification', 'Care', 'Devotion'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 8,
    },
    Sun: {
      title: 'Dedicated Purpose',
      summary: 'Your purpose becomes visible. This is a time where focused effort meets public recognition — the work you have been devoted to earns its moment in the light. Leadership here is quiet, purposeful, and earned through consistent dedication.',
      focus: 'Let your disciplined work speak for itself and step into the recognition you have earned.',
      caution: 'Avoid seeking validation or abandoning your practice for applause.',
      tags: ['Purpose', 'Focus', 'Direction'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 6,
    },
    Vesta: {
      title: 'Total Devotion',
      summary: 'Pure concentration meets sacred ritual. This is a time of complete immersion in your practice — nothing exists outside the work. Discipline is not a burden; it is a doorway to mastery. Whatever you give yourself to fully will reward you.',
      focus: 'Immerse yourself completely in your most sacred task.',
      caution: 'Watch for isolating yourself so deeply that you lose connection with life outside the work.',
      tags: ['Ritual', 'Mastery', 'Discipline'],
      energyScore: 6,
      stabilityScore: 9,
      spiritualScore: 8,
    },
    Juno: {
      title: 'Sacred Commitment',
      summary: 'Loyalty becomes a spiritual practice. This is a time where commitment to a partner or cause is deepened through conscious effort and sacred intention. Agreements made now carry the weight of devotion behind them.',
      focus: 'Strengthen your commitments through intentional, devoted action.',
      caution: 'The trap here is blind loyalty that prevents you from seeing what needs to change.',
      tags: ['Commitment', 'Loyalty', 'Sacred'],
      energyScore: 5,
      stabilityScore: 8,
      spiritualScore: 6,
    },
    Pluto: {
      title: 'Deep Purification',
      summary: 'Shadow work becomes sacred practice. This is a time for intense, disciplined confrontation with what lies beneath — transformative focus applied to the darkest corners. The work is not easy, but it is profoundly purifying.',
      focus: 'Apply your discipline to the shadow that needs your attention most.',
      caution: 'Steer clear of obsessive self-examination that becomes self-punishment.',
      tags: ['Shadow Work', 'Purification', 'Depth'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 7,
    },
    Jupiter: {
      title: 'Devoted Growth',
      summary: 'Discipline serves expansion. This is a time where sacred study, devoted learning, and growth through focused effort create lasting wisdom. The teacher and the student are both honored in this moment.',
      focus: 'Expand your understanding through disciplined study and devoted practice.',
      caution: 'Be wary of rigid dogma or limiting your growth to a single path.',
      tags: ['Growth', 'Study', 'Expansion'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 7,
    },
    Saturn: {
      title: 'Austere Mastery',
      summary: 'The long road yields its reward. This is a time of maximum discipline and seriousness — there are no shortcuts, no distractions, and no excuses. What you build now is built to last, forged through patience and uncompromising effort.',
      focus: 'Commit to the hardest, most important thing, and do not stop until it is done.',
      caution: 'The risk: joylessness or mistaking severity for virtue.',
      tags: ['Mastery', 'Austerity', 'Endurance'],
      energyScore: 6,
      stabilityScore: 10,
      spiritualScore: 6,
    },
    Uranus: {
      title: 'Radical Focus',
      summary: 'Convention shatters in the monastery. This is a time where discipline meets innovation — a breakthrough in your practice, an unconventional method that produces extraordinary results, or a sudden insight that redefines your focus.',
      focus: 'Try the unconventional approach to your most disciplined practice.',
      caution: 'Careful — abandoning proven methods for novelty without testing the new approach.',
      tags: ['Innovation', 'Focus', 'Breakthrough'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 6,
    },
    Neptune: {
      title: 'Mystical Service',
      summary: 'Devotion dissolves into the divine. This is a time for prayer, meditation, and surrender to something greater than personal effort. Service becomes worship, and the boundary between work and spiritual practice disappears entirely.',
      focus: 'Let your service become a form of prayer and surrender to the sacred.',
      caution: 'The shadow side is spiritual escapism or losing practical effectiveness in mystical abstraction.',
      tags: ['Prayer', 'Surrender', 'Mysticism'],
      energyScore: 4,
      stabilityScore: 5,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // JUNO HOUR
  // ─────────────────────────────────────────────
  Juno: {
    Mars: {
      title: 'Active Alliance',
      summary: 'Partnership demands action. This is a time for defending your bonds, fighting for fairness, and bringing direct energy to relational dynamics. Passivity will not serve you — stand up for what your partnerships need.',
      focus: 'Take decisive action to protect or strengthen your most important alliance.',
      caution: 'Keep an eye on aggression toward a partner or turning negotiation into combat.',
      tags: ['Partnership', 'Action', 'Defense'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Venus: {
      title: 'Union in Beauty',
      summary: 'Harmony flows through your partnerships. This is a time where love, mutual appreciation, and shared beauty deepen the bonds between people. Commitment feels natural and joyful rather than heavy or obligatory.',
      focus: 'Celebrate the beauty in your partnership and express appreciation openly.',
      caution: 'Avoid papering over real issues with pleasantries.',
      tags: ['Love', 'Harmony', 'Union'],
      energyScore: 5,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Mercury: {
      title: 'Clear Agreements',
      summary: 'Words build lasting structures between people. This is a time for clear negotiation, contract review, and mediation — any dialogue where precision and fairness matter. The goal is not to win, but to reach an agreement that endures.',
      focus: 'Communicate your terms clearly and listen with equal care.',
      caution: 'Watch for legalistic maneuvering that sacrifices the spirit of the agreement.',
      tags: ['Negotiation', 'Contracts', 'Communication'],
      energyScore: 6,
      stabilityScore: 7,
      spiritualScore: 3,
    },
    Moon: {
      title: 'Bonded Care',
      summary: 'Emotional loyalty deepens the bond. This is a time where partnerships are nurtured through care, presence, and shared vulnerability. The strength of your union is measured not by contracts, but by how safely you hold each other.',
      focus: 'Show your partner that they are emotionally safe with you.',
      caution: 'The trap here is emotional enmeshment or losing your identity inside the relationship.',
      tags: ['Loyalty', 'Care', 'Bonding'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Partnership Pride',
      summary: 'Your union steps into the light. This is a time for visible commitment — celebrating a partnership publicly, leading together, and sharing pride in what you have built. The bond becomes a source of confidence and identity.',
      focus: 'Let your partnership be visible and lead together with shared purpose.',
      caution: 'Steer clear of competing with your partner for recognition or overshadowing their contribution.',
      tags: ['Pride', 'Leadership', 'Partnership'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 3,
    },
    Vesta: {
      title: 'Devoted Union',
      summary: 'Commitment becomes sacred practice. This is a time where loyalty is not just felt — it is actively cultivated through discipline and devoted attention. The partnership is tended like a flame, with consistency and reverence.',
      focus: 'Invest focused, intentional effort into your most important commitment.',
      caution: 'Be wary of turning partnership into an obligation that drains rather than nourishes.',
      tags: ['Devotion', 'Commitment', 'Sacred'],
      energyScore: 5,
      stabilityScore: 9,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Perfect Balance',
      summary: 'Equality reigns. This is a time of pure partnership energy — alliance, formal agreements, and the exquisite balance of giving and receiving. Every interaction is measured by fairness, and every contract carries the weight of mutual respect.',
      focus: 'Seek perfect equilibrium in your agreements and honor both sides equally.',
      caution: 'The risk: obsessing over fairness to the point of paralysis.',
      tags: ['Balance', 'Alliance', 'Contract'],
      energyScore: 5,
      stabilityScore: 9,
      spiritualScore: 4,
    },
    Pluto: {
      title: 'Karmic Bond',
      summary: 'Relationships encounter depth. This is a time where partnerships are tested by intensity — power dynamics surface, hidden truths emerge, and bonds either transform or break. What survives this moment is real.',
      focus: 'Face the truth about your partnership dynamics with courage and honesty.',
      caution: 'Careful — manipulation or using the bond as a tool for control.',
      tags: ['Karma', 'Depth', 'Transformation'],
      energyScore: 7,
      stabilityScore: 4,
      spiritualScore: 6,
    },
    Jupiter: {
      title: 'Blessed Union',
      summary: 'Fortune smiles on partnership. This is a time where alliances grow, expand, and attract blessings. Whether through marriage, business deals, or collaborative ventures, growth comes through joining forces with the right people.',
      focus: 'Expand through partnership — the right alliance multiplies your potential.',
      caution: 'The shadow side is overcommitting or assuming every partner shares your vision.',
      tags: ['Blessing', 'Growth', 'Partnership'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Tested Loyalty',
      summary: 'Commitment faces its hardest test. This is a time where partnerships are measured by endurance — the bonds that survive pressure, delay, and difficulty are the ones worth keeping. Duty and loyalty are not glamorous, but they are real.',
      focus: 'Honor your commitments even when it is difficult — this is where loyalty is proven.',
      caution: 'Keep an eye on staying in bonds that have become prisons out of misplaced obligation.',
      tags: ['Duty', 'Loyalty', 'Endurance'],
      energyScore: 5,
      stabilityScore: 10,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Liberated Bond',
      summary: 'Partnership breaks its own rules. This is a time for unconventional unions, surprising agreements, and the freedom to redefine what commitment means. The relationship that survives this moment does so by evolving.',
      focus: 'Give your partnership the freedom to grow beyond its original form.',
      caution: 'Avoid using freedom as an excuse to avoid genuine intimacy.',
      tags: ['Freedom', 'Innovation', 'Partnership'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Neptune: {
      title: 'Soul Contract',
      summary: 'Partnership transcends the material. This is a time where unions feel destined, compassion deepens commitment, and the bond between people takes on a spiritual quality. Love here is not practical — it is sacred and idealistic.',
      focus: 'Trust the deeper meaning of your connection and let compassion guide your bond.',
      caution: 'Watch for idealizing a partner beyond recognition or ignoring red flags in the name of destiny.',
      tags: ['Soul', 'Compassion', 'Idealism'],
      energyScore: 4,
      stabilityScore: 4,
      spiritualScore: 9,
    },
  },

  // ─────────────────────────────────────────────
  // PLUTO HOUR
  // ─────────────────────────────────────────────
  Pluto: {
    Mars: {
      title: 'Total Force',
      summary: 'Power collides with will. This is a time of extraordinary intensity — survival instincts activate, power struggles surface, and the force of transformation demands action. Nothing here is gentle, but everything here is real.',
      focus: 'Channel your deepest power into the confrontation that cannot be avoided.',
      caution: 'The trap here is destructive rage or engaging in battles that serve only ego.',
      tags: ['Power', 'Survival', 'Force'],
      energyScore: 10,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Venus: {
      title: 'Magnetic Obsession',
      summary: 'Attraction reaches its most intense frequency. This is a time where desire becomes consuming — love, beauty, and value are experienced at a depth that can be both thrilling and overwhelming. What draws you now touches something primal.',
      focus: 'Honor the depth of your desire without losing yourself inside it.',
      caution: 'Steer clear of obsessive attachment or confusing possession with love.',
      tags: ['Obsession', 'Magnetism', 'Desire'],
      energyScore: 7,
      stabilityScore: 4,
      spiritualScore: 5,
    },
    Mercury: {
      title: 'Piercing Truth',
      summary: 'The mind cuts to the bone. This is a time for relentless investigation, psychological insight, and the kind of analysis that reveals what others cannot see. No secret is safe from this level of mental penetration.',
      focus: 'Investigate what has been hidden and speak the truth others avoid.',
      caution: 'Be wary of weaponizing knowledge or using insight to manipulate others.',
      tags: ['Investigation', 'Truth', 'Psychology'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Emotional Purge',
      summary: 'The emotional depths crack open. This is a time of catharsis — long-buried feelings, trauma, and hidden pain rise to the surface demanding release. It is uncomfortable and essential. Healing begins where denial ends.',
      focus: 'Let the emotional release happen — what surfaces now has been waiting for this.',
      caution: 'The risk: projecting your pain onto others or mistaking catharsis for crisis.',
      tags: ['Catharsis', 'Healing', 'Depth'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 6,
    },
    Sun: {
      title: 'Exposed Power',
      summary: 'Identity transforms under the spotlight. This is a time where who you really are — beneath the persona — is brought into the light. It may feel like exposure, but it is also liberation. Authenticity becomes the only viable strategy.',
      focus: 'Embrace the transformation of your identity and let the old mask fall away.',
      caution: 'Careful — power plays or using visibility to intimidate rather than illuminate.',
      tags: ['Truth', 'Power', 'Visibility'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 5,
    },
    Vesta: {
      title: 'Shadow Discipline',
      summary: 'Sacred intensity meets shadow work. This is a time for disciplined confrontation with the deepest parts of yourself — purification through focused, unflinching attention. The work is demanding but the results are transformative.',
      focus: 'Apply sacred discipline to your most difficult inner work.',
      caution: 'The shadow side is self-punishment masquerading as spiritual practice.',
      tags: ['Shadow Work', 'Purification', 'Ritual'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 7,
    },
    Juno: {
      title: 'Transforming Bonds',
      summary: 'Relationships enter the crucible. This is a time where partnerships are transformed through truth-telling, karmic reckoning, and the willingness to die to what the relationship was in order to become what it must be.',
      focus: 'Allow your most important bond to evolve through honest, deep engagement.',
      caution: 'Keep an eye on destroying a relationship to avoid your own transformation.',
      tags: ['Karma', 'Healing', 'Partnership'],
      energyScore: 6,
      stabilityScore: 4,
      spiritualScore: 6,
    },
    Pluto: {
      title: 'Full Metamorphosis',
      summary: 'Total transformation is underway. This is a time of endings and beginnings compressed into a single moment — nothing survives unchanged. The old must die so the new can be born. Resistance is futile; surrender to the process.',
      focus: 'Release what is dying and trust the rebirth that is already beginning.',
      caution: 'Avoid clinging to what has already ended or mistaking destruction for progress.',
      tags: ['Rebirth', 'Intensity', 'Transformation'],
      energyScore: 8,
      stabilityScore: 2,
      spiritualScore: 7,
    },
    Jupiter: {
      title: 'Empowered Growth',
      summary: 'Transformation meets expansion. This is a time where deep, powerful change creates room for massive growth — truth enlarges your influence, and the willingness to face the dark gives you access to extraordinary opportunity.',
      focus: 'Let your deepest transformation fuel your greatest expansion.',
      caution: 'Watch for using power for personal gain without considering the impact on others.',
      tags: ['Empowerment', 'Growth', 'Truth'],
      energyScore: 9,
      stabilityScore: 4,
      spiritualScore: 6,
    },
    Saturn: {
      title: 'Karmic Pressure',
      summary: 'Reality presses down with transformative weight. This is a time of restructuring under pressure — old foundations crumble so new ones can be built. The work is heavy but necessary. What survives this moment is built on bedrock.',
      focus: 'Accept the restructuring that is required and build on what remains solid.',
      caution: 'The trap here is rigidity in the face of change or breaking under pressure you were meant to bear.',
      tags: ['Pressure', 'Endurance', 'Restructuring'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Uranus: {
      title: 'Radical Rebirth',
      summary: 'The ground shifts beneath everything. This is a time of explosive awakening — sudden transformation, the destruction of limits, and radical change that cannot be predicted or controlled. Liberation comes through upheaval.',
      focus: 'Embrace the radical change that has arrived — it is clearing the way for something essential.',
      caution: 'Steer clear of nihilistic destruction or confusing chaos with liberation.',
      tags: ['Revolution', 'Awakening', 'Destruction'],
      energyScore: 9,
      stabilityScore: 1,
      spiritualScore: 6,
    },
    Neptune: {
      title: 'Mystical Abyss',
      summary: 'The deepest depths meet the infinite. This is a time of ego dissolution, psychic intensity, and the experience of forces beyond comprehension. The boundary between self and universe dissolves. Surrender is not a choice — it is the only option.',
      focus: 'Let go of the need to understand and allow the mystery to transform you.',
      caution: 'Be wary of existential despair or losing your grounding in the face of the unknown.',
      tags: ['Mystery', 'Dissolution', 'Psychic'],
      energyScore: 5,
      stabilityScore: 2,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // JUPITER HOUR
  // ─────────────────────────────────────────────
  Jupiter: {
    Mars: {
      title: 'Bold Fortune',
      summary: 'Adventure calls with irresistible force. This is a time for courageous expansion — taking bold risks, launching ambitious ventures, and charging forward with optimism and fire. The universe rewards bravery right now.',
      focus: 'Take the bold leap that your instincts have been urging you toward.',
      caution: 'The risk: recklessness disguised as confidence or gambling beyond your means.',
      tags: ['Adventure', 'Courage', 'Expansion'],
      energyScore: 9,
      stabilityScore: 5,
      spiritualScore: 4,
    },
    Venus: {
      title: 'Abundant Love',
      summary: 'Blessings flow through beauty and connection. This is a time of fortunate attraction, generous affection, and the sense that love and pleasure are abundant. Give freely, receive graciously, and trust that there is enough for everyone.',
      focus: 'Open your heart to the abundance of love and beauty surrounding you.',
      caution: 'Careful — overindulgence or taking generosity for granted.',
      tags: ['Abundance', 'Love', 'Blessings'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Mercury: {
      title: 'Wise Teaching',
      summary: 'Knowledge expands and seeks to be shared. This is a time for teaching, publishing, strategic communication, and the kind of broad learning that connects disparate ideas into wisdom. The mind reaches outward and upward.',
      focus: 'Share what you know generously and seek the teaching that will change your perspective.',
      caution: 'The shadow side is pontificating or mistaking opinion for wisdom.',
      tags: ['Teaching', 'Wisdom', 'Publishing'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Healing Hope',
      summary: 'Emotional uplift arrives like sunlight after rain. This is a time of healing optimism, protective generosity, and a deep faith that things will work out. The heart feels buoyant and the desire to nurture others comes from a place of genuine abundance.',
      focus: 'Let hope guide your emotions and be generous with your warmth.',
      caution: 'Keep an eye on toxic positivity or offering hope that bypasses genuine grief.',
      tags: ['Hope', 'Healing', 'Faith'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 6,
    },
    Sun: {
      title: 'Golden Success',
      summary: 'Confidence and fortune align in brilliant harmony. Recognition, growth, and the quiet sense that you are exactly where you are meant to be all arrive together. Success under this hour feels less like a push and more like a tailwind.',
      focus: 'Step into the recognition and growth that have been building for you.',
      caution: 'Avoid complacency or believing that luck alone sustains success.',
      tags: ['Success', 'Recognition', 'Growth'],
      energyScore: 9,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Vesta: {
      title: 'Sacred Expansion',
      summary: 'Growth becomes devotional practice. This is a time where disciplined study, sacred learning, and devoted effort produce extraordinary results. Expansion is not scattered — it is focused, intentional, and deeply meaningful.',
      focus: 'Grow through dedicated practice and let your discipline amplify your blessings.',
      caution: 'Watch for limiting your expansion through excessive rigidity or narrow focus.',
      tags: ['Growth', 'Devotion', 'Study'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 7,
    },
    Juno: {
      title: 'Fortunate Alliance',
      summary: 'Partnerships attract blessings. This is a time where joining forces produces greater results than going alone — beneficial agreements, growth through collaboration, and the luck that comes from the right alliance at the right time.',
      focus: 'Seek or strengthen the partnership that multiplies your growth.',
      caution: 'The trap here is unequal partnerships where one side gives more than it receives.',
      tags: ['Partnership', 'Fortune', 'Growth'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Pluto: {
      title: 'Deep Empowerment',
      summary: 'Expansion meets the depths. This is a time where growth comes through confrontation with truth and power — not surface-level optimism, but the kind of expansion that occurs when you face your shadow and emerge stronger.',
      focus: 'Let your growth come from the deepest place rather than the easiest.',
      caution: 'Steer clear of using influence or power without ethical consideration.',
      tags: ['Empowerment', 'Expansion', 'Truth'],
      energyScore: 9,
      stabilityScore: 4,
      spiritualScore: 6,
    },
    Jupiter: {
      title: 'Maximum Blessing',
      summary: 'Abundance multiplies itself. This is a time of peak growth, extraordinary luck, and the sense that every door is opening simultaneously. Opportunities arrive faster than you can process them. The universe is generous.',
      focus: 'Receive the blessings that are arriving and choose the best opportunity wisely.',
      caution: 'Be wary of greed, overextension, or assuming that abundance requires no stewardship.',
      tags: ['Luck', 'Abundance', 'Opportunity'],
      energyScore: 8,
      stabilityScore: 6,
      spiritualScore: 7,
    },
    Saturn: {
      title: 'Measured Growth',
      summary: 'Expansion meets structure. This is a time for responsible growth — the kind of success that is built on solid foundations, strategic planning, and the maturity to say no to what does not serve the long-term vision.',
      focus: 'Grow steadily in the direction that serves your most enduring goals.',
      caution: 'The risk: limiting growth through excessive caution or expanding without a plan.',
      tags: ['Strategy', 'Growth', 'Discipline'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Uranus: {
      title: 'Visionary Luck',
      summary: 'Opportunity arrives like lightning. This is a time of sudden breakthroughs, unexpected blessings, and the kind of growth that comes from being willing to follow an unconventional path. What appears out of nowhere may change everything.',
      focus: 'Follow the unexpected opportunity that just appeared — it may be the one that matters most.',
      caution: 'Careful — chasing every shiny possibility or mistaking disruption for opportunity.',
      tags: ['Breakthrough', 'Vision', 'Opportunity'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Neptune: {
      title: 'Divine Grace',
      summary: 'Blessings arrive from beyond the visible. This is a time of profound spiritual expansion — faith deepens, compassion broadens, and the sense of being guided by something greater than yourself is unmistakable. Grace is the word.',
      focus: 'Trust the unseen forces that are guiding your growth and surrender to grace.',
      caution: 'The shadow side is spiritual grandiosity or detaching from practical reality.',
      tags: ['Grace', 'Faith', 'Spirituality'],
      energyScore: 5,
      stabilityScore: 5,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // SATURN HOUR
  // ─────────────────────────────────────────────
  Saturn: {
    Mars: {
      title: 'Forged Discipline',
      summary: 'Raw force meets enduring structure. This is a time for controlled, strategic effort — the kind of work that requires both strength and patience. You are forging something that will last, and the process demands everything you have.',
      focus: 'Apply your full strength to the work that requires the most endurance.',
      caution: 'Keep an eye on frustration-driven shortcuts or forcing results that need time.',
      tags: ['Endurance', 'Strategy', 'Effort'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 3,
    },
    Venus: {
      title: 'Loyal Value',
      summary: 'Love matures into something unbreakable. This is a time for stable partnerships, disciplined financial management, and the kind of beauty that comes from age, experience, and weathering storms together. Value what has proven itself.',
      focus: 'Invest in the relationships and assets that have earned your trust.',
      caution: 'Avoid being so cautious with love or money that you starve both.',
      tags: ['Loyalty', 'Finance', 'Maturity'],
      energyScore: 5,
      stabilityScore: 9,
      spiritualScore: 3,
    },
    Mercury: {
      title: 'Structured Mind',
      summary: 'Thought becomes architecture. This is a time for serious planning, realistic assessment, and communication that carries the weight of authority. Every word counts. Every plan must account for what could go wrong.',
      focus: 'Plan with discipline and speak only what you are prepared to stand behind.',
      caution: 'Watch for negativity masquerading as realism or silencing creative thinking.',
      tags: ['Planning', 'Structure', 'Realism'],
      energyScore: 6,
      stabilityScore: 9,
      spiritualScore: 2,
    },
    Moon: {
      title: 'Steady Heart',
      summary: 'Emotions are contained without being suppressed. This is a time for emotional maturity — holding space for difficult feelings while maintaining composure. The heart is strong because it has learned to endure without breaking.',
      focus: 'Meet your emotions with patience and respond from a place of inner stability.',
      caution: 'The trap here is emotional coldness or punishing yourself for having feelings.',
      tags: ['Maturity', 'Containment', 'Stability'],
      energyScore: 4,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Sun: {
      title: 'Crowned Authority',
      summary: 'Responsibility and visibility merge into true leadership. This is a time where your authority is both visible and weighty — the crown is not given for free, it is earned through sustained effort and the willingness to carry what others cannot.',
      focus: 'Accept the responsibility that comes with your position and lead with integrity.',
      caution: 'Steer clear of authoritarian control or letting the weight of responsibility crush your spirit.',
      tags: ['Authority', 'Responsibility', 'Vision'],
      energyScore: 7,
      stabilityScore: 9,
      spiritualScore: 3,
    },
    Vesta: {
      title: 'Master Craftsman',
      summary: 'Discipline meets devotion in the highest expression of mastery. This is a time for austere, focused work — the kind that produces excellence through sheer commitment. Sacred duty and practical effort are one and the same.',
      focus: 'Pursue mastery through unwavering discipline and sacred dedication.',
      caution: 'Be wary of neglecting rest and human connection in the pursuit of perfection.',
      tags: ['Mastery', 'Duty', 'Discipline'],
      energyScore: 6,
      stabilityScore: 10,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Binding Oath',
      summary: 'Commitment is forged in iron. This is a time for serious agreements, tested loyalty, and the formal bonds that define lasting partnerships. What you commit to now carries weight and consequence. Choose wisely and honor fully.',
      focus: 'Make only the commitments you are prepared to keep through difficulty.',
      caution: 'The risk: commitments born from obligation rather than genuine intention.',
      tags: ['Commitment', 'Duty', 'Loyalty'],
      energyScore: 5,
      stabilityScore: 10,
      spiritualScore: 3,
    },
    Pluto: {
      title: 'Karmic Reckoning',
      summary: 'Old structures face their day of truth. This is a time of deep, often uncomfortable restructuring — karmic debts come due, outdated foundations crumble, and the only path forward requires letting go of what no longer holds.',
      focus: 'Accept the restructuring that reality demands and release what cannot be saved.',
      caution: 'Careful — clinging to structures that have outlived their purpose.',
      tags: ['Karma', 'Pressure', 'Restructuring'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Steady Ascent',
      summary: 'Growth takes the stairs instead of the elevator. This is a time for structured expansion, mature wisdom, and the kind of success that is built slowly and sustainably. The result may not be flashy, but it will endure.',
      focus: 'Expand through patient, disciplined effort and small, repeated commitments.',
      caution: 'The shadow side is impatience or dismissing slow progress as failure.',
      tags: ['Growth', 'Wisdom', 'Structure'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Iron Will',
      summary: 'Maximum discipline meets maximum endurance. This is a time where nothing is easy, but everything built is permanent. The force of will required is immense — and so is the reward for those who do not quit. Order, accountability, and commitment reign.',
      focus: 'Commit fully to the hardest work before you and refuse to yield.',
      caution: 'Keep an eye on rigidity that breaks rather than bends, or mistaking harshness for strength.',
      tags: ['Endurance', 'Order', 'Commitment'],
      energyScore: 6,
      stabilityScore: 10,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Tense Reform',
      summary: 'Structure and freedom clash productively. This is a time of reform under pressure — the old system must evolve, and the tension between tradition and innovation produces breakthroughs that are both radical and sustainable.',
      focus: 'Find the balance between necessary structure and essential change.',
      caution: 'Avoid resisting change out of fear or destroying structure out of impatience.',
      tags: ['Reform', 'Tension', 'Innovation'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 4,
    },
    Neptune: {
      title: 'Grounded Spirit',
      summary: 'Discipline anchors the spiritual. This is a time where faith meets reality — prayer is practical, intuition is tested, and spiritual insight must prove itself against the demands of the material world. Grounded mysticism at its finest.',
      focus: 'Apply spiritual wisdom to concrete, real-world challenges.',
      caution: 'Watch for dismissing spiritual insight as impractical or spiritualizing your avoidance of hard work.',
      tags: ['Discipline', 'Spirit', 'Maturity'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 7,
    },
  },

  // ─────────────────────────────────────────────
  // URANUS HOUR
  // ─────────────────────────────────────────────
  Uranus: {
    Mars: {
      title: 'Lightning Strike',
      summary: 'Action erupts without warning. This is a time of sudden, electrifying movement — impulsive breakthroughs, rebellion against constraint, and the kind of rapid change that rewrites the situation entirely. Speed is everything.',
      focus: 'Act on the sudden impulse that breaks the pattern — this is your moment of liberation.',
      caution: 'The trap here is impulsive destruction or recklessness that creates collateral damage.',
      tags: ['Rebellion', 'Speed', 'Breakthrough'],
      energyScore: 10,
      stabilityScore: 1,
      spiritualScore: 4,
    },
    Venus: {
      title: 'Wild Chemistry',
      summary: 'Attraction takes an unexpected turn. This is a time of unusual connections, sudden romantic sparks, and the thrilling experience of beauty in unconventional forms. Love is exciting, unpredictable, and refuses to follow the rules.',
      focus: 'Welcome the unexpected connection that defies your usual type or pattern.',
      caution: 'Steer clear of confusing excitement with compatibility or abandoning stability for a rush.',
      tags: ['Excitement', 'Freedom', 'Chemistry'],
      energyScore: 8,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Mercury: {
      title: 'Genius Frequency',
      summary: 'The mind tunes into frequencies others cannot hear. This is a time for radical communication, technological innovation, and ideas that arrive fully formed from somewhere beyond ordinary thought. Information downloads are fast and disruptive.',
      focus: 'Trust the unconventional idea that just arrived and communicate it fearlessly.',
      caution: 'Be wary of information overload or expressing radical ideas in ways that alienate your audience.',
      tags: ['Genius', 'Innovation', 'Downloads'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Emotional Lightning',
      summary: 'Feelings shift with shocking speed. This is a time of emotional awakening — sudden insight about what you really feel, unexpected mood shifts, and the liberation that comes from breaking free of old emotional patterns.',
      focus: 'Welcome the emotional insight that arrives as a shock — it is freeing something.',
      caution: 'The risk: emotional whiplash or making permanent decisions based on temporary feelings.',
      tags: ['Awakening', 'Surprise', 'Release'],
      energyScore: 7,
      stabilityScore: 2,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Original Fire',
      summary: 'Identity becomes radical self-expression. This is a time where your uniqueness demands visibility — you cannot hide who you are, and the world benefits from your refusal to conform. Be the revolution you wish to see.',
      focus: 'Express your most authentic, unconventional self without apology.',
      caution: 'Careful — contrarianism that serves no purpose or rebellion against your own well-being.',
      tags: ['Originality', 'Rebellion', 'Expression'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Vesta: {
      title: 'Awakened Focus',
      summary: 'Innovation meets sacred discipline. This is a time where an unconventional approach to focused work produces extraordinary results — breaking the rules of your own practice in a way that deepens rather than scatters your devotion.',
      focus: 'Apply a radically new method to your most devoted practice.',
      caution: 'The shadow side is abandoning what works in the name of novelty.',
      tags: ['Focus', 'Innovation', 'Devotion'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Free Alliance',
      summary: 'Partnership reinvents itself. This is a time for nontraditional unions, surprising agreements, and the freedom to redefine the rules of commitment. Relationships that embrace change thrive; those that resist it feel the strain.',
      focus: 'Allow your relationships to evolve beyond conventional expectations.',
      caution: 'Keep an eye on using freedom as a weapon or destabilizing partnerships for the thrill of it.',
      tags: ['Freedom', 'Partnership', 'Surprise'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Pluto: {
      title: 'Total Revolution',
      summary: 'Everything changes at once. This is a time of seismic upheaval — the convergence of radical awakening and deep transformation that leaves nothing untouched. Old systems collapse, old selves dissolve, and what emerges is unrecognizable.',
      focus: 'Surrender to the revolution that has already begun — you cannot stop it, only direct it.',
      caution: 'Avoid nihilistic destruction or losing your humanity in the chaos of transformation.',
      tags: ['Revolution', 'Transformation', 'Upheaval'],
      energyScore: 10,
      stabilityScore: 1,
      spiritualScore: 6,
    },
    Jupiter: {
      title: 'Visionary Leap',
      summary: 'The future arrives ahead of schedule. This is a time of massive, sudden expansion — breakthrough growth, unexpected abundance, and the kind of opportunity that appears only when you are willing to leap without a net.',
      focus: 'Take the visionary leap that others are too cautious to attempt.',
      caution: 'Watch for overextending in the excitement or mistaking recklessness for vision.',
      tags: ['Vision', 'Expansion', 'Breakthrough'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 6,
    },
    Saturn: {
      title: 'Structured Rebellion',
      summary: 'Innovation finds its discipline. This is a time where radical ideas meet practical structure — the rebellion that succeeds because it has a plan, the innovation that endures because it was built with rigor. Tension produces progress.',
      focus: 'Give your most radical idea a solid, practical framework.',
      caution: 'The trap here is letting either structure or rebellion dominate at the expense of the other.',
      tags: ['Reform', 'Structure', 'Innovation'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 4,
    },
    Uranus: {
      title: 'Pure Liberation',
      summary: 'Freedom is total and uncompromising. This is a time of radical change, full awakening, and the complete dismantling of whatever has been holding you back. Nothing is sacred except liberation itself. The cage door is open.',
      focus: 'Step through the door that has just opened — total freedom is available now.',
      caution: 'Steer clear of destroying what you actually need in the frenzy of liberation.',
      tags: ['Liberation', 'Awakening', 'Change'],
      energyScore: 9,
      stabilityScore: 1,
      spiritualScore: 6,
    },
    Neptune: {
      title: 'Cosmic Download',
      summary: 'The cosmos speaks in frequencies beyond language. This is a time of visionary spirituality, surreal awakening, and the kind of insight that feels like it comes from another dimension entirely. Reality is stranger than you thought.',
      focus: 'Open yourself to the cosmic insight that is trying to reach you.',
      caution: 'Be wary of dissociation or mistaking disorientation for enlightenment.',
      tags: ['Vision', 'Cosmic', 'Awakening'],
      energyScore: 6,
      stabilityScore: 2,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // NEPTUNE HOUR
  // ─────────────────────────────────────────────
  Neptune: {
    Mars: {
      title: 'Spiritual Warrior',
      summary: 'Action is guided by the invisible. This is a time for inspired effort, sacrifice in service of a higher cause, and the courage to act on spiritual conviction. The warrior\'s sword is held by unseen hands.',
      focus: 'Act from spiritual conviction and let your effort be an offering.',
      caution: 'The risk: martyrdom, confused motivations, or fighting battles that are not yours to fight.',
      tags: ['Sacrifice', 'Inspiration', 'Effort'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 7,
    },
    Venus: {
      title: 'Dream Romance',
      summary: 'Love becomes transcendent. This is a time of soft beauty, spiritual connection, and the kind of romance that feels like a dream — idealistic, boundless, and tinged with something otherworldly. The heart sees with its soul.',
      focus: 'Let yourself be enchanted by the beauty that exists beyond the material.',
      caution: 'Careful — romantic delusion or falling in love with a fantasy rather than a person.',
      tags: ['Romance', 'Dreams', 'Beauty'],
      energyScore: 4,
      stabilityScore: 4,
      spiritualScore: 9,
    },
    Mercury: {
      title: 'Visionary Words',
      summary: 'Language dissolves into poetry. This is a time for spiritual messages, imaginative writing, and communication that reaches beyond the literal. Words carry images, feelings, and vibrations rather than just information.',
      focus: 'Write, speak, or create from the place where imagination and spirit meet.',
      caution: 'The shadow side is miscommunication, deception, or confusing poetic language with factual truth.',
      tags: ['Poetry', 'Vision', 'Imagination'],
      energyScore: 5,
      stabilityScore: 3,
      spiritualScore: 8,
    },
    Moon: {
      title: 'Psychic Ocean',
      summary: 'Sensitivity has no boundaries. This is a time of full psychic openness — empathy is oceanic, dreams are vivid, and the inner world is as real as the outer one. Everything seems to be listening at once.',
      focus: 'Trust your deepest intuitive impressions and let the psychic tide carry you.',
      caution: 'Keep an eye on absorbing the suffering of others or losing yourself in boundless feeling.',
      tags: ['Psychic', 'Dreams', 'Empathy'],
      energyScore: 3,
      stabilityScore: 3,
      spiritualScore: 10,
    },
    Sun: {
      title: 'Inspired Glow',
      summary: 'Identity becomes a vessel for the divine. This is a time where you radiate spiritual light — your presence carries something beyond personality, and your creative expression channels a source greater than ego. Be the light.',
      focus: 'Let your presence be a vessel for inspiration and spiritual warmth.',
      caution: 'Avoid losing your sense of self in the spiritual current or becoming ungrounded.',
      tags: ['Inspiration', 'Radiance', 'Vision'],
      energyScore: 5,
      stabilityScore: 4,
      spiritualScore: 8,
    },
    Vesta: {
      title: 'Sacred Surrender',
      summary: 'Devotion becomes prayer. This is a time for deep meditation, mystical service, and the surrender of personal will to something greater. Effort dissolves into offering, and discipline becomes a form of worship.',
      focus: 'Surrender your effort to the sacred and let your service become prayer.',
      caution: 'Watch for spiritual bypassing or using devotion to avoid engaging with practical reality.',
      tags: ['Prayer', 'Meditation', 'Surrender'],
      energyScore: 3,
      stabilityScore: 5,
      spiritualScore: 10,
    },
    Juno: {
      title: 'Soul Bond',
      summary: 'Partnership transcends the earthly. This is a time where the connection between people feels destined, spiritual, and guided by forces beyond individual will. Compassion deepens commitment, and love operates on the level of the soul.',
      focus: 'Trust the deeper, spiritual dimension of your most meaningful bond.',
      caution: 'The trap here is idealizing a partner to the point of losing sight of who they actually are.',
      tags: ['Soul', 'Compassion', 'Union'],
      energyScore: 4,
      stabilityScore: 4,
      spiritualScore: 9,
    },
    Pluto: {
      title: 'Infinite Depth',
      summary: 'The deepest transformation meets the most boundless surrender. This is a time where ego dissolves under the weight of forces far greater than the self — mystical death and rebirth, psychic flooding, and the encounter with the infinite.',
      focus: 'Release your grip on identity and let the transformation complete itself.',
      caution: 'Steer clear of existential terror or losing your will to function in the dissolution.',
      tags: ['Transformation', 'Mystery', 'Dissolution'],
      energyScore: 5,
      stabilityScore: 2,
      spiritualScore: 10,
    },
    Jupiter: {
      title: 'Divine Expansion',
      summary: 'Faith expands without limit. This is a time of profound spiritual growth — grace, blessings, and the sense that the universe is infinitely generous and infinitely mysterious. Compassion and wisdom merge into something luminous.',
      focus: 'Expand your faith and trust the spiritual abundance that surrounds you.',
      caution: 'Be wary of spiritual materialism or using mystical experiences to inflate your ego.',
      tags: ['Grace', 'Faith', 'Expansion'],
      energyScore: 5,
      stabilityScore: 5,
      spiritualScore: 10,
    },
    Saturn: {
      title: 'Grounded Mysticism',
      summary: 'Spiritual vision meets earthly discipline. This is a time where intuition is tested against reality, faith is tempered by experience, and the mystical must prove its worth in the material world. The result is wisdom that serves both worlds.',
      focus: 'Bring your spiritual insights into practical application.',
      caution: 'The risk: dismissing spiritual experience as impractical or avoiding hard work through mysticism.',
      tags: ['Faith', 'Structure', 'Devotion'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 8,
    },
    Uranus: {
      title: 'Cosmic Vision',
      summary: 'Reality bends. This is a time of strange visions, spiritual breakthroughs, and insights that arrive from dimensions beyond ordinary perception. The experience may be disorienting, but what you see cannot be unseen.',
      focus: 'Open yourself to the vision that is breaking through from beyond the ordinary.',
      caution: 'Careful — confusion or mistaking disorientation for enlightenment.',
      tags: ['Vision', 'Breakthrough', 'Cosmic'],
      energyScore: 6,
      stabilityScore: 2,
      spiritualScore: 10,
    },
    Neptune: {
      title: 'Pure Transcendence',
      summary: 'The boundary between self and everything else dissolves completely. This is a time of total surrender, divine mystery, and the experience of oneness that defies description. There is nothing to hold onto, and nothing to fear in letting go.',
      focus: 'Surrender completely and let the mystery reveal what it will.',
      caution: 'The shadow side is complete dissociation from reality or neglecting your earthly responsibilities.',
      tags: ['Transcendence', 'Mystery', 'Surrender'],
      energyScore: 2,
      stabilityScore: 2,
      spiritualScore: 10,
    },
  },
};

// ─────────────────────────────────────────────
// Lookup Helper
// ─────────────────────────────────────────────

export function getHourMinuteInterpretation(
  hourLord: string,
  minuteLord: string,
): HourMinuteInterpretation {
  const hourData = GALACTIC_HOUR_MINUTE_INTERPRETATIONS[hourLord];
  if (hourData && hourData[minuteLord]) {
    return hourData[minuteLord];
  }
  return fallbackInterpretation(hourLord, minuteLord);
}

// ─────────────────────────────────────────────
// Fallback Synthesizer
// ─────────────────────────────────────────────

function fallbackInterpretation(
  hourLord: string,
  minuteLord: string,
): HourMinuteInterpretation {
  const hourMeaning = RULER_MEANINGS[hourLord] || {
    keywords: 'cosmic force',
    essence: 'universal energy',
  };
  const minuteMeaning = RULER_MEANINGS[minuteLord] || {
    keywords: 'flowing expression',
    essence: 'active channel',
  };
  return {
    title: `${hourLord} through ${minuteLord}`,
    summary: `The dominant force of ${hourMeaning.essence} expresses through ${minuteMeaning.essence}. This combination creates a unique moment worth paying attention to.`,
    focus: `Channel the energy of ${hourLord} through the method of ${minuteLord}.`,
    caution: `Stay mindful of how these forces interact in your current situation.`,
    tags: [hourLord, minuteLord],
    energyScore: 5,
    stabilityScore: 5,
    spiritualScore: 5,
  };
}
