/**
 * Galactic Clock: 144 Hour Lord + Minute Lord Interpretations
 *
 * 12 Hour Lords x 12 Minute Lords = 144 unique combinations.
 * Hour Lord = dominant climate/force of the moment.
 * Minute Lord = how that force is currently expressing itself.
 */

export interface HourMinuteInterpretation {
  title: string;
  summary: string;
  focus: string;
  caution: string;
  tags: string[];
  energyScore: number;      // 1-10
  stabilityScore: number;   // 1-10
  spiritualScore: number;   // 1-10
}

interface RulerMeaning {
  keywords: string;
  essence: string;
}

const RULER_MEANINGS: Record<string, RulerMeaning> = {
  Mars: { keywords: 'action, force, courage, drive, confrontation, initiation', essence: 'decisive action and courageous drive' },
  Venus: { keywords: 'attraction, beauty, pleasure, harmony, value, affection', essence: 'magnetic attraction and harmonious beauty' },
  Mercury: { keywords: 'thought, speech, trade, learning, analysis, movement', essence: 'swift thought and clear communication' },
  Moon: { keywords: 'emotion, intuition, nurture, receptivity, reflection, memory', essence: 'emotional depth and intuitive receptivity' },
  Sun: { keywords: 'visibility, leadership, vitality, creativity, confidence, purpose', essence: 'radiant vitality and confident purpose' },
  Vesta: { keywords: 'devotion, concentration, sacred work, discipline, purity, precision', essence: 'focused devotion and sacred discipline' },
  Juno: { keywords: 'partnership, commitment, fairness, union, agreements, loyalty', essence: 'committed partnership and balanced union' },
  Pluto: { keywords: 'depth, power, exposure, transformation, elimination, rebirth', essence: 'transformative power and deep renewal' },
  Jupiter: { keywords: 'growth, wisdom, teaching, opportunity, blessings, expansion', essence: 'expansive wisdom and abundant opportunity' },
  Saturn: { keywords: 'structure, restraint, effort, maturity, responsibility, endurance', essence: 'disciplined structure and mature endurance' },
  Uranus: { keywords: 'innovation, disruption, awakening, freedom, shock, originality', essence: 'radical innovation and liberating awakening' },
  Neptune: { keywords: 'spirituality, dreams, surrender, imagination, compassion, mysticism', essence: 'mystical surrender and spiritual imagination' },
};

export const GALACTIC_HOUR_MINUTE_INTERPRETATIONS: Record<string, Record<string, HourMinuteInterpretation>> = {

  // ─────────────────────────────────────────────
  // MARS HOUR
  // ─────────────────────────────────────────────
  Mars: {
    Mars: {
      title: 'Pure Momentum',
      summary: 'This window is raw forward motion. Whatever you launch right now carries the full force of your will behind it — so launch the thing you\'ve been circling. Nothing about this hour is subtle; it\'s direct, unapologetic, and it rewards whoever moves first.',
      focus: 'Start the hardest thing on your list right now — hesitation costs you more than any mistake will.',
      caution: 'Don\'t swing at everything that moves — a bridge you torch in this window stays torched.',
      tags: ['Action', 'Initiative', 'Courage'],
      energyScore: 10,
      stabilityScore: 3,
      spiritualScore: 2,
    },
    Venus: {
      title: 'Assertive Attraction',
      summary: 'Your drive and your desire are pointed at the same target right now. Use this window for the bold move in love, beauty, or money — you\'re reaching for what you want and pulling it toward you at the same time. The charm is inside the courage. Go.',
      focus: 'Name what you want and go after it — confidence reads as magnetism this hour.',
      caution: 'Don\'t mistake heat for depth — what you attract in this window still has to be vetted.',
      tags: ['Desire', 'Love', 'Money'],
      energyScore: 8,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Mercury: {
      title: 'Sharp Strategy',
      summary: 'Your mind is fast and your tongue is sharper. Use this window for the hard conversation, the rapid decision, the negotiation you\'ve been dreading — your words land with the force of actions right now. Say the precise thing, then stop talking.',
      focus: 'Make the call you\'ve been postponing — your thinking won\'t be this fast again today.',
      caution: 'Don\'t send the message written in anger — what you say this hour can\'t be unsaid.',
      tags: ['Strategy', 'Communication', 'Speed'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 2,
    },
    Moon: {
      title: 'Emotional Charge',
      summary: 'Your feelings are running hot and your instincts are dead-on. This window favors protective action — defend what you love, respond to what actually matters, and trust the gut read you just got. The charge you feel is fuel; point it at something worth it.',
      focus: 'Take the emotion you\'re carrying right now and spend it on purposeful action.',
      caution: 'Don\'t let a bruised feeling pick your next move — react to the threat, not the sting.',
      tags: ['Protection', 'Instinct', 'Emotion'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 4,
    },
    Sun: {
      title: 'Bold Leadership',
      summary: 'This is your hour to be seen taking charge. Step forward, make the call, and let people watch you do it — your presence carries real authority right now, and your actions speak louder than anything you could say. Front of the room. Go.',
      focus: 'Lead from the front this hour — visible, decisive action gets rewarded.',
      caution: 'Don\'t confuse commanding the room with steamrolling it — ego is the one thing that can waste this window.',
      tags: ['Leadership', 'Confidence', 'Visibility'],
      energyScore: 9,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Vesta: {
      title: 'Sacred Drive',
      summary: 'This window turns effort into devotion. Don\'t scatter yourself — pick the one piece of work that actually matters and hit it with concentrated force. What you build in this hour has a ritual quality: heavy, focused, and worth it.',
      focus: 'Pour everything into your single most important task — one target, total concentration.',
      caution: 'Don\'t grind past empty — relentless effort without rest burns the very focus you\'re using.',
      tags: ['Discipline', 'Deep Work', 'Focus'],
      energyScore: 8,
      stabilityScore: 7,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Active Partnership',
      summary: 'Your relationships need direct engagement right now, not politeness. Use this window for the honest negotiation, the defense of a bond, the alliance you\'ve been meaning to build. Passivity in partnership costs you this hour — show up and say the real thing.',
      focus: 'Bring your full presence to your most important relationship or agreement right now.',
      caution: 'Don\'t turn the partnership into a battlefield — fight for the bond, not against the person.',
      tags: ['Partnership', 'Negotiation', 'Commitment'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Pluto: {
      title: 'Power Surge',
      summary: 'Something heavy and transformative is moving through this hour, and it\'s handing you leverage. The thing you\'ve been stuck on can shift right now — if you\'re willing to face it head-on. Confront the truth you\'ve been circling. It moves when you push.',
      focus: 'Face the confrontation you\'ve been avoiding — this window gives you the power to shift it.',
      caution: 'Don\'t pick a power struggle to feed your ego — use this force on truth or not at all.',
      tags: ['Transformation', 'Power', 'Intensity'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Bold Expansion',
      summary: 'Courage and opportunity are in the same room right now. This window favors the risk you\'ve been talking yourself out of — the bigger ask, the leap, the bet on yourself. Fortune backs the brave this hour, and you know exactly which leap this is about.',
      focus: 'Take the calculated risk that serves your bigger vision — this is its window.',
      caution: 'Don\'t bite off three leaps at once — overconfidence is the tax on this hour.',
      tags: ['Expansion', 'Risk', 'Opportunity'],
      energyScore: 9,
      stabilityScore: 4,
      spiritualScore: 4,
    },
    Saturn: {
      title: 'Controlled Force',
      summary: 'This hour wants your strength applied with precision, not speed. Push steadily on the hard thing — the wall moves for pressure, not punches. What you build under this window is built to take a hit, so make the effort count and don\'t rush it.',
      focus: 'Put sustained, deliberate pressure on your most demanding problem.',
      caution: 'Don\'t let slow progress bait you into a shortcut — frustration is the trap of this window.',
      tags: ['Endurance', 'Strategy', 'Discipline'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Electric Breakthrough',
      summary: 'This window crackles. The unconventional move you just thought of? That\'s the one. Sudden action, radical pivots, and pattern-breaking are all favored right now — the rules you usually follow are the exact thing to break this hour.',
      focus: 'Act on the unconventional insight that just landed — before you talk yourself out of it.',
      caution: 'Don\'t blow things up just to feel the spark — disruption without a target is just damage.',
      tags: ['Breakthrough', 'Innovation', 'Disruption'],
      energyScore: 9,
      stabilityScore: 2,
      spiritualScore: 4,
    },
    Neptune: {
      title: 'Inspired Force',
      summary: 'Your drive is being steered by something quieter than logic right now. This window rewards action taken from intuition and punishes action taken from ego — so before you move, check where the impulse is coming from. When it\'s the deep one, follow it all the way.',
      focus: 'Let the inner signal direct your next move — then commit to it fully.',
      caution: 'Don\'t charge into a fight that isn\'t yours — unclear motives sink this window fast.',
      tags: ['Inspiration', 'Surrender', 'Spiritual Action'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 7,
    },
  },

  // ─────────────────────────────────────────────
  // VENUS HOUR
  // ─────────────────────────────────────────────
  Venus: {
    Mars: {
      title: 'Passionate Magnetism',
      summary: 'What you love is pulling you toward it right now — and this window says reach back. The bold romantic gesture, the direct money move, the pursuit you\'ve been sitting on: all favored this hour. Desire isn\'t passive right now. Neither are you.',
      focus: 'Go after what your heart wants — directly, without the disclaimer.',
      caution: 'Don\'t grip what you\'re drawn to — desire needs air, and possession kills this current.',
      tags: ['Desire', 'Love', 'Passion'],
      energyScore: 8,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Venus: {
      title: 'Pure Harmony',
      summary: 'Everything soft is available to you right now. Your senses are turned up, connection comes easy, and the world is briefly kinder than usual — so stop working the moment and let yourself receive it. No guilt, no analysis. This hour is for taking it in.',
      focus: 'Open up to the beauty, comfort, and pleasure in reach right now — and actually receive it.',
      caution: 'Don\'t let enjoying turn into escaping — indulgence you\'ll regret isn\'t rest.',
      tags: ['Love', 'Beauty', 'Harmony'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Mercury: {
      title: 'Charming Words',
      summary: 'Your words have polish on them right now. Use this window for the message that needs charm instead of force — the pitch, the apology, the ask, the piece of writing that has to land soft. What you say this hour opens doors that pushing wouldn\'t.',
      focus: 'Send the message that needs grace — your delivery is at its smoothest right now.',
      caution: 'Don\'t flatter your way past the truth — charm that dodges honesty costs you later.',
      tags: ['Communication', 'Art', 'Social'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Moon: {
      title: 'Tender Bond',
      summary: 'This is a warm hour — made for care, not drama. Reach for the people who matter with softness: the check-in text, the quiet dinner, the actual listening. Your heart is open and the mood around you is trusting. Deepen something gently while it is.',
      focus: 'Tend the bond that matters most — presence and gentleness do the work this hour.',
      caution: 'Don\'t hide inside the comfort — cozy that never stretches becomes a cage.',
      tags: ['Nurturing', 'Love', 'Comfort'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Radiant Grace',
      summary: 'You\'re magnetic right now, and people can tell. This window amplifies your charm, your creative output, and your visibility all at once — so make the thing, post the thing, walk into the room. The light is flattering this hour. Stand in it.',
      focus: 'Let your warmth and creativity be seen — no hedging, no shrinking.',
      caution: 'Don\'t perform for approval — the pull only works when it\'s actually you.',
      tags: ['Creativity', 'Magnetism', 'Warmth'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 4,
    },
    Vesta: {
      title: 'Devoted Beauty',
      summary: 'This hour turns care into craft. The thing you love deserves your full, precise attention right now — the art made slowly, the gesture done properly, the detail no one else would bother with. What you cherish becomes sacred when you tend it like this.',
      focus: 'Give what you love the patient, exact attention of a craftsperson.',
      caution: 'Don\'t let devotion curdle into control — tending isn\'t gripping.',
      tags: ['Devotion', 'Refinement', 'Sacred'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Union Harmony',
      summary: 'Your partnerships are at their most graceful right now. Use this window to appreciate out loud, to negotiate open-hearted, to strengthen the bond you actually want to keep — romantic or professional. Commitment feels light this hour. Build on that.',
      focus: 'Tell your most important partner what you genuinely value about them — now, not later.',
      caution: 'Don\'t buy peace by erasing yourself — harmony that costs your needs is fake.',
      tags: ['Partnership', 'Commitment', 'Harmony'],
      energyScore: 5,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Pluto: {
      title: 'Magnetic Depth',
      summary: 'What\'s pulling at you right now isn\'t surface-level — it\'s reaching something primal. This window takes relationships, values, and creative work into deeper water, and what shifts down there shifts for real. Let yourself be drawn. Just keep your eyes open.',
      focus: 'Move toward what\'s transforming you — the pull is the point.',
      caution: 'Don\'t confuse intensity with love — obsession wears attraction\'s clothes this hour.',
      tags: ['Intensity', 'Attraction', 'Depth'],
      energyScore: 7,
      stabilityScore: 4,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Abundant Grace',
      summary: 'This is a generous hour — luck, warmth, and plenty are all flowing your way at once. Love, money, and pleasure are expanding right now, and hoarding any of it stalls the current. Take what\'s offered, enjoy it fully, and pass some forward.',
      focus: 'Receive what\'s flowing toward you — and share it while it\'s moving.',
      caution: 'Don\'t tip abundance into waste — more isn\'t the same as better.',
      tags: ['Abundance', 'Joy', 'Blessings'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Mature Love',
      summary: 'This window backs what lasts. Choose the loyal thing over the shiny thing right now — the partnership with a track record, the purchase that holds value, the beauty built on substance. Trust what has already proven itself to you. It\'s telling the truth.',
      focus: 'Put your time and money into what has survived the test — nothing speculative this hour.',
      caution: 'Don\'t go so practical you turn cold — withholding warmth isn\'t wisdom.',
      tags: ['Loyalty', 'Stability', 'Finance'],
      energyScore: 5,
      stabilityScore: 9,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Electric Chemistry',
      summary: 'Attraction is sparking in places you didn\'t plan for. This window brings the unexpected connection, the sudden shift in what you value, the creative jolt from outside your usual lane — and it\'s all live right now. Say yes to the surprising one.',
      focus: 'Follow the surprising connection or creative impulse that just showed up.',
      caution: 'Don\'t trade something stable for a thrill — novelty isn\'t compatibility.',
      tags: ['Excitement', 'Freedom', 'Chemistry'],
      energyScore: 8,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Neptune: {
      title: 'Dream Love',
      summary: 'The line between love and something holier is thin right now. Connection feels destined this hour, beauty feels otherworldly, and your imagination is soaking everything it touches. Create in it, love in it, float in it — just don\'t sign anything while you\'re in it.',
      focus: 'Dream, create, and love without forcing it into a definition right now.',
      caution: 'Don\'t fall for the halo — idealizing someone this hour blinds you to who\'s actually there.',
      tags: ['Romance', 'Dreams', 'Spirituality'],
      energyScore: 5,
      stabilityScore: 4,
      spiritualScore: 8,
    },
  },

  // ─────────────────────────────────────────────
  // MERCURY HOUR
  // ─────────────────────────────────────────────
  Mercury: {
    Mars: {
      title: 'Cutting Edge',
      summary: 'Your thoughts are arriving like blades right now — fast, sharp, decisive. Use this window to cut through the confusion, win the argument that matters, and make the call you\'ve been dragging out. Your mind is a weapon this hour. Point it at something.',
      focus: 'Make the decision you\'ve been delaying — your clarity is peaking right now.',
      caution: 'Don\'t use the blade on people — a snap judgment sent in this window can\'t be recalled.',
      tags: ['Speed', 'Debate', 'Decision'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 2,
    },
    Venus: {
      title: 'Eloquent Grace',
      summary: 'Your language is wearing its finest clothes this hour. The diplomatic email, the artful paragraph, the conversation that builds instead of bruises — all of it flows now. Ideas come out elegant without you forcing them. Write the thing while the polish lasts.',
      focus: 'Use your words to open doors — persuade gently, write beautifully, smooth the rough thing over.',
      caution: 'Don\'t let style eat substance — telling people what they want to hear isn\'t diplomacy.',
      tags: ['Diplomacy', 'Art', 'Communication'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Mercury: {
      title: 'Pure Mind',
      summary: 'This is your intellectual prime time — right now. Analysis, writing, learning, planning: your mind is both swift and precise this hour, and connections between ideas are appearing on their own. Whatever needs your sharpest thinking, do it before this window closes.',
      focus: 'Do your most demanding mental work now — clarity like this doesn\'t hold all day.',
      caution: 'Don\'t think in circles — at some point this hour, analysis has to become a decision.',
      tags: ['Study', 'Analysis', 'Planning'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Moon: {
      title: 'Inner Dialogue',
      summary: 'Your thoughts and feelings are actually talking to each other right now. Use this window to journal, to say the tender thing out loud, to listen to the quiet voice under the noise. Your reasoning has intuition in it this hour — let it in.',
      focus: 'Write down what you\'re feeling right now — the clarity arrives as you put it into words.',
      caution: 'Don\'t reason your feelings out of existence — naming them isn\'t dismissing them.',
      tags: ['Reflection', 'Intuition', 'Writing'],
      energyScore: 5,
      stabilityScore: 5,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Confident Voice',
      summary: 'Your ideas carry weight this hour and people are actually listening. This is the window for the presentation, the pitch, the post, the point you\'ve been waiting to make in the right room. Speak like you mean it — your voice has authority right now.',
      focus: 'Say the thing you\'ve been saving — this hour, it lands.',
      caution: 'Don\'t talk over the room to prove you\'re smart — authority listens too.',
      tags: ['Expression', 'Clarity', 'Confidence'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Vesta: {
      title: 'Precision Mind',
      summary: 'Your concentration has sharpened to a fine point. This is the window for the meticulous work — the detailed plan, the careful study, the document that has to be exactly right. Your mind isn\'t wandering right now. Lock it on the target and keep it there.',
      focus: 'Give your full focus to the most intricate problem in front of you — now, while it holds.',
      caution: 'Don\'t let perfect strangle done — detail serves the goal, not the other way around.',
      tags: ['Focus', 'Study', 'Precision'],
      energyScore: 6,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Juno: {
      title: 'Fair Exchange',
      summary: 'This hour is built for the deal. Negotiation, contract review, mediation, the conversation where both sides need to walk away whole — your words build bridges right now. Aim for the agreement that lasts, not the one that merely wins.',
      focus: 'State your terms plainly and listen just as hard — seal the fair deal this hour.',
      caution: 'Don\'t lawyer the spirit out of the agreement — winning on a technicality loses the partnership.',
      tags: ['Negotiation', 'Balance', 'Agreements'],
      energyScore: 6,
      stabilityScore: 7,
      spiritualScore: 3,
    },
    Pluto: {
      title: 'Deep Investigation',
      summary: 'Your mind wants to dig right now — let it. This window is made for research, psychological insight, and finding the detail everyone else walked past. What\'s been concealed is findable this hour. Follow the thread that doesn\'t add up.',
      focus: 'Look under the surface — the answer you need is in the details others skipped.',
      caution: 'Don\'t weaponize what you uncover — and don\'t let digging tip into paranoia.',
      tags: ['Investigation', 'Truth', 'Depth'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Expansive Learning',
      summary: 'Your mind is reaching outward this hour. Teach the thing you know, read the thing that stretches you, connect the ideas that don\'t normally sit together — big-picture thinking is at its best right now, and it wants to be shared.',
      focus: 'Teach something or learn something that widens your map — this hour rewards both.',
      caution: 'Don\'t preach — a lecture without listening is just noise with confidence.',
      tags: ['Teaching', 'Wisdom', 'Publishing'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Strategic Planning',
      summary: 'Your thinking is sober, precise, and immune to wishful thinking right now — which makes this the window for the real plan. Long-term strategy, honest assessment, the budget, the timeline: build them on facts this hour and they\'ll hold.',
      focus: 'Draft the plan with discipline — say only what\'s essential, promise only what\'s true.',
      caution: 'Don\'t dress pessimism up as realism — killing every idea isn\'t rigor.',
      tags: ['Strategy', 'Planning', 'Structure'],
      energyScore: 6,
      stabilityScore: 9,
      spiritualScore: 2,
    },
    Uranus: {
      title: 'Genius Download',
      summary: 'Brilliant ideas are arriving without warning right now, fully formed and slightly illegal to your usual logic. This window rewrites rules — the radical insight, the unconventional fix, the connection nobody else would make. Catch it before it evaporates.',
      focus: 'Write the breakthrough down right now — it will not wait for you.',
      caution: 'Don\'t torch conventional wisdom for sport — chaos and creativity aren\'t the same thing.',
      tags: ['Innovation', 'Genius', 'Breakthrough'],
      energyScore: 8,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Neptune: {
      title: 'Poetic Mind',
      summary: 'Your imagination has flooded your thinking — in the best way. This window is for the poem, the creative draft, the insight that arrives sideways through a dream instead of a spreadsheet. Logic is soft right now; let the images carry the message.',
      focus: 'Create from your imagination while it\'s this open — trust the message that arrives quietly.',
      caution: 'Don\'t make binding decisions in the fog — save the contracts for a clearer hour.',
      tags: ['Poetry', 'Imagination', 'Vision'],
      energyScore: 5,
      stabilityScore: 3,
      spiritualScore: 8,
    },
  },

  // ─────────────────────────────────────────────
  // MOON HOUR
  // ─────────────────────────────────────────────
  Moon: {
    Mars: {
      title: 'Fierce Protection',
      summary: 'Your protective instinct is fully armed this hour. When something threatens what you love, you\'ll feel it in your body before your mind catches up — and this window says trust that. Defend what\'s yours to defend. The heart isn\'t passive right now.',
      focus: 'Stand up for what matters to you — with conviction and immediate action.',
      caution: 'Don\'t swing at ghosts — check that the threat is real before you strike.',
      tags: ['Protection', 'Instinct', 'Courage'],
      energyScore: 7,
      stabilityScore: 4,
      spiritualScore: 4,
    },
    Venus: {
      title: 'Gentle Comfort',
      summary: 'Sweetness is medicine right now. This window is for the comfort meal, the soft music, the warm embrace, the small pleasure that actually soothes you — take it without apologizing. Soothing yourself this hour isn\'t weakness. It\'s maintenance.',
      focus: 'Nourish yourself and someone you love — tenderness is the assignment this hour.',
      caution: 'Don\'t use comfort to dodge the feeling underneath — soothe it, don\'t bury it.',
      tags: ['Comfort', 'Love', 'Softness'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Mercury: {
      title: 'Reflective Mind',
      summary: 'Your feelings can find words right now — that\'s rarer than you think. Use this window to journal, to talk it through, to name the thing that\'s been sitting on your chest. Understanding comes from naming it this hour, not from analyzing it to death.',
      focus: 'Put language to what\'s moving in you — write it or say it out loud.',
      caution: 'Don\'t intellectualize until you can\'t feel it anymore — words should connect you, not seal you off.',
      tags: ['Reflection', 'Processing', 'Writing'],
      energyScore: 5,
      stabilityScore: 5,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Deep Feeling',
      summary: 'Your sensitivity is at full volume right now. Intuition is speaking clearly, your inner life is vivid, and the boundary between you and everything else is thin. Don\'t fight it and don\'t judge it — this window is for feeling all the way through.',
      focus: 'Trust your intuition this hour and let yourself simply feel — no fixing required.',
      caution: 'Don\'t soak up everyone else\'s weather — some of what you\'re feeling isn\'t yours.',
      tags: ['Intuition', 'Rest', 'Sensitivity'],
      energyScore: 3,
      stabilityScore: 5,
      spiritualScore: 7,
    },
    Sun: {
      title: 'Heart Glow',
      summary: 'Your feelings are visible right now — and that\'s your strength, not your leak. This window lets you be open and strong in the same breath: the heart-led decision, the warm word said publicly, the vulnerability that commands respect instead of pity.',
      focus: 'Say what you feel with warmth — your emotional truth carries this hour.',
      caution: 'Don\'t perform the feeling for an audience — the glow only works when it\'s real.',
      tags: ['Heart', 'Warmth', 'Expression'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Vesta: {
      title: 'Sacred Retreat',
      summary: 'Your inner flame wants quiet right now. Step out of the noise this hour — the solitude, the bath, the unplugged evening, the tending of the inner room only you can enter. Healing happens in stillness this window, and you\'ve earned some.',
      focus: 'Make a quiet space and tend yourself in it — renewal is the work this hour.',
      caution: 'Don\'t retreat so deep you vanish on the people who need you — the door stays unlocked.',
      tags: ['Retreat', 'Devotion', 'Care'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 8,
    },
    Juno: {
      title: 'Bonded Hearts',
      summary: 'Loyalty is felt this hour, not signed. Closeness, shared vulnerability, the quiet certainty of belonging to someone — that\'s what this window deepens. Show up in person, put the phone down, and let presence do what promises can\'t.',
      focus: 'Be emotionally available to your person right now — presence is the proof.',
      caution: 'Don\'t hand your whole emotional weight to your partner — leaning isn\'t collapsing.',
      tags: ['Bonding', 'Loyalty', 'Closeness'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Pluto: {
      title: 'Emotional Depths',
      summary: 'Something buried is surfacing this hour — the old wound, the unprocessed grief, the memory that picked now to knock. It\'s uncomfortable on purpose. Meet it with courage in this window and it heals; shove it back down and it books another appointment.',
      focus: 'Let what\'s rising rise — be honest with yourself and it turns into healing.',
      caution: 'Don\'t set up camp in the pain — feel it, then move it toward resolution.',
      tags: ['Catharsis', 'Depth', 'Transformation'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 6,
    },
    Jupiter: {
      title: 'Hopeful Heart',
      summary: 'Optimism is warming you from the inside right now, and it\'s not naive — it\'s fuel. This window is for emotional generosity: the encouraging word, the faith that things work out, the warmth you\'ve got extra of today. Someone near you needs it. Spend it.',
      focus: 'Let hope lead this hour — and give your warmth away freely.',
      caution: 'Don\'t paste positivity over real pain — hope that skips grief isn\'t healing anything.',
      tags: ['Hope', 'Healing', 'Generosity'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 6,
    },
    Saturn: {
      title: 'Steady Emotions',
      summary: 'This hour asks for your emotional spine. Feel the difficult thing fully — and respond like the adult you\'ve become. Restraint right now isn\'t suppression; it\'s the strength to hold a hard feeling without letting it drive. You can do both. This window proves it.',
      focus: 'Feel deeply, respond maturely — that\'s the whole assignment this hour.',
      caution: 'Don\'t mistake numb for strong — containment with no feeling in it is just repression.',
      tags: ['Maturity', 'Stability', 'Restraint'],
      energyScore: 4,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Uranus: {
      title: 'Emotional Awakening',
      summary: 'Your moods are shifting fast right now — and inside one of those shifts is a real insight about what you actually feel. This window breaks old emotional patterns loose. When the surprising realization lands, don\'t flinch. That\'s the one you keep.',
      focus: 'Catch the emotional insight that arrives as a jolt — it\'s freeing something you outgrew.',
      caution: 'Don\'t make permanent moves on a temporary feeling — let the shock settle first.',
      tags: ['Awakening', 'Surprise', 'Insight'],
      energyScore: 6,
      stabilityScore: 2,
      spiritualScore: 5,
    },
    Neptune: {
      title: 'Psychic Flow',
      summary: 'The veil is thin for you right now. Your empathy is oceanic, your dreams are loud, and your inner senses are picking up things your logic can\'t explain. Stop explaining. This window is for receiving — the image, the feeling, the whisper. Write down what comes.',
      focus: 'Trust the impressions arriving right now — record them before the veil closes.',
      caution: 'Don\'t drown in other people\'s feelings — and don\'t label every fantasy an omen.',
      tags: ['Psychic', 'Dreams', 'Surrender'],
      energyScore: 3,
      stabilityScore: 3,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // SUN HOUR
  // ─────────────────────────────────────────────
  Sun: {
    Mars: {
      title: 'Heroic Action',
      summary: 'This is your hero hour. Step forward, take command, move decisively — and let it be seen. Your energy is contagious right now and your authority gets earned in real time, through doing. The moment is watching. Give it something to watch.',
      focus: 'Lead by visible example — take the action others are waiting for someone to take.',
      caution: 'Don\'t chase glory over the outcome — bravado that costs your people isn\'t leadership.',
      tags: ['Leadership', 'Courage', 'Action'],
      energyScore: 9,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Venus: {
      title: 'Radiant Charm',
      summary: 'You\'re glowing right now and it\'s not your imagination — people are drawn to you this hour. Creativity, warmth, and personal magnetism are all amplified, so make the art, make the move, make the impression. The light is on you. Use it.',
      focus: 'Create something beautiful and let your magnetism work — no forcing needed.',
      caution: 'Don\'t hang your worth on the applause — the glow is yours whether they clap or not.',
      tags: ['Charm', 'Creativity', 'Beauty'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 4,
    },
    Mercury: {
      title: 'Brilliant Voice',
      summary: 'Your intellect and your confidence just linked arms. This window is for the pitch, the presentation, the conversation where your idea has to land with impact — your mind is sharp and your delivery is commanding right now. Take the mic.',
      focus: 'Say what needs saying — with full clarity and zero apology.',
      caution: 'Don\'t showboat — talking over people to prove a point loses the room you just won.',
      tags: ['Expression', 'Clarity', 'Authority'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 3,
    },
    Moon: {
      title: 'Luminous Heart',
      summary: 'Your feelings are lighting you up right now instead of hiding you. This window merges heart and visibility — nurture openly, care out loud, let the warmth show. People feel safe around you this hour. That\'s a power. Use it deliberately.',
      focus: 'Let your open heart be the light in the room — someone near you needs exactly that.',
      caution: 'Don\'t hand raw vulnerability to an audience that hasn\'t earned it.',
      tags: ['Heart', 'Radiance', 'Nurturing'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Full Radiance',
      summary: 'Peak you. Maximum visibility, creative authority, and confidence that doesn\'t wobble — all live right now. The spotlight is on and it\'s actually yours this hour, so claim the recognition, ship the work, stand at full height. This is the window you save the big reveal for.',
      focus: 'Step fully into who you are and let it be witnessed — now.',
      caution: 'Don\'t let the light blind you — arrogance is this hour\'s only real enemy.',
      tags: ['Power', 'Recognition', 'Vitality'],
      energyScore: 9,
      stabilityScore: 6,
      spiritualScore: 4,
    },
    Vesta: {
      title: 'Sacred Purpose',
      summary: 'Your purpose is unusually clear right now, and your discipline is what\'s making you shine. This window rewards leadership that serves something bigger than your ego — the devoted work, done visibly, for the reason you started. Realign to that and glow.',
      focus: 'Do the work that serves your deepest purpose — and let the alignment show.',
      caution: 'Don\'t martyr yourself to the mission — duty without joy burns the temple down.',
      tags: ['Purpose', 'Dedication', 'Leadership'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Partnership Light',
      summary: 'Your partnership deserves the spotlight this hour. Celebrate it publicly, lead together, take shared pride in what the two of you built — the bond is a source of strength right now, not a private footnote. Let people see what you\'ve made together.',
      focus: 'Honor your partnership out loud and lead as a unit this hour.',
      caution: 'Don\'t compete with your partner for the spotlight — it\'s big enough for two.',
      tags: ['Partnership', 'Balance', 'Leadership'],
      energyScore: 6,
      stabilityScore: 7,
      spiritualScore: 4,
    },
    Pluto: {
      title: 'Magnetic Truth',
      summary: 'The mask is slipping this hour — on purpose. Who you really are underneath the persona is coming into the light, and pretending is officially more expensive than honesty. It feels like exposure; it\'s actually liberation. Show the real thing.',
      focus: 'Own the truth of who you are — including the parts you usually crop out.',
      caution: 'Don\'t use your power to intimidate — visibility is for illumination, not leverage.',
      tags: ['Truth', 'Power', 'Magnetism'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Golden Blessing',
      summary: 'Confidence and opportunity just aligned for you — this is the rare hour where the room tilts in your favor. Recognition, reward, growth on several fronts at once. The thing that\'s been building has its moment right now. Walk in and receive it.',
      focus: 'Say yes to the opportunity that\'s been building — this window is what it was building toward.',
      caution: 'Don\'t coast on the luck — the tailwind still needs you pedaling.',
      tags: ['Success', 'Blessing', 'Growth'],
      energyScore: 9,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Earned Authority',
      summary: 'The authority you\'re carrying right now isn\'t borrowed — you built it. This window is for mature, long-game leadership: the serious decision, the standard you hold, the weight you carry because you can. People trust you this hour because you did the work. Act like it.',
      focus: 'Accept the weight of leadership and put it toward something that outlasts you.',
      caution: 'Don\'t let the responsibility squeeze the joy out — a grim leader builds grim things.',
      tags: ['Authority', 'Discipline', 'Mastery'],
      energyScore: 7,
      stabilityScore: 9,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Original Fire',
      summary: 'Your uniqueness is demanding airtime right now. This window is for radical self-expression — the weird idea shown proudly, the version of you that refuses to be sanded down. The world hasn\'t seen your unconventional take yet. This hour, show it.',
      focus: 'Express the part of you that won\'t conform — publicly, without apology.',
      caution: 'Don\'t shock people just to watch them flinch — rebellion needs a reason.',
      tags: ['Originality', 'Breakthrough', 'Rebellion'],
      energyScore: 8,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Neptune: {
      title: 'Inspired Glow',
      summary: 'Something larger is moving through you right now. Your creativity has a source beyond your ego this hour, and your presence is softer, stranger, and more magnetic for it. Be the vessel — make what wants to be made through you and don\'t ask it for ID.',
      focus: 'Create from the spiritual current and follow where it pulls — this hour, trust it.',
      caution: 'Don\'t dissolve entirely — stay you, or others will project whatever they want onto the blur.',
      tags: ['Inspiration', 'Vision', 'Spirituality'],
      energyScore: 6,
      stabilityScore: 4,
      spiritualScore: 8,
    },
  },

  // ─────────────────────────────────────────────
  // VESTA HOUR
  // ─────────────────────────────────────────────
  Vesta: {
    Mars: {
      title: 'Disciplined Force',
      summary: 'This window turns hard labor into offering. Take the work you\'re devoted to and hit it with everything — body, will, and full attention. Purification through effort is the assignment this hour, and every rep, page, or task is part of the ritual.',
      focus: 'Attack your most important work at full intensity — it deserves nothing less right now.',
      caution: 'Don\'t force the result or worship your own exhaustion — tired isn\'t the same as done.',
      tags: ['Work', 'Discipline', 'Effort'],
      energyScore: 8,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Venus: {
      title: 'Sacred Beauty',
      summary: 'Beauty isn\'t frivolous this hour — it\'s sacred. Give careful, loving attention to aesthetic detail: the craft, the arrangement, the refinement of something you genuinely value. What you polish with reverence right now holds the reverence.',
      focus: 'Make or tend something beautiful — slowly, properly, with full attention.',
      caution: 'Don\'t chase perfection so hard you can\'t enjoy what\'s already in your hands.',
      tags: ['Beauty', 'Devotion', 'Refinement'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 6,
    },
    Mercury: {
      title: 'Focused Study',
      summary: 'Your mind is a precision instrument right now. This window is built for concentrated study, careful documentation, and planning that requires sustained attention — the deep read, the intentional journal, the work that needs you locked in. Lock in.',
      focus: 'Give undivided attention to the study or plan that matters most — this hour holds you steady.',
      caution: 'Don\'t disappear into the details — keep one eye on why you\'re doing this.',
      tags: ['Study', 'Precision', 'Concentration'],
      energyScore: 6,
      stabilityScore: 8,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Inner Flame',
      summary: 'Your devotion turns inward this hour. Tend your inner life the way you\'d tend a sacred flame — quietly, attentively, releasing what no longer serves and protecting what does. Emotional purification is the work right now, and it\'s done in private.',
      focus: 'Care for your emotional and spiritual well-being with quiet, deliberate attention.',
      caution: 'Don\'t suppress feelings in the name of discipline — tending the flame means feeling its heat.',
      tags: ['Purification', 'Care', 'Devotion'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 8,
    },
    Sun: {
      title: 'Dedicated Purpose',
      summary: 'The work you\'ve been quietly devoted to is earning its moment in the light. This window brings recognition for consistency, not flash — so keep doing the practice exactly as you do it, and let it be seen. You didn\'t chase the spotlight. It found the work.',
      focus: 'Let your disciplined work speak — and stand in the recognition it earned.',
      caution: 'Don\'t start performing for the applause — the practice is the point, not the audience.',
      tags: ['Purpose', 'Focus', 'Direction'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 6,
    },
    Vesta: {
      title: 'Total Devotion',
      summary: 'Complete immersion is available right now — the rare window where nothing exists outside the work. Discipline isn\'t a burden this hour; it\'s the door to mastery. Give yourself fully to your practice and it gives back double. Close the door. Begin.',
      focus: 'Immerse completely in your most sacred task — nothing else exists this hour.',
      caution: 'Don\'t seal yourself in so tightly that life outside the work stops recognizing you.',
      tags: ['Ritual', 'Mastery', 'Discipline'],
      energyScore: 6,
      stabilityScore: 9,
      spiritualScore: 8,
    },
    Juno: {
      title: 'Sacred Commitment',
      summary: 'Loyalty becomes practice this hour. Deepen your commitment — to the partner, the cause, the promise — through conscious, deliberate effort, not sentiment. What you agree to in this window carries the weight of devotion behind it. Mean it.',
      focus: 'Strengthen a commitment through intentional action — do the devoted thing, visibly.',
      caution: 'Don\'t go blind in your loyalty — devotion that can\'t see flaws can\'t protect the bond.',
      tags: ['Commitment', 'Loyalty', 'Sacred'],
      energyScore: 5,
      stabilityScore: 8,
      spiritualScore: 6,
    },
    Pluto: {
      title: 'Deep Purification',
      summary: 'Shadow work is sacred work this hour. Take your discipline into the basement — the pattern you avoid, the corner you don\'t sweep — and face it with focused, unflinching attention. This window is demanding on purpose. What it purifies stays purified.',
      focus: 'Aim your discipline at the shadow that most needs your attention — steadily, without flinching.',
      caution: 'Don\'t let self-examination become self-punishment — you\'re cleaning the room, not burning it.',
      tags: ['Shadow Work', 'Purification', 'Depth'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 7,
    },
    Jupiter: {
      title: 'Devoted Growth',
      summary: 'Discipline is feeding expansion right now. This window rewards sacred study and devoted learning — the practice that compounds, the teacher you take seriously, the growth earned one focused session at a time. Sit down and add to it. It\'s adding up.',
      focus: 'Grow through devoted practice — one disciplined session this hour beats ten scattered ones.',
      caution: 'Don\'t harden into dogma — one path walked deeply still needs windows.',
      tags: ['Growth', 'Study', 'Expansion'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 7,
    },
    Saturn: {
      title: 'Austere Mastery',
      summary: 'No shortcuts exist in this window — and that\'s its gift. Maximum discipline, zero distractions, zero excuses. What you build right now is forged, not assembled, and it will outlast everything you made in a hurry. Pick the hard important thing. Stay until it\'s done.',
      focus: 'Commit to the hardest thing that matters and do not stop until it\'s finished.',
      caution: 'Don\'t confuse severity with virtue — joyless isn\'t the same as serious.',
      tags: ['Mastery', 'Austerity', 'Endurance'],
      energyScore: 6,
      stabilityScore: 10,
      spiritualScore: 6,
    },
    Uranus: {
      title: 'Radical Focus',
      summary: 'Break the rules of your own practice this hour. An unconventional method, a strange schedule, a backwards approach — this window is where discipline and innovation collide and produce something extraordinary. The routine got you here. The experiment gets you further.',
      focus: 'Try the unconventional approach on your most disciplined work — right now.',
      caution: 'Don\'t torch what works for novelty — test the new method before you trust it.',
      tags: ['Innovation', 'Focus', 'Breakthrough'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 6,
    },
    Neptune: {
      title: 'Mystical Service',
      summary: 'Effort dissolves into offering this hour. Pray, meditate, serve — the boundary between your work and your worship is gone right now, and personal willpower isn\'t the engine anymore. Surrender is. Let the practice carry you instead of the reverse.',
      focus: 'Let your service become prayer — surrender the outcome and do the sacred thing.',
      caution: 'Don\'t float away entirely — the mystical still has to land somewhere practical.',
      tags: ['Prayer', 'Surrender', 'Mysticism'],
      energyScore: 4,
      stabilityScore: 5,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // JUNO HOUR
  // ─────────────────────────────────────────────
  Juno: {
    Mars: {
      title: 'Active Alliance',
      summary: 'Your partnerships need action right now, not politeness. Defend the bond, fight for fairness, bring direct energy to the dynamic that\'s been drifting — this window punishes passivity in relationships. Stand up for what your alliances need. Today, out loud.',
      focus: 'Take decisive action for your most important alliance — protect it or push it forward.',
      caution: 'Don\'t turn the negotiation into combat — you\'re fighting for the bond, not against your partner.',
      tags: ['Partnership', 'Action', 'Defense'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 3,
    },
    Venus: {
      title: 'Union in Beauty',
      summary: 'Harmony is moving through your partnerships this hour. Appreciation, shared beauty, mutual warmth — commitment feels natural right now instead of heavy. Use the window: say the loving thing, plan the shared thing, enjoy what you\'ve built together.',
      focus: 'Celebrate your partnership openly — appreciation said out loud compounds this hour.',
      caution: 'Don\'t paper over the real issue with pleasantries — sweet isn\'t the same as solved.',
      tags: ['Love', 'Harmony', 'Union'],
      energyScore: 5,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Mercury: {
      title: 'Clear Agreements',
      summary: 'This is the hour for the deal that lasts. Negotiate clearly, review the contract, mediate the dispute — words build durable structures between people right now. The goal isn\'t to win. It\'s to walk away with an agreement both sides will still honor next year.',
      focus: 'Lay out your terms plainly and listen with equal care — close the fair agreement now.',
      caution: 'Don\'t win on a technicality — gutting the spirit of the deal breaks it later.',
      tags: ['Negotiation', 'Contracts', 'Communication'],
      energyScore: 6,
      stabilityScore: 7,
      spiritualScore: 3,
    },
    Moon: {
      title: 'Bonded Care',
      summary: 'Your bond deepens through care this hour, not contracts. Presence, shared vulnerability, the sense of being safely held — that\'s what strengthens the union right now. Show your person they\'re safe with you. That\'s the whole assignment.',
      focus: 'Make your partner feel emotionally safe with you — presence over promises this hour.',
      caution: 'Don\'t dissolve into the relationship — closeness works best with your self intact.',
      tags: ['Loyalty', 'Care', 'Bonding'],
      energyScore: 4,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Partnership Pride',
      summary: 'Your union steps into the light this hour. Celebrate the partnership publicly, lead together, take visible pride in what you\'ve built as a pair — the bond is a source of confidence right now, and hiding it undersells you both.',
      focus: 'Show your partnership off and lead together — shared purpose, visible pride.',
      caution: 'Don\'t elbow your partner out of the frame — the spotlight holds two.',
      tags: ['Pride', 'Leadership', 'Partnership'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 3,
    },
    Vesta: {
      title: 'Devoted Union',
      summary: 'Commitment gets tended like a flame this hour — with consistency, attention, and reverence. Don\'t just feel loyal; do something loyal. The deliberate act of devotion you make in this window is worth a hundred warm intentions.',
      focus: 'Invest focused, intentional effort into your most important commitment — today, concretely.',
      caution: 'Don\'t let the bond become a chore list — devotion should feed you both, not drain you.',
      tags: ['Devotion', 'Commitment', 'Sacred'],
      energyScore: 5,
      stabilityScore: 9,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Perfect Balance',
      summary: 'Pure partnership energy, right now. Alliances, formal agreements, the precise balance of giving and receiving — every exchange this hour gets measured by fairness, and every deal carries mutual respect or it doesn\'t close. Weigh both sides. Then commit.',
      focus: 'Seek true equilibrium in your agreements — honor both sides fully before you sign on.',
      caution: 'Don\'t audit fairness into paralysis — at some point balanced enough is balanced.',
      tags: ['Balance', 'Alliance', 'Contract'],
      energyScore: 5,
      stabilityScore: 9,
      spiritualScore: 4,
    },
    Pluto: {
      title: 'Karmic Bond',
      summary: 'Your partnership is in the deep end this hour. Power dynamics are surfacing, hidden truths are coming up, and the bond will either transform or crack — that\'s the test. Face what\'s real between you right now. What survives this window is the real thing.',
      focus: 'Name the truth about your partnership dynamics — courage now saves the bond later.',
      caution: 'Don\'t use the bond as leverage — control disguised as love still corrodes.',
      tags: ['Karma', 'Depth', 'Transformation'],
      energyScore: 7,
      stabilityScore: 4,
      spiritualScore: 6,
    },
    Jupiter: {
      title: 'Blessed Union',
      summary: 'Fortune is favoring your alliances right now. The right partnership multiplies everything this hour — the deal, the collaboration, the marriage of strengths. Growth comes through joining forces, so reach out to the person who doubles your reach. Now\'s the window.',
      focus: 'Strengthen or seek the alliance that multiplies you — partnership is the growth channel this hour.',
      caution: 'Don\'t assume every partner shares your vision — check before you overcommit.',
      tags: ['Blessing', 'Growth', 'Partnership'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Tested Loyalty',
      summary: 'Your commitments are being weighed this hour — by pressure, delay, and difficulty. The bonds that hold under this window\'s load are the ones worth keeping. Honor the promise even though it\'s hard right now. That\'s where loyalty stops being a word.',
      focus: 'Keep the commitment precisely because it\'s difficult — this is where loyalty gets proven.',
      caution: 'Don\'t stay chained to a bond that\'s become a prison — obligation isn\'t loyalty.',
      tags: ['Duty', 'Loyalty', 'Endurance'],
      energyScore: 5,
      stabilityScore: 10,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Liberated Bond',
      summary: 'Your partnership is allowed to break its own rules this hour. Redefine the terms, surprise each other, let the commitment evolve past its original shape — the relationships that survive this window do it by changing. Rigid ones feel the strain. Choose evolution.',
      focus: 'Let the partnership grow beyond its original form — renegotiate what needs renegotiating.',
      caution: 'Don\'t wave the freedom flag to dodge intimacy — space and avoidance aren\'t the same.',
      tags: ['Freedom', 'Innovation', 'Partnership'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Neptune: {
      title: 'Soul Contract',
      summary: 'Your connection feels destined this hour — bigger than logistics, older than the day you met. Compassion is deepening the commitment right now and the bond is operating at soul level. Trust that dimension of it. Just keep one eye open while you do.',
      focus: 'Honor the spiritual depth of your bond — lead with compassion this hour.',
      caution: 'Don\'t idealize your partner into fiction — love the person, not the halo you gave them.',
      tags: ['Soul', 'Compassion', 'Idealism'],
      energyScore: 4,
      stabilityScore: 4,
      spiritualScore: 9,
    },
  },

  // ─────────────────────────────────────────────
  // PLUTO HOUR
  // ─────────────────────────────────────────────
  Pluto: {
    Mars: {
      title: 'Total Force',
      summary: 'Raw power is moving through this hour — survival instinct, will, the force that doesn\'t negotiate. The confrontation you can\'t avoid is best faced right now, with everything you have. Nothing about this window is gentle. All of it is real.',
      focus: 'Bring your full power to the confrontation that can\'t be dodged — now, deliberately.',
      caution: 'Don\'t let rage drive — a battle fought for ego costs you the war that matters.',
      tags: ['Power', 'Survival', 'Force'],
      energyScore: 10,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Venus: {
      title: 'Magnetic Obsession',
      summary: 'Desire is running at its most intense frequency right now. What\'s pulling at you this hour touches something primal — love, beauty, value experienced at a depth that can consume you if you let it. Honor the pull. Keep your feet.',
      focus: 'Feel the full depth of your desire without handing it the steering wheel.',
      caution: 'Don\'t confuse possession with love — gripping tighter isn\'t going deeper.',
      tags: ['Obsession', 'Magnetism', 'Desire'],
      energyScore: 7,
      stabilityScore: 4,
      spiritualScore: 5,
    },
    Mercury: {
      title: 'Piercing Truth',
      summary: 'Your mind is cutting to the bone this hour. Investigation, psychological insight, the analysis that sees what everyone else politely ignores — no secret near you is safe right now. Ask the question no one wants asked. Then say what you find.',
      focus: 'Dig into what\'s been hidden and say the truth others keep dodging.',
      caution: 'Don\'t turn insight into a weapon — knowing someone\'s soft spot doesn\'t mean pressing it.',
      tags: ['Investigation', 'Truth', 'Psychology'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Emotional Purge',
      summary: 'The floor of your emotional life is cracking open this hour — buried feelings, old pain, the grief that never got its turn. It\'s rising because it\'s ready to leave. Let it move through you in this window. Healing starts exactly where the denial stops.',
      focus: 'Let the release happen — what\'s surfacing right now has waited long enough.',
      caution: 'Don\'t spray the pain onto bystanders — this purge is yours to move through, not assign.',
      tags: ['Catharsis', 'Healing', 'Depth'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 6,
    },
    Sun: {
      title: 'Exposed Power',
      summary: 'Who you are under the persona is coming into the light this hour — whether you schedule it or not. It feels like exposure; it functions like liberation. Authenticity is the only strategy that works in this window. Drop the mask before it\'s pulled.',
      focus: 'Let the old mask fall — walk into this hour as the person you actually are.',
      caution: 'Don\'t use the intensity to intimidate — power that needs fear isn\'t power.',
      tags: ['Truth', 'Power', 'Visibility'],
      energyScore: 8,
      stabilityScore: 4,
      spiritualScore: 5,
    },
    Vesta: {
      title: 'Shadow Discipline',
      summary: 'Sacred intensity meets your inner basement this hour. Take disciplined, unflinching attention into the deepest part of yourself — the pattern, the wound, the thing you manage instead of face. The work is heavy right now. It\'s also the one that changes you.',
      focus: 'Apply steady discipline to your hardest inner work — focused, unflinching, now.',
      caution: 'Don\'t dress self-punishment up as practice — the goal is clean, not bleeding.',
      tags: ['Shadow Work', 'Purification', 'Ritual'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 7,
    },
    Juno: {
      title: 'Transforming Bonds',
      summary: 'Your relationship is in the crucible this hour. Truth-telling, reckoning, the death of what the bond was so it can become what it needs to be — that\'s the work of this window. Engage honestly and deep. What comes out the other side is stronger or gone.',
      focus: 'Let the bond evolve through honest, deep engagement — hold nothing back that matters.',
      caution: 'Don\'t blow up the relationship to dodge your own transformation — check whose work this is.',
      tags: ['Karma', 'Healing', 'Partnership'],
      energyScore: 6,
      stabilityScore: 4,
      spiritualScore: 6,
    },
    Pluto: {
      title: 'Full Metamorphosis',
      summary: 'Total transformation is underway right now — endings and beginnings compressed into one window. Something in your life is finishing whether you approve or not, and something else is already starting underneath it. Stop gripping the old shape. Let it complete.',
      focus: 'Release what\'s already ending — the rebirth has started and it needs your hands free.',
      caution: 'Don\'t cling to what has already ended — and don\'t call random destruction progress.',
      tags: ['Rebirth', 'Intensity', 'Transformation'],
      energyScore: 8,
      stabilityScore: 2,
      spiritualScore: 7,
    },
    Jupiter: {
      title: 'Empowered Growth',
      summary: 'Deep change is creating massive room right now. The truth you faced is enlarging your reach this hour — the willingness to look at the dark is exactly what\'s unlocking the opportunity. Let the transformation fund the expansion. It\'s paying out.',
      focus: 'Let your deepest change power your biggest move — the two are connected this hour.',
      caution: 'Don\'t cash power in for pure self-interest — influence used carelessly comes back with interest.',
      tags: ['Empowerment', 'Growth', 'Truth'],
      energyScore: 9,
      stabilityScore: 4,
      spiritualScore: 6,
    },
    Saturn: {
      title: 'Karmic Pressure',
      summary: 'Reality is pressing down with transformative weight this hour. Old foundations are crumbling so real ones can go in — the restructuring is not optional, only your posture toward it is. Bear what\'s yours to bear right now. What survives this window sits on bedrock.',
      focus: 'Accept the restructuring and start building on what\'s still solid.',
      caution: 'Don\'t go rigid under the load — the pressure is shaping you, not flattening you.',
      tags: ['Pressure', 'Endurance', 'Restructuring'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Uranus: {
      title: 'Radical Rebirth',
      summary: 'The ground is moving under everything right now. Sudden transformation, limits detonating, change you can\'t predict or manage — this window doesn\'t do gradual. You can\'t stop what\'s begun. You can steer it. Grab the wheel, not the past.',
      focus: 'Ride the radical change — direct it toward what matters instead of resisting it.',
      caution: 'Don\'t torch it all for the thrill — chaos isn\'t the same as liberation.',
      tags: ['Revolution', 'Awakening', 'Destruction'],
      energyScore: 9,
      stabilityScore: 1,
      spiritualScore: 6,
    },
    Neptune: {
      title: 'Mystical Abyss',
      summary: 'You\'re at the edge of something bottomless this hour — ego thinning, psychic volume up, forces moving that don\'t answer to comprehension. The boundary between you and everything is dissolving right now. Don\'t fight the water. Float, and let it change you.',
      focus: 'Drop the need to understand — let the mystery do its work on you this hour.',
      caution: 'Don\'t lose your tether — touch ground, eat something, come back with both feet.',
      tags: ['Mystery', 'Dissolution', 'Psychic'],
      energyScore: 5,
      stabilityScore: 2,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // JUPITER HOUR
  // ─────────────────────────────────────────────
  Jupiter: {
    Mars: {
      title: 'Bold Fortune',
      summary: 'Adventure is calling this hour and it isn\'t whispering. Courageous expansion, the ambitious launch, the risk you\'ve been circling — bravery is being rewarded right now, specifically yours. Charge at the big thing while the window\'s open.',
      focus: 'Take the bold leap your instincts keep pointing at — this hour backs you.',
      caution: 'Don\'t gamble past your means — recklessness in a lucky hour is still recklessness.',
      tags: ['Adventure', 'Courage', 'Expansion'],
      energyScore: 9,
      stabilityScore: 5,
      spiritualScore: 4,
    },
    Venus: {
      title: 'Abundant Love',
      summary: 'Blessings are flowing through beauty and connection right now. Affection is generous this hour, attraction is fortunate, and there\'s genuinely enough to go around — so give freely, receive without flinching, and let the pleasure be uncomplicated for once.',
      focus: 'Open up to the love and beauty around you — receive it and pass it on.',
      caution: 'Don\'t take the generosity for granted — and don\'t eat the whole hour in one bite.',
      tags: ['Abundance', 'Love', 'Blessings'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Mercury: {
      title: 'Wise Teaching',
      summary: 'Your knowledge wants an audience this hour. Teach, publish, explain the thing you understand better than most — big learning and broad connection are at their strongest right now, and the ideas you link up in this window become actual wisdom.',
      focus: 'Share what you know generously — and grab the lesson that stretches your view.',
      caution: 'Don\'t pontificate — opinion delivered loudly still isn\'t wisdom.',
      tags: ['Teaching', 'Wisdom', 'Publishing'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Healing Hope',
      summary: 'Emotional sunlight after rain — that\'s this hour. Healing optimism, protective generosity, real faith that things work out. Your heart is buoyant right now and your warmth has surplus. Someone in your orbit needs it today. You know who. Send it.',
      focus: 'Lead with hope and hand your warmth out freely this hour.',
      caution: 'Don\'t hand out hope as a way to skip someone\'s grief — including your own.',
      tags: ['Hope', 'Healing', 'Faith'],
      energyScore: 6,
      stabilityScore: 6,
      spiritualScore: 6,
    },
    Sun: {
      title: 'Golden Success',
      summary: 'You\'re exactly where the tailwind is right now. Recognition, growth, and the quiet sense of being in the right place at the right time have all converged on this hour. Success moves toward you instead of away for once — meet it in motion, not on the couch.',
      focus: 'Claim the recognition and growth that\'s been building — this hour is what it built toward.',
      caution: 'Don\'t mistake the tailwind for the engine — luck sustains no one who stops working.',
      tags: ['Success', 'Recognition', 'Growth'],
      energyScore: 9,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Vesta: {
      title: 'Sacred Expansion',
      summary: 'Your growth turns devotional this hour. Focused study, disciplined practice, the deliberate deepening of what you\'re building — expansion isn\'t scattered right now, it\'s concentrated and meaningful. One devoted session in this window outproduces a scattered week.',
      focus: 'Grow through dedicated practice — let discipline multiply the blessing this hour.',
      caution: 'Don\'t squeeze the growth into too narrow a channel — devotion needs some sky.',
      tags: ['Growth', 'Devotion', 'Study'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 7,
    },
    Juno: {
      title: 'Fortunate Alliance',
      summary: 'Joining forces beats going solo this hour — decisively. The beneficial agreement, the collaboration that clicks, the right alliance at the right time: partnership is where the luck is concentrated right now. Make the call to the person you\'re better with.',
      focus: 'Reach out to the partner who multiplies your growth — the alliance is the opportunity.',
      caution: 'Don\'t sign into a lopsided deal — count what each side actually brings.',
      tags: ['Partnership', 'Fortune', 'Growth'],
      energyScore: 7,
      stabilityScore: 7,
      spiritualScore: 5,
    },
    Pluto: {
      title: 'Deep Empowerment',
      summary: 'Your growth is coming from the deep end this hour, not the shallow one. Face the truth, look at the shadow, and expansion follows — the kind that actually holds. What you\'re willing to confront right now converts directly into strength. Confront accordingly.',
      focus: 'Grow from the deepest place available — the hard truth is the growth vein this hour.',
      caution: 'Don\'t wield the new leverage carelessly — power without ethics shrinks you back.',
      tags: ['Empowerment', 'Expansion', 'Truth'],
      energyScore: 9,
      stabilityScore: 4,
      spiritualScore: 6,
    },
    Jupiter: {
      title: 'Maximum Blessing',
      summary: 'Doors are opening faster than you can walk through them right now. Peak growth, outsized luck, opportunity stacking on opportunity — this hour is the universe being loud about its generosity. Don\'t try to take every door. Pick the best one and walk through it well.',
      focus: 'Receive what\'s arriving and choose the single best opportunity — deliberately.',
      caution: 'Don\'t let abundance turn into greed or sprawl — stewardship is the skill this hour.',
      tags: ['Luck', 'Abundance', 'Opportunity'],
      energyScore: 8,
      stabilityScore: 6,
      spiritualScore: 7,
    },
    Saturn: {
      title: 'Measured Growth',
      summary: 'This hour grows things that last. Responsible expansion, solid foundations, and the maturity to decline what doesn\'t serve the long game — that\'s the winning shape right now. Say no to two shiny things and yes to the durable one. Build it properly.',
      focus: 'Expand steadily toward your most enduring goal — structure first, speed second.',
      caution: 'Don\'t strangle the growth with caution — and don\'t sprint off without the plan.',
      tags: ['Strategy', 'Growth', 'Discipline'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Uranus: {
      title: 'Visionary Luck',
      summary: 'Opportunity is striking like lightning right now — sudden, sideways, and not on your calendar. The unexpected door that just appeared is this window\'s whole point. The unconventional path is carrying real luck this hour. Follow it while it\'s glowing.',
      focus: 'Chase the unexpected opportunity that just showed up — it\'s the one that matters.',
      caution: 'Don\'t sprint after every shiny thing — one lightning bolt, not a light show.',
      tags: ['Breakthrough', 'Vision', 'Opportunity'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Neptune: {
      title: 'Divine Grace',
      summary: 'Blessings are arriving from beyond the visible this hour. Your faith is deepening, your compassion is widening, and the sense of being guided isn\'t your imagination right now — it\'s the weather. Grace is the word for this window. Stand in it and say thanks.',
      focus: 'Trust the guidance you can\'t see — surrender to the grace moving through this hour.',
      caution: 'Don\'t float off the ground — grace still expects you to answer your emails.',
      tags: ['Grace', 'Faith', 'Spirituality'],
      energyScore: 5,
      stabilityScore: 5,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // SATURN HOUR
  // ─────────────────────────────────────────────
  Saturn: {
    Mars: {
      title: 'Forged Discipline',
      summary: 'This hour forges. Strength plus patience, applied to the work that has to outlast you — that\'s the assignment right now. The process will demand everything, and everything you give gets baked into the result. Push steady. What you\'re making is permanent.',
      focus: 'Apply full strength to the work requiring the most endurance — steadily, without shortcuts.',
      caution: 'Don\'t let frustration sell you a shortcut — forcing what needs time breaks it.',
      tags: ['Endurance', 'Strategy', 'Effort'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 3,
    },
    Venus: {
      title: 'Loyal Value',
      summary: 'This window backs the unbreakable version of love and money. The stable partnership, the disciplined budget, the beauty that comes from having weathered storms together — value what has proven itself to you. It\'s the honest signal this hour.',
      focus: 'Invest in the relationships and assets that have already earned your trust.',
      caution: 'Don\'t guard your heart and wallet so hard you starve them both.',
      tags: ['Loyalty', 'Finance', 'Maturity'],
      energyScore: 5,
      stabilityScore: 9,
      spiritualScore: 3,
    },
    Mercury: {
      title: 'Structured Mind',
      summary: 'Your thinking is load-bearing right now. This hour is for the serious plan, the realistic assessment, the communication that carries weight — every word counts in this window, and every plan should already know what could go wrong. Build the strategy on facts.',
      focus: 'Plan with discipline — commit to paper only what you\'ll stand behind.',
      caution: 'Don\'t let realism rot into negativity — stress-testing ideas isn\'t killing them.',
      tags: ['Planning', 'Structure', 'Realism'],
      energyScore: 6,
      stabilityScore: 9,
      spiritualScore: 2,
    },
    Moon: {
      title: 'Steady Heart',
      summary: 'You can hold the hard feeling without dropping it or drowning in it — that\'s this hour\'s specific strength. Emotional maturity is both required and rewarded right now. Contain without suppressing. Endure without hardening. You\'ve trained for this window.',
      focus: 'Meet the difficult emotion with patience — respond from your stable center.',
      caution: 'Don\'t confuse cold with composed — numbness isn\'t maturity, it\'s absence.',
      tags: ['Maturity', 'Containment', 'Stability'],
      energyScore: 4,
      stabilityScore: 8,
      spiritualScore: 4,
    },
    Sun: {
      title: 'Crowned Authority',
      summary: 'The crown you\'re wearing this hour was earned, not gifted — visible authority backed by sustained effort. People trust you right now because you carry what others put down. So carry it: make the serious call, hold the standard, lead with full weight.',
      focus: 'Accept the responsibility of your position and lead with integrity — now.',
      caution: 'Don\'t rule by control — and don\'t let the weight grind the joy out of what you built.',
      tags: ['Authority', 'Responsibility', 'Vision'],
      energyScore: 7,
      stabilityScore: 9,
      spiritualScore: 3,
    },
    Vesta: {
      title: 'Master Craftsman',
      summary: 'This is the mastery hour. Austere, focused work — the kind that produces excellence through sheer commitment, where sacred duty and practical effort become the same motion. Whatever your craft is, this window is when you honor it properly. Sit down. Begin.',
      focus: 'Pursue mastery through unwavering discipline — do the craft the way it deserves.',
      caution: 'Don\'t sacrifice rest and human contact on perfection\'s altar — masters sleep too.',
      tags: ['Mastery', 'Duty', 'Discipline'],
      energyScore: 6,
      stabilityScore: 10,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Binding Oath',
      summary: 'What you commit to this hour is iron. Serious agreements, tested loyalty, the formal bonds that define lasting partnerships — every promise made in this window carries weight and consequence. So choose slowly, sign deliberately, and honor completely.',
      focus: 'Make only the commitments you\'ll keep when it gets hard — then keep them.',
      caution: 'Don\'t swear an oath out of obligation — a promise without intention behind it is a debt.',
      tags: ['Commitment', 'Duty', 'Loyalty'],
      energyScore: 5,
      stabilityScore: 10,
      spiritualScore: 3,
    },
    Pluto: {
      title: 'Karmic Reckoning',
      summary: 'Old structures are facing their audit this hour. Debts come due, outdated foundations give way, and the only road forward runs through letting go of what no longer holds. It\'s uncomfortable and overdue. Release what\'s condemned. Reinforce what passed inspection.',
      focus: 'Accept what reality is demanding — release what can\'t be saved and rebuild from there.',
      caution: 'Don\'t prop up a structure that\'s already condemned — loyalty to rubble buries you.',
      tags: ['Karma', 'Pressure', 'Restructuring'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 5,
    },
    Jupiter: {
      title: 'Steady Ascent',
      summary: 'Growth takes the stairs this hour — and the stairs actually get you there. Structured expansion, mature wisdom, success assembled slowly enough to be permanent. It won\'t look flashy right now. Check back in a year and see who\'s still standing.',
      focus: 'Advance through patient, repeated effort — small commitments, kept, compounding.',
      caution: 'Don\'t read slow as failing — quitting the stairs for the elevator is how this window gets wasted.',
      tags: ['Growth', 'Wisdom', 'Structure'],
      energyScore: 7,
      stabilityScore: 8,
      spiritualScore: 5,
    },
    Saturn: {
      title: 'Iron Will',
      summary: 'Nothing is easy this hour — and everything you build in it is permanent. Maximum discipline meets maximum endurance right now: order, accountability, commitment with no soft edges. The reward for not quitting through this window is immense. So don\'t.',
      focus: 'Commit completely to the hardest work in front of you — and refuse to fold.',
      caution: 'Don\'t go so rigid you crack — and don\'t mistake harshness for strength.',
      tags: ['Endurance', 'Order', 'Commitment'],
      energyScore: 6,
      stabilityScore: 10,
      spiritualScore: 3,
    },
    Uranus: {
      title: 'Tense Reform',
      summary: 'Structure and freedom are grinding against each other this hour — productively. The old system has to evolve, and the tension you feel right now is exactly what produces the breakthrough that\'s both radical and durable. Reform it; don\'t raze it.',
      focus: 'Hold structure and change in the same hand — reform what exists instead of choosing sides.',
      caution: 'Don\'t cling to the old rules out of fear — and don\'t shred them out of impatience.',
      tags: ['Reform', 'Tension', 'Innovation'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 4,
    },
    Neptune: {
      title: 'Grounded Spirit',
      summary: 'Your faith gets field-tested this hour — and that\'s good for it. Intuition meets reality, prayer meets practice, and spiritual insight has to prove itself against actual life right now. The insight that survives contact is the one worth keeping. Test it in daylight.',
      focus: 'Take one spiritual insight and apply it to a concrete, real-world problem today.',
      caution: 'Don\'t write off the mystical as impractical — and don\'t use it to dodge hard work.',
      tags: ['Discipline', 'Spirit', 'Maturity'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 7,
    },
  },

  // ─────────────────────────────────────────────
  // URANUS HOUR
  // ─────────────────────────────────────────────
  Uranus: {
    Mars: {
      title: 'Lightning Strike',
      summary: 'Action erupts without warning this hour. The impulsive breakthrough, the rebellion against whatever\'s been fencing you in, the move that rewrites the whole situation — speed is everything right now. When the bolt hits you, move with it. Immediately.',
      focus: 'Act on the sudden impulse that breaks the pattern — this is your liberation window.',
      caution: 'Don\'t detonate indiscriminately — fast and reckless aren\'t the same move.',
      tags: ['Rebellion', 'Speed', 'Breakthrough'],
      energyScore: 10,
      stabilityScore: 1,
      spiritualScore: 4,
    },
    Venus: {
      title: 'Wild Chemistry',
      summary: 'Attraction just swerved off the map. The unusual connection, the sudden spark, beauty showing up in a form you don\'t have a category for — this hour\'s chemistry refuses to follow your rules. Let it surprise you. That\'s what it\'s for.',
      focus: 'Say yes to the connection that defies your usual type — this hour, the anomaly is the signal.',
      caution: 'Don\'t trade something solid for a rush — excitement and compatibility run on different clocks.',
      tags: ['Excitement', 'Freedom', 'Chemistry'],
      energyScore: 8,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Mercury: {
      title: 'Genius Frequency',
      summary: 'Your mind is tuned to a frequency most people can\'t hear right now. Radical ideas, technological leaps, insights arriving fully formed from somewhere past ordinary thought — the downloads are fast this hour and they won\'t repeat. Transcribe everything.',
      focus: 'Capture the unconventional idea the moment it lands — then say it out loud, fearlessly.',
      caution: 'Don\'t firehose the radical idea at people — package it so the room can hear it.',
      tags: ['Genius', 'Innovation', 'Downloads'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 5,
    },
    Moon: {
      title: 'Emotional Lightning',
      summary: 'Your feelings are shifting at shocking speed this hour — and one of those jolts is carrying the truth about what you actually feel. Old emotional patterns are breaking loose right now. Let them. The insight that arrives as a shock is the one that frees you.',
      focus: 'Welcome the jolt of emotional clarity — it\'s cutting you loose from something old.',
      caution: 'Don\'t make forever decisions on a feeling that\'s ten minutes old.',
      tags: ['Awakening', 'Surprise', 'Release'],
      energyScore: 7,
      stabilityScore: 2,
      spiritualScore: 5,
    },
    Sun: {
      title: 'Original Fire',
      summary: 'You can\'t hide who you are this hour — so stop trying. Your uniqueness is demanding visibility right now, and the world actually benefits from your refusal to blend in. Radical self-expression is the assignment. Be the thing nobody else can be.',
      focus: 'Show your most authentic, unconventional self — no apology, no dimmer switch.',
      caution: 'Don\'t be contrary just to be contrary — rebellion against your own good is still self-harm.',
      tags: ['Originality', 'Rebellion', 'Expression'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Vesta: {
      title: 'Awakened Focus',
      summary: 'Break the rules of your own practice this hour — deliberately. The unconventional method, applied with devotion, produces something extraordinary right now: not scattered energy, but focus running through a brand-new channel. Experiment inside the discipline.',
      focus: 'Run your most devoted practice through a radically new method — today\'s the test flight.',
      caution: 'Don\'t abandon what works for what\'s merely new — novelty has to earn its keep.',
      tags: ['Focus', 'Innovation', 'Devotion'],
      energyScore: 7,
      stabilityScore: 5,
      spiritualScore: 6,
    },
    Juno: {
      title: 'Free Alliance',
      summary: 'Your partnerships want reinventing this hour. Nontraditional terms, surprising agreements, the freedom to redefine what commitment means for you two — relationships that flex right now thrive, and the rigid ones creak. Renegotiate something honestly.',
      focus: 'Let your relationships evolve past their default settings — propose the honest change.',
      caution: 'Don\'t swing freedom like a weapon — destabilizing the bond for a thrill isn\'t liberation.',
      tags: ['Freedom', 'Partnership', 'Surprise'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 4,
    },
    Pluto: {
      title: 'Total Revolution',
      summary: 'Everything is changing at once right now — awakening and transformation colliding, systems collapsing, old versions of you dissolving mid-sentence. You don\'t get to pause this window. You get to steer it. Point the upheaval at what actually needs to fall.',
      focus: 'Direct the revolution instead of resisting it — choose what it clears.',
      caution: 'Don\'t go nihilist in the chaos — keep your humanity on through the demolition.',
      tags: ['Revolution', 'Transformation', 'Upheaval'],
      energyScore: 10,
      stabilityScore: 1,
      spiritualScore: 6,
    },
    Jupiter: {
      title: 'Visionary Leap',
      summary: 'The future just arrived early. Massive, sudden expansion is available this hour — breakthrough growth, unexpected abundance, the opportunity that only shows itself to people willing to jump without the net. You can see the ledge. This window is for leaving it.',
      focus: 'Take the visionary leap the cautious people won\'t — this hour is the net.',
      caution: 'Don\'t confuse adrenaline with vision — leap at the thing, not just the feeling.',
      tags: ['Vision', 'Expansion', 'Breakthrough'],
      energyScore: 9,
      stabilityScore: 3,
      spiritualScore: 6,
    },
    Saturn: {
      title: 'Structured Rebellion',
      summary: 'Your radical idea needs scaffolding this hour — and the tension between wild and rigorous is exactly what makes it work. The rebellion that succeeds is the one with a plan. Build the frame around the lightning right now, and the flash becomes a machine.',
      focus: 'Give your most radical idea a practical framework — structure is what makes it survive.',
      caution: 'Don\'t let either side win outright — pure order kills it, pure chaos drops it.',
      tags: ['Reform', 'Structure', 'Innovation'],
      energyScore: 7,
      stabilityScore: 6,
      spiritualScore: 4,
    },
    Uranus: {
      title: 'Pure Liberation',
      summary: 'The cage door is open right now. Total freedom, full awakening, the complete dismantling of whatever has been holding you back — this hour compromises on nothing. The only mistake available is standing still and admiring the open door. Walk.',
      focus: 'Step through the door that just opened — all the way through, now.',
      caution: 'Don\'t demolish the load-bearing walls — some of what you\'re fleeing you actually need.',
      tags: ['Liberation', 'Awakening', 'Change'],
      energyScore: 9,
      stabilityScore: 1,
      spiritualScore: 6,
    },
    Neptune: {
      title: 'Cosmic Download',
      summary: 'The signal coming through right now doesn\'t use language. Visionary flashes, surreal awakenings, insight that feels beamed in from another dimension entirely — reality is stranger than you thought and this hour proves it. Stay open. Take notes you won\'t understand until later.',
      focus: 'Receive the cosmic insight trying to reach you — record it even when it makes no sense yet.',
      caution: 'Don\'t confuse disorientation with enlightenment — dizzy isn\'t the same as awake.',
      tags: ['Vision', 'Cosmic', 'Awakening'],
      energyScore: 6,
      stabilityScore: 2,
      spiritualScore: 10,
    },
  },

  // ─────────────────────────────────────────────
  // NEPTUNE HOUR
  // ─────────────────────────────────────────────
  Neptune: {
    Mars: {
      title: 'Spiritual Warrior',
      summary: 'Your actions are being guided by something you can\'t see this hour — and that\'s the point. Inspired effort, service to a cause bigger than you, the courage to act on conviction instead of calculation. When the deep signal says move, move. That\'s the practice right now.',
      focus: 'Act from spiritual conviction and make the effort an offering — this hour, that\'s strength.',
      caution: 'Don\'t martyr yourself — and don\'t pick up a sword for a battle that was never yours.',
      tags: ['Sacrifice', 'Inspiration', 'Effort'],
      energyScore: 6,
      stabilityScore: 3,
      spiritualScore: 7,
    },
    Venus: {
      title: 'Dream Romance',
      summary: 'Love has gone transcendent on you this hour. Soft beauty, soul-level connection, romance with something otherworldly in its edges — your heart is seeing further than your eyes right now. Enjoy the dream fully. Just remember you\'re in one.',
      focus: 'Let yourself be enchanted — follow the beauty past the material for an hour.',
      caution: 'Don\'t fall in love with the projection — the fantasy version can\'t love you back.',
      tags: ['Romance', 'Dreams', 'Beauty'],
      energyScore: 4,
      stabilityScore: 4,
      spiritualScore: 9,
    },
    Mercury: {
      title: 'Visionary Words',
      summary: 'Your language is dissolving into poetry right now. The imaginative draft, the message with spirit in it, the words that carry image and feeling instead of mere information — write them this hour, while the channel is open. Literal can wait until tomorrow.',
      focus: 'Write or speak from where imagination meets spirit — the channel is open now.',
      caution: 'Don\'t present the poetry as fact — beautiful and accurate are separate claims.',
      tags: ['Poetry', 'Vision', 'Imagination'],
      energyScore: 5,
      stabilityScore: 3,
      spiritualScore: 8,
    },
    Moon: {
      title: 'Psychic Ocean',
      summary: 'Your sensitivity has no edges this hour. Empathy is oceanic, dreams are loud, and your inner world is exactly as real as the outer one right now. Everything is transmitting. You don\'t have to answer every signal — just float, receive, and note what keeps repeating.',
      focus: 'Trust the deep impressions and let the tide carry you — receiving is the work this hour.',
      caution: 'Don\'t absorb everyone\'s suffering as your own — you\'re a receiver, not a sponge.',
      tags: ['Psychic', 'Dreams', 'Empathy'],
      energyScore: 3,
      stabilityScore: 3,
      spiritualScore: 10,
    },
    Sun: {
      title: 'Inspired Glow',
      summary: 'Something bigger than your personality is lighting you up this hour. Your presence carries it, your creative work channels it, and trying to take personal credit only dims it. Be the vessel right now — make what wants making and let the source stay nameless.',
      focus: 'Let inspiration move through you — create and radiate without gripping the credit.',
      caution: 'Don\'t evaporate into the current — keep enough self to steer.',
      tags: ['Inspiration', 'Radiance', 'Vision'],
      energyScore: 5,
      stabilityScore: 4,
      spiritualScore: 8,
    },
    Vesta: {
      title: 'Sacred Surrender',
      summary: 'Devotion becomes prayer this hour. Deep meditation, mystical service, the handing over of personal will to something larger — effort dissolves into offering right now, and the discipline itself turns into worship. Kneel into the work. It knows the way.',
      focus: 'Surrender the outcome and let your service become prayer — fully, this hour.',
      caution: 'Don\'t use devotion as a hiding place — practical reality still gets a vote.',
      tags: ['Prayer', 'Meditation', 'Surrender'],
      energyScore: 3,
      stabilityScore: 5,
      spiritualScore: 10,
    },
    Juno: {
      title: 'Soul Bond',
      summary: 'The connection between you and yours feels destined this hour — guided, compassionate, operating at soul level rather than schedule level. Trust that dimension. Love right now isn\'t practical, and it isn\'t supposed to be. It\'s sacred, and it\'s asking you to meet it there.',
      focus: 'Meet your bond at its spiritual depth — lead with compassion, not logistics.',
      caution: 'Don\'t idealize your person into someone they never claimed to be.',
      tags: ['Soul', 'Compassion', 'Union'],
      energyScore: 4,
      stabilityScore: 4,
      spiritualScore: 9,
    },
    Pluto: {
      title: 'Infinite Depth',
      summary: 'The deepest transformation and the most boundless surrender are happening at once this hour. Your ego is dissolving under forces far larger than you — mystical death and rebirth, running on their own schedule. Loosen your grip on who you were. Let the process finish.',
      focus: 'Release your hold on identity and let the transformation complete itself.',
      caution: 'Don\'t spiral into dread — dissolution is intense, but you still have to eat lunch.',
      tags: ['Transformation', 'Mystery', 'Dissolution'],
      energyScore: 5,
      stabilityScore: 2,
      spiritualScore: 10,
    },
    Jupiter: {
      title: 'Divine Expansion',
      summary: 'Your faith is expanding without limit this hour. Grace, blessing, and the sense that the universe is both infinitely generous and infinitely mysterious — compassion and wisdom are merging into something luminous in you right now. Trust the abundance. It\'s not a trick.',
      focus: 'Let your faith stretch — trust the spiritual abundance that\'s surrounding you now.',
      caution: 'Don\'t turn the mystical experience into an ego trophy — grace isn\'t a rank.',
      tags: ['Grace', 'Faith', 'Expansion'],
      energyScore: 5,
      stabilityScore: 5,
      spiritualScore: 10,
    },
    Saturn: {
      title: 'Grounded Mysticism',
      summary: 'Your spiritual vision gets its structural inspection this hour. Intuition tested against reality, faith tempered by experience, the mystical proving its worth in the material world — what passes the test right now becomes wisdom that serves both worlds. Run the test.',
      focus: 'Bring one spiritual insight down to earth and apply it — practically, today.',
      caution: 'Don\'t dismiss the vision as impractical — and don\'t hide from hard work inside it.',
      tags: ['Faith', 'Structure', 'Devotion'],
      energyScore: 5,
      stabilityScore: 7,
      spiritualScore: 8,
    },
    Uranus: {
      title: 'Cosmic Vision',
      summary: 'Reality is bending this hour. Strange visions, spiritual breakthroughs, insight arriving from somewhere past ordinary perception — it disorients on purpose. What you see in this window can\'t be unseen, and that\'s the gift. Look directly at it.',
      focus: 'Open to the vision breaking through — look at it straight, even when it\'s strange.',
      caution: 'Don\'t mislabel dizziness as revelation — ground first, interpret second.',
      tags: ['Vision', 'Breakthrough', 'Cosmic'],
      energyScore: 6,
      stabilityScore: 2,
      spiritualScore: 10,
    },
    Neptune: {
      title: 'Pure Transcendence',
      summary: 'The boundary between you and everything else is dissolving completely this hour. Total surrender, divine mystery, the experience of oneness that doesn\'t fit into words — there\'s nothing to hold onto right now, and nothing to fear in the letting go. So let go. All the way.',
      focus: 'Surrender completely and let the mystery show you what it wants to show.',
      caution: 'Don\'t float off the earth entirely — your responsibilities will still be here in an hour.',
      tags: ['Transcendence', 'Mystery', 'Surrender'],
      energyScore: 2,
      stabilityScore: 2,
      spiritualScore: 10,
    },
  },
};

// ─────────────────────────────────────────────
// Lookup Helper
// ─────────────────────────────────────────────

export function getHourMinuteInterpretation(
  hourLord: string,
  minuteLord: string,
): HourMinuteInterpretation {
  const hourData = GALACTIC_HOUR_MINUTE_INTERPRETATIONS[hourLord];
  if (hourData && hourData[minuteLord]) {
    return hourData[minuteLord];
  }
  return fallbackInterpretation(hourLord, minuteLord);
}

// ─────────────────────────────────────────────
// Fallback Synthesizer
// ─────────────────────────────────────────────

function fallbackInterpretation(
  hourLord: string,
  minuteLord: string,
): HourMinuteInterpretation {
  const hourMeaning = RULER_MEANINGS[hourLord] || {
    keywords: 'cosmic force',
    essence: 'universal energy',
  };
  const minuteMeaning = RULER_MEANINGS[minuteLord] || {
    keywords: 'flowing expression',
    essence: 'active channel',
  };
  return {
    title: `${hourLord} through ${minuteLord}`,
    summary: `Right now ${hourMeaning.essence} is running your hour, and it's expressing through ${minuteMeaning.essence}. This window is speaking directly to you — use it while it's open.`,
    focus: `Channel your ${hourLord} drive through the ${minuteLord} method — deliberately, right now.`,
    caution: `Watch how these two currents collide in whatever you're doing right now — don't let them steer unsupervised.`,
    tags: [hourLord, minuteLord],
    energyScore: 5,
    stabilityScore: 5,
    spiritualScore: 5,
  };
}
