// ═══════════════════════════════════════════════════════════════════
// Build-A-Match — Midpoint Readings (web)
//
// EXACT MIRROR of align-app/src/services/buildAMatch/midpointInterpretations.ts.
//
// All 230 pairs among Align's 22 indexed bodies, each with a plain name,
// what it brings, and what it costs.
//
// Dual naming, as agreed: "Mars/Pluto — Intense Passion". The technical
// pair teaches over time; the plain name communicates on first read.
//
// ─── The frame ─────────────────────────────────────────────────────
// A midpoint is a sensitive point in YOUR chart. These readings describe
// what happens when THEIR body lands on it, within 1°. So every line is
// about being activated, not about the midpoint in the abstract.
//
// ─── Settled technique ─────────────────────────────────────────────
//   • existing midpointEngine — NEAR point only (short arc), not the axis
//   • 1° orb
//   • 230 = all pairs among the 22 indexed bodies, minus N.Node/S.Node
//     (the nodes are always opposite, so their short-arc midpoint is
//     undefined)
//
// PURE MODULE. No Supabase, no React Native.
//
// ─── Provenance ────────────────────────────────────────────────────
// Names approved by the founder. Readings are a STRAWMAN drafted for
// review — where one is rewritten, that version becomes Align's.
// ═══════════════════════════════════════════════════════════════════

export interface MidpointReading {
  /** Plain-language name. Shown alongside the technical pair, never instead. */
  name: string;
  /** What it brings when their body lands here. */
  light: string;
  /** What the same contact costs. Never omitted. */
  shadow: string;
}

/** Order-independent key: Sun/Moon and Moon/Sun are one entry. */
export function midpointKey(a: string, b: string): string {
  return [a, b].sort().join('/');
}

/**
 * The 13 pairs `SHADOW_MIDPOINT_PAIRS` in midpointEngine.ts already flags
 * as toxicity potential. These keep their name AND carry a warning — the
 * point is that they are the same placement, not two different ones.
 */
export const SHADOW_MIDPOINTS = new Set([
  'Mars/Pluto', 'Mars/Saturn', 'Pluto/Saturn', 'Moon/Pluto', 'Pluto/Venus',
  'Pluto/Sun', 'Moon/Saturn', 'Saturn/Venus', 'Mars/Neptune', 'Neptune/Venus',
  'Moon/Neptune', 'Mars/Uranus', 'Pluto/Uranus',
].map(k => midpointKey(...(k.split('/') as [string, string]))));

const R = (name: string, light: string, shadow: string): MidpointReading =>
  ({ name, light, shadow });

export const MIDPOINT_READINGS: Record<string, MidpointReading> = {
  // ═══ SUN ═══
  [midpointKey('Sun', 'Moon')]: R('Inner Union',
    'They land where who you are meets what you feel — the single most personal point in your chart. People who sit here feel like home and destiny at once.',
    'Whoever occupies this point has enormous say over your sense of self. That is a lot to hand to someone you have just met.'),
  [midpointKey('Sun', 'Mercury')]: R('Clear Voice',
    'They make you articulate. You say what you actually mean around them, often for the first time.',
    'Your voice starts sounding like theirs. Watch for opinions you did not arrive at yourself.'),
  [midpointKey('Sun', 'Venus')]: R('Warm Charm',
    'You are more likeable around them, and you can feel it happening.',
    'Charm is a surface. This point can make a shallow connection feel warmer than it is.'),
  [midpointKey('Sun', 'Mars')]: R('Drive',
    'They switch you on. Things you have been putting off get done.',
    'Also the point where you become someone who argues. The energy does not choose its target.'),
  [midpointKey('Sun', 'Jupiter')]: R('Big Life',
    'Your sense of what is possible expands. Plans get bigger while they are around.',
    'Bigger is not better. This point is where people overcommit and call it optimism.'),
  [midpointKey('Sun', 'Saturn')]: R('Earned Authority',
    'They take you seriously and make you take yourself seriously. Real weight.',
    'Or they become the authority. You start seeking permission you never used to need.'),
  [midpointKey('Sun', 'Uranus')]: R('The Original',
    'They meet the part of you that does not fit, and treat it as the good part.',
    'Being encouraged toward your strangeness is not the same as being supported through it.'),
  [midpointKey('Sun', 'Neptune')]: R('The Dreamer',
    'They see who you could be. It is genuinely inspiring.',
    'They may be in love with that version and not the one actually here.'),
  [midpointKey('Sun', 'Pluto')]: R('Total Force',
    'You become more yourself, harder, less negotiable. This point does not do halfway.',
    'Or you are remade in their image and cannot tell the difference from inside.'),
  [midpointKey('Sun', 'N.Node')]: R('Purpose',
    'They point at where you were already headed. Meeting them feels like timing.',
    'A pull toward your future can be used to justify almost anything in the present.'),
  [midpointKey('Sun', 'S.Node')]: R('Old Identity',
    'Instant recognition. They know the version of you that came before.',
    'They may keep you in it. Familiarity here is a room with the door shut.'),
  [midpointKey('Sun', 'Asc')]: R('Full Presence',
    'How you appear and who you are line up while they are looking.',
    'Their gaze becomes the mirror. Notice if you stop knowing yourself without it.'),
  [midpointKey('Sun', 'MC')]: R('Public Self',
    'They raise your standing. You become more visible, and more yourself in public.',
    'Visibility on loan. Test whether it survives their absence.'),
  [midpointKey('Sun', 'Chiron')]: R('The Wounded Self',
    'They see the injury at the centre of your identity and do not look away.',
    'They may need you wounded. Some people love the hurt version most.'),
  [midpointKey('Sun', 'Juno')]: R('Marriage Identity',
    'You read as someone\'s partner around them. The role fits.',
    'A role is not a self. Watch what you stop being in order to be a spouse.'),
  [midpointKey('Sun', 'Vesta')]: R('Sacred Work',
    'They understand what you are devoted to and protect your time for it.',
    'Devotion narrows a life. They may hold you to a calling past the point it serves you.'),
  [midpointKey('Sun', 'Pallas')]: R('The Strategist',
    'They see how you actually operate, including the parts you do not announce.',
    'Being read that clearly is also being manageable.'),
  [midpointKey('Sun', 'Lilith')]: R('Untamed Self',
    'They meet the part of you that refuses. It will feel like being let out.',
    'That part does not care what it costs, and they will not be the one to talk you down.'),
  [midpointKey('Sun', 'Eros')]: R('Desirable',
    'You feel wanted as yourself, not as a performance.',
    'Desire aimed at identity is hard to separate from love. Check which one this is.'),
  [midpointKey('Sun', 'Psyche')]: R('The Known Soul',
    'They know you at a depth you did not consent to and could not have prevented.',
    'Being known is not being kept. They may see all of it and still leave.'),
  [midpointKey('Sun', 'Ceres')]: R('Cared-For Self',
    'They tend to you as a person, not a project. Steady and unglamorous.',
    'Being cared for can quietly replace being capable.'),

  // ═══ MOON ═══
  [midpointKey('Moon', 'Mercury')]: R('Feeling Spoken',
    'You can say the feeling out loud instead of routing around it.',
    'Everything becomes discussable, including things that needed to stay felt.'),
  [midpointKey('Moon', 'Venus')]: R('Tenderness',
    'Genuine softness. They are gentle with you and it is not technique.',
    'Gentleness can avoid the necessary conversation forever.'),
  [midpointKey('Moon', 'Mars')]: R('Raw Reaction',
    'Nothing is suppressed. You know exactly where you stand with each other.',
    'Things get said in heat that do not get unsaid.'),
  [midpointKey('Moon', 'Jupiter')]: R('Emotional Abundance',
    'They make room for you to feel big. Generous with your moods.',
    'Optimism used to skip past what actually hurts.'),
  [midpointKey('Moon', 'Saturn')]: R('Held-Back Feeling',
    'They stay steady when you are not okay. Unshaken, present, dry-eyed.',
    'On Align\'s shadow list. You will feel like a burden — not once, as a baseline.'),
  [midpointKey('Moon', 'Uranus')]: R('Unpredictable Heart',
    'Feeling arrives fast and unrehearsed. Never boring.',
    'You cannot plan around them emotionally. There is no pattern to learn.'),
  [midpointKey('Moon', 'Neptune')]: R('Dissolving Feeling',
    'You feel each other without asking. Rare and real.',
    'On the shadow list. You assume you were understood; often you were not, and nobody checks.'),
  [midpointKey('Moon', 'Pluto')]: R('Emotional Depth Charge',
    'They reach the feeling under the feeling. Nothing stays polite.',
    'On the shadow list. Emotional control lives here and it is very hard to see from inside.'),
  [midpointKey('Moon', 'N.Node')]: R('Where The Heart Is Going',
    'They belong to the emotional life you are moving toward, not the one you had.',
    'Future-facing people are often poor at the present, which is where you live.'),
  [midpointKey('Moon', 'S.Node')]: R('The Familiar Feeling',
    'They feel like somewhere you already lived. Your guard drops early.',
    'Familiar is not safe. Early comfort skips the part where you find out.'),
  [midpointKey('Moon', 'Asc')]: R('Open Face',
    'What you feel shows. Around them you stop managing your expression.',
    'You are readable to someone whose intentions you have not verified.'),
  [midpointKey('Moon', 'MC')]: R('Private Made Public',
    'Your inner life becomes part of how the world sees you, and it works.',
    'Things meant for one person end up in front of everyone.'),
  [midpointKey('Moon', 'Chiron')]: R('The Old Hurt',
    'They reach the childhood thing. It can genuinely heal here.',
    'Or it reopens on a schedule neither of you chose.'),
  [midpointKey('Moon', 'Juno')]: R('Home And Vow',
    'Emotional safety and commitment arrive together, which is rarer than it sounds.',
    'Staying because leaving would break the home, long after the feeling went.'),
  [midpointKey('Moon', 'Vesta')]: R('Devoted Care',
    'They tend to you with a seriousness most people never receive.',
    'Devotion narrows. Both of your worlds get smaller and neither of you notices.'),
  [midpointKey('Moon', 'Pallas')]: R('Emotional Intelligence',
    'They understand the pattern in your moods before you do.',
    'Understanding your patterns is also knowing how to work them.'),
  [midpointKey('Moon', 'Lilith')]: R('The Refused Feeling',
    'They meet the emotion you were taught not to have. Usually anger.',
    'That emotion has been waiting a long time and it does not arrive gently.'),
  [midpointKey('Moon', 'Eros')]: R('Wanting To Be Held',
    'Desire and comfort point the same direction. You want them and you rest with them.',
    'Comfort mistaken for compatibility keeps people in place for years.'),
  [midpointKey('Moon', 'Psyche')]: R('Felt Completely',
    'They feel your state before you have named it, from another room.',
    'No privacy in your own interior. Nothing you feel stays yours first.'),
  [midpointKey('Moon', 'Ceres')]: R('Mothering',
    'Real care, in practice — fed, warm, noticed. Not sentiment, behaviour.',
    'Care becomes management. Notice when you stopped deciding.'),

  // ═══ MERCURY ═══
  [midpointKey('Mercury', 'Venus')]: R('Sweet Talk',
    'They are lovely to talk to and they know it. Conversation feels like affection.',
    'Charm in language is the easiest thing to fake and the hardest to catch.'),
  [midpointKey('Mercury', 'Mars')]: R('Sharp Tongue',
    'Fast, direct, alive. You argue well together.',
    'The same speed that makes it fun makes it cut.'),
  [midpointKey('Mercury', 'Jupiter')]: R('Big Ideas',
    'Every conversation opens outward. You leave knowing more than you came with.',
    'Breadth without depth. Much talked about, little settled.'),
  [midpointKey('Mercury', 'Saturn')]: R('Careful Words',
    'They hold you to what you actually said. Your thinking gets rigorous.',
    'You start editing before you speak. Eventually you stop speaking.'),
  [midpointKey('Mercury', 'Uranus')]: R('Lightning Mind',
    'They say the thing that reorganises your week in one sentence.',
    'Stimulation mistaken for insight. Some weeks you needed to be left alone.'),
  [midpointKey('Mercury', 'Neptune')]: R('Poetic Confusion',
    'You understand each other without finishing sentences.',
    'This is where it quietly breaks. Neither of you finds out for months.'),
  [midpointKey('Mercury', 'Pluto')]: R('Words With Power',
    'Nothing stays on the surface. They ask the second question.',
    'The second question becomes an interrogation, and you will feel watched.'),
  [midpointKey('Mercury', 'N.Node')]: R('The Message',
    'They say the thing you needed to hear at exactly the moment it lands.',
    'Timing that good is easy to mistake for fate.'),
  [midpointKey('Mercury', 'S.Node')]: R('What You Always Say',
    'They already know your stories. You can skip the setup.',
    'They also know the ones you tell to avoid the truth, and they let you.'),
  [midpointKey('Mercury', 'Asc')]: R('How You Come Across',
    'You explain yourself well around them. You get read correctly.',
    'Being easy to read is being easy to anticipate.'),
  [midpointKey('Mercury', 'MC')]: R('Known For What You Say',
    'They make your ideas public. Your work gets heard.',
    'Half-formed thinking gets attributed to you before it was ready.'),
  [midpointKey('Mercury', 'Chiron')]: R('The Thing Hard To Say',
    'They make speakable the thing you have never put into words.',
    'Said aloud is not the same as resolved, and it cannot be unsaid.'),
  [midpointKey('Mercury', 'Juno')]: R('Talking It Through',
    'You negotiate rather than escalate. Conflict has a route out.',
    'Endless discussion in place of a decision.'),
  [midpointKey('Mercury', 'Vesta')]: R('Focused Study',
    'You go deep on one thing together and it holds.',
    'One subject crowds out the rest of the relationship.'),
  [midpointKey('Mercury', 'Pallas')]: R('Pattern Recognition',
    'They see the shape you have been staring past for a year.',
    'Applied to a relationship, strategy stops being insight and becomes management.'),
  [midpointKey('Mercury', 'Lilith')]: R('Saying The Unsayable',
    'They ask what nobody asks. It is a relief.',
    'Some things were unsaid on purpose and cannot be put back.'),
  [midpointKey('Mercury', 'Eros')]: R('Flirtation',
    'The conversation is the seduction. Words do the work.',
    'A relationship that lives in text often cannot survive a room.'),
  [midpointKey('Mercury', 'Psyche')]: R('Understanding',
    'They follow your meaning past your wording, to what you actually intended.',
    'Being understood that fast removes your chance to change your mind privately.'),
  [midpointKey('Mercury', 'Ceres')]: R('Words That Nourish',
    'What they say to you feeds something. Small sentences, lasting effect.',
    'Words in place of action. Notice whether anything is actually done.'),

  // ═══ VENUS ═══
  [midpointKey('Venus', 'Mars')]: R('Desire',
    'Wanting and being wanted, mutual and uncomplicated.',
    'Chemistry is not compatibility. It can hold together two people who agree on nothing.'),
  [midpointKey('Venus', 'Jupiter')]: R('Generous Love',
    'Warmth without accounting. They give and enjoy giving.',
    'Generosity creates obligation whether or not anyone intended it.'),
  [midpointKey('Venus', 'Saturn')]: R('Love That Costs',
    'Real, tested affection. Nothing here is casual and nothing is free.',
    'On the shadow list. Withholding. You are always slightly not enough, and it is never said.'),
  [midpointKey('Venus', 'Uranus')]: R('Sudden Attraction',
    'It arrives fast and it is exciting. Unlike your usual.',
    'What arrives fast leaves fast. This point is not known for staying.'),
  [midpointKey('Venus', 'Neptune')]: R('Idealised Love',
    'They look like the answer. Genuinely enchanting, and it feels like recognition.',
    'On the shadow list. You are in love with an image; the person is behind it.'),
  [midpointKey('Venus', 'Pluto')]: R('Obsessive Love',
    'You will think about them when you are trying not to. Magnetic, literally.',
    'On the shadow list. Jealousy lives here, and obsession wearing love\'s clothes.'),
  [midpointKey('Venus', 'N.Node')]: R('Love As Direction',
    'Loving them moves your life somewhere. It is not static.',
    'A relationship that is also a direction is very hard to leave.'),
  [midpointKey('Venus', 'S.Node')]: R('The Love You Repeat',
    'Instant ease, as if resuming rather than starting.',
    'You may be repeating something rather than beginning it. Check the pattern.'),
  [midpointKey('Venus', 'Asc')]: R('Instant Appeal',
    'They find you beautiful before you have done anything to earn it.',
    'Attraction this immediate carries relationships past the point they should have been questioned.'),
  [midpointKey('Venus', 'MC')]: R('Loved In Public',
    'You look good together and it helps you both.',
    'A relationship that performs well in public can be hollow in private.'),
  [midpointKey('Venus', 'Chiron')]: R('Loved At The Wound',
    'They love the part you are least proud of.',
    'Being loved there can make you keep the wound, because it is what they love.'),
  [midpointKey('Venus', 'Juno')]: R('Committed Love',
    'Affection that intends to stay, and says so out loud.',
    'The intention can be sincere and still not survive contact.'),
  [midpointKey('Venus', 'Vesta')]: R('Sacred Devotion',
    'Love treated as something to tend rather than consume.',
    'Devotion to the love can outlast the love itself.'),
  [midpointKey('Venus', 'Pallas')]: R('Loving Wisely',
    'You choose each other with your eyes open. Rare and underrated.',
    'Choosing wisely can be a way of never choosing riskily.'),
  [midpointKey('Venus', 'Lilith')]: R('Forbidden Attraction',
    'They meet whatever you do not admit to wanting.',
    'Wanting what you cannot respect. This point does not care about your self-image.'),
  [midpointKey('Venus', 'Eros')]: R('Erotic Love',
    'Desire and affection point the same direction, which is not always the case.',
    'When the erotic charge fades, check whether anything else was holding it.'),
  [midpointKey('Venus', 'Psyche')]: R('Soul Attraction',
    'You are drawn to what they actually are, not what they present.',
    'Loving someone\'s depths is not the same as being able to live with their surface.'),
  [midpointKey('Venus', 'Ceres')]: R('Nurturing Love',
    'Love expressed as care. Fed, warm, looked after.',
    'Care can become the whole of the love, and care is not desire.'),

  // ═══ MARS ═══
  [midpointKey('Mars', 'Jupiter')]: R('Bold Action',
    'You do the brave thing while they are around. Momentum.',
    'Bravery and recklessness look identical until afterwards.'),
  [midpointKey('Mars', 'Saturn')]: R('Blocked Force',
    'They slow you down, and sometimes you needed slowing.',
    'On the shadow list. Frustration with nowhere to go turns into resentment.'),
  [midpointKey('Mars', 'Uranus')]: R('Explosive',
    'Sudden, electric, decisive. Things break open.',
    'On the shadow list. This point is where accidents and blow-ups happen.'),
  [midpointKey('Mars', 'Neptune')]: R('Misdirected Drive',
    'Effort in service of something larger than you.',
    'On the shadow list. Energy poured into a fantasy. You will not see it while it happens.'),
  [midpointKey('Mars', 'Pluto')]: R('Intense Passion',
    'Total physical and psychological force. Nothing about this is casual.',
    'First on Align\'s shadow list. Control, obsession and volatility live at exactly this point.'),
  [midpointKey('Mars', 'N.Node')]: R('Driven Forward',
    'They push you toward where you were going anyway.',
    'A push is still a push. Notice whether the direction was yours.'),
  [midpointKey('Mars', 'S.Node')]: R('The Old Fight',
    'The conflict is familiar. You already know the choreography.',
    'Familiar conflict is the hardest kind to leave. You are good at it.'),
  [midpointKey('Mars', 'Asc')]: R('Physical Charge',
    'Your body reacts to them being in the room.',
    'The same charge is why you fight so easily.'),
  [midpointKey('Mars', 'MC')]: R('Ambition',
    'They push you at your work and it produces results.',
    'Competition inside the relationship. Someone has to be winning.'),
  [midpointKey('Mars', 'Chiron')]: R('The Wound That Fights',
    'They activate the injury and give you somewhere to put it.',
    'Fighting from a wound looks like strength and is not.'),
  [midpointKey('Mars', 'Juno')]: R('Fighting For It',
    'They will fight for the relationship. That is worth a great deal.',
    'And they will fight inside it. The same energy does both.'),
  [midpointKey('Mars', 'Vesta')]: R('Disciplined Force',
    'Focused effort, sustained. Nothing wasted.',
    'Discipline aimed at a person becomes control.'),
  [midpointKey('Mars', 'Pallas')]: R('Tactical Force',
    'You act with a plan rather than an impulse.',
    'A planned move in a relationship is still a move being made on you.'),
  [midpointKey('Mars', 'Lilith')]: R('Raw Want',
    'They meet the part of you that does not ask permission.',
    'This point does not care about your plans or your self-image.'),
  [midpointKey('Mars', 'Eros')]: R('Direct Desire',
    'Wanting without negotiation. Explicit and mutual.',
    'Desire that does not wait for the rest of the relationship to catch up.'),
  [midpointKey('Mars', 'Psyche')]: R('Passionate Knowing',
    'They want you and they understand you. Both at full volume.',
    'Being wanted by someone who knows exactly where you are soft.'),
  [midpointKey('Mars', 'Ceres')]: R('Fierce Protection',
    'They will stand in front of you. Literally, if it comes to it.',
    'Protection slides into possession without a visible line between them.'),

  // ═══ JUPITER ═══
  [midpointKey('Jupiter', 'Saturn')]: R('Growth With Structure',
    'Expansion that has a floor under it. Rare combination, genuinely valuable.',
    'The brake and the engine in one place. Progress can stall for years and look like patience.'),
  [midpointKey('Jupiter', 'Uranus')]: R('Sudden Luck',
    'Doors open unexpectedly while they are around.',
    'Luck is not a plan. This point gives and takes on no schedule.'),
  [midpointKey('Jupiter', 'Neptune')]: R('Beautiful Delusion',
    'A shared vision that lifts both of you.',
    'The most convincing wrong idea you will ever have. Neither of you doubts it.'),
  [midpointKey('Jupiter', 'Pluto')]: R('Enormous Power',
    'Together you can move things neither could alone.',
    'Power concentrated in a couple is still concentrated power. Watch who holds it.'),
  [midpointKey('Jupiter', 'N.Node')]: R('Expansion Ahead',
    'They arrive at the moment your life was about to get bigger.',
    'Growth and the person who arrived with it are easy to confuse.'),
  [midpointKey('Jupiter', 'S.Node')]: R('Old Abundance',
    'Ease that feels earned already. Nothing has to be built.',
    'Coasting on something that is already spent.'),
  [midpointKey('Jupiter', 'Asc')]: R('Larger Presence',
    'You take up more room around them and people notice.',
    'Confidence borrowed from someone leaves when they do.'),
  [midpointKey('Jupiter', 'MC')]: R('Rising Reputation',
    'Your standing improves. Introductions, opportunity, visibility.',
    'A reputation built on their network is not yours. Test it alone.'),
  [midpointKey('Jupiter', 'Chiron')]: R('Healing Through Meaning',
    'They give the injury a context that makes it bearable.',
    'Meaning applied to pain can be a sophisticated way of not treating it.'),
  [midpointKey('Jupiter', 'Juno')]: R('Expansive Commitment',
    'Partnership that makes both lives bigger rather than smaller.',
    'Commitment that keeps expanding never quite settles into anything.'),
  [midpointKey('Jupiter', 'Vesta')]: R('Devoted Belief',
    'Shared conviction, seriously held.',
    'Conviction shared by two people is very hard for either to question.'),
  [midpointKey('Jupiter', 'Pallas')]: R('Wise Strategy',
    'You think well together at scale. Good long decisions.',
    'Strategy at scale can quietly stop accounting for the people in it.'),
  [midpointKey('Jupiter', 'Lilith')]: R('Unapologetic Excess',
    'They give you permission to want more and not apologise for it.',
    'Excess with permission is still excess, and now nobody is objecting.'),
  [midpointKey('Jupiter', 'Eros')]: R('Joyful Desire',
    'Wanting each other is fun. Laughing, generous, unheavy.',
    'Fun resists depth. When you need it to mean something it may not know how.'),
  [midpointKey('Jupiter', 'Psyche')]: R('Soul Expansion',
    'They know you and that knowledge makes your life larger, not smaller.',
    'Being known by someone expansive can mean being carried somewhere you did not choose.'),
  [midpointKey('Jupiter', 'Ceres')]: R('Abundant Care',
    'Generous, plentiful looking-after. Nothing is rationed.',
    'Abundance of care can make you smaller by degrees.'),

  // ═══ SATURN ═══
  [midpointKey('Saturn', 'Uranus')]: R('Break Or Hold',
    'The tension between staying and leaving, made conscious.',
    'This point rarely resolves. It oscillates, and both of you get tired.'),
  [midpointKey('Saturn', 'Neptune')]: R('Dissolving Structure',
    'They soften the rules you were holding too tightly.',
    'Or the structure genuinely fails and nobody admits it until it is gone.'),
  [midpointKey('Saturn', 'Pluto')]: R('Crushing Weight',
    'Endurance. Whatever this survives, it survives properly.',
    'On the shadow list. The heaviest point in the set. What it builds it can also bury.'),
  [midpointKey('Saturn', 'N.Node')]: R('The Hard Road Forward',
    'The direction is right and it will not be easy. They come with the difficulty.',
    'Difficulty is not proof of rightness, though it will feel like it.'),
  [midpointKey('Saturn', 'S.Node')]: R('The Old Burden',
    'They know the weight you have always carried.',
    'Knowing it is not lifting it. They may simply help you keep carrying.'),
  [midpointKey('Saturn', 'Asc')]: R('Guarded',
    'You are careful around them, and the care is warranted.',
    'You get smaller. You will call it maturity long before you call it what it is.'),
  [midpointKey('Saturn', 'MC')]: R('Earned Standing',
    'Real authority, built slowly, that holds.',
    'They become the one who judges whether you have earned it.'),
  [midpointKey('Saturn', 'Chiron')]: R('The Wound That Hardens',
    'They give the injury structure. It stops running your life.',
    'Structure over a wound is scar tissue. Nothing grows through it either.'),
  [midpointKey('Saturn', 'Juno')]: R('Duty Marriage',
    'Commitment that will not break. It genuinely will not.',
    'Duty replaces love and neither of you says so. This is the cage that looks like devotion.'),
  [midpointKey('Saturn', 'Vesta')]: R('Lifelong Discipline',
    'Devotion that lasts decades. Serious, quiet, unwavering.',
    'A life narrowed to one thing, defended as commitment.'),
  [midpointKey('Saturn', 'Pallas')]: R('Cold Strategy',
    'Clear-eyed planning with no sentiment in it.',
    'Applied to a person, this is calculation, and you are being calculated.'),
  [midpointKey('Saturn', 'Lilith')]: R('Repressed Rage',
    'They meet the anger you have kept under a lid for years.',
    'It has been waiting. It does not come out proportionate.'),
  [midpointKey('Saturn', 'Eros')]: R('Withheld Desire',
    'Restraint that makes wanting sharper. Slow-burning.',
    'Or desire that is simply denied, on purpose, as leverage.'),
  [midpointKey('Saturn', 'Psyche')]: R('The Slow Knowing',
    'They learn you properly, over years, and it lasts.',
    'Slow knowing can also be slow judgement, accumulating.'),
  [midpointKey('Saturn', 'Ceres')]: R('Austere Care',
    'Care without warmth, but genuinely reliable. It shows up.',
    'Being looked after by someone who never says they love you.'),

  // ═══ URANUS ═══
  [midpointKey('Uranus', 'Neptune')]: R('Strange Vision',
    'You see something together that nobody around you sees.',
    'Shared vision with no reality check is how two people talk each other into anything.'),
  [midpointKey('Uranus', 'Pluto')]: R('Revolution',
    'Something in your life ends and something else starts. Fast.',
    'On the shadow list. Upheaval you did not choose and cannot steer.'),
  [midpointKey('Uranus', 'N.Node')]: R('The Break Forward',
    'They arrive as the disruption that moves you on.',
    'Disruption that moves you on also moves you away from things worth keeping.'),
  [midpointKey('Uranus', 'S.Node')]: R('The Old Rupture',
    'They touch a break that already happened once.',
    'Repeating a rupture is not the same as healing it.'),
  [midpointKey('Uranus', 'Asc')]: R('Unmistakable',
    'You are more visibly yourself, edges and all, when they are near.',
    'Standing out is not the same as being supported.'),
  [midpointKey('Uranus', 'MC')]: R('Unconventional Standing',
    'They make your unusual path look deliberate rather than accidental.',
    'Unconventional and unstable are hard to tell apart from outside.'),
  [midpointKey('Uranus', 'Chiron')]: R('Sudden Healing',
    'Something shifts fast that had not moved in years.',
    'Fast shifts are rarely finished. What moved can move back.'),
  [midpointKey('Uranus', 'Juno')]: R('Unconventional Bond',
    'A partnership on your own terms rather than the standard shape.',
    'Terms that suit one of you more than the other, unexamined.'),
  [midpointKey('Uranus', 'Vesta')]: R('Unusual Devotion',
    'Committed to something nobody else understands, together.',
    'Devotion nobody else understands is devotion nobody else can check.'),
  [midpointKey('Uranus', 'Pallas')]: R('Genius',
    'You solve things together that neither cracks alone.',
    'Brilliance is not kindness, and this point supplies only one of them.'),
  [midpointKey('Uranus', 'Lilith')]: R('Total Freedom',
    'No rules, no permission, no apology.',
    'Freedom that answers to nothing eventually answers to nobody, including you.'),
  [midpointKey('Uranus', 'Eros')]: R('Electric Desire',
    'Sudden, unpredictable, unmistakable when it hits.',
    'It cannot be summoned. You will spend time waiting for it to come back.'),
  [midpointKey('Uranus', 'Psyche')]: R('Sudden Recognition',
    'You know each other immediately, with no evidence.',
    'Recognition that fast has not been tested against anything.'),
  [midpointKey('Uranus', 'Ceres')]: R('Unpredictable Care',
    'Wonderful care, arriving on no schedule.',
    'Care you cannot rely on is not care you can build on.'),

  // ═══ NEPTUNE ═══
  [midpointKey('Neptune', 'Pluto')]: R('The Deep Unseen',
    'You reach things together that neither would reach alone.',
    'Both of these bodies hide. Whatever goes wrong here goes wrong out of sight.'),
  [midpointKey('Neptune', 'N.Node')]: R('The Dream Ahead',
    'They embody the future you have been imagining.',
    'Imagining is not planning. This point does not distinguish.'),
  [midpointKey('Neptune', 'S.Node')]: R('The Old Illusion',
    'A familiar softness. You have believed this before.',
    'You have believed this before. That is the warning, not the comfort.'),
  [midpointKey('Neptune', 'Asc')]: R('Elusive',
    'Dreamlike to each other. Neither quite in focus.',
    'You are not seeing an actual person, and neither are they.'),
  [midpointKey('Neptune', 'MC')]: R('Blurred Reputation',
    'Your public face softens. People project warmly onto you.',
    'This is where scandal attaches. Keep the boundaries visible.'),
  [midpointKey('Neptune', 'Chiron')]: R('The Wound Without A Name',
    'They reach the hurt you have never been able to describe.',
    'Unnameable hurt met by an unclear person rarely resolves. It just gets shared.'),
  [midpointKey('Neptune', 'Juno')]: R('The Idealised Partner',
    'They look exactly like what you have always wanted.',
    'Looking like it and being it are different, and this point cannot tell you which.'),
  [midpointKey('Neptune', 'Vesta')]: R('Mystic Devotion',
    'Devotion with something sacred in it. Not ordinary.',
    'Sacred devotion is the hardest kind to walk away from when it stops serving you.'),
  [midpointKey('Neptune', 'Pallas')]: R('Intuitive Strategy',
    'You navigate by feel and it works more often than it should.',
    'It works until it does not, and there was never a plan underneath.'),
  [midpointKey('Neptune', 'Lilith')]: R('The Seductive Shadow',
    'They meet what you keep hidden, and make it feel beautiful.',
    'The most dangerous combination in the set: hidden, wanted, and unaccountable.'),
  [midpointKey('Neptune', 'Eros')]: R('Fantasy Desire',
    'Desire with a dreamlike quality. Genuinely intoxicating.',
    'You want an idea. The person may never be able to meet it.'),
  [midpointKey('Neptune', 'Psyche')]: R('Merged Souls',
    'The boundary thins. Something real happens in the gap.',
    'Dissolution is not intimacy. Check that there are still two people here.'),
  [midpointKey('Neptune', 'Ceres')]: R('Boundless Care',
    'Care with no limit and no conditions.',
    'No limit means no boundary. This is where enabling lives.'),

  // ═══ PLUTO ═══
  [midpointKey('Pluto', 'N.Node')]: R('Fated Transformation',
    'Meeting them changes the direction of your life. It will not feel optional.',
    'Inevitability is a story. You can always leave, and this point will make that feel untrue.'),
  [midpointKey('Pluto', 'S.Node')]: R('The Old Power',
    'A dynamic you have been in before, recognised instantly.',
    'Recognising a pattern is not the same as being free of it.'),
  [midpointKey('Pluto', 'Asc')]: R('Magnetic',
    'People turn. Whatever this is, it is not subtle.',
    'Magnetism is not consent. Being pulled is not the same as choosing.'),
  [midpointKey('Pluto', 'MC')]: R('Power In The World',
    'They understand power and will show you how it actually operates.',
    'What they built for you they can dismantle.'),
  [midpointKey('Pluto', 'Chiron')]: R('The Wound Transformed',
    'The injury becomes a source of strength rather than a limit.',
    'Transformation is not gentle and this one does not ask first.'),
  [midpointKey('Pluto', 'Juno')]: R('Possessive Bond',
    'Total commitment. Nothing about this partnership is casual.',
    'Possession wearing commitment\'s clothes. The line is thin and it moves.'),
  [midpointKey('Pluto', 'Vesta')]: R('Consuming Devotion',
    'Devotion at full intensity, holding nothing back.',
    'Consumed is the accurate word. Ask what is left of you afterwards.'),
  [midpointKey('Pluto', 'Pallas')]: R('Ruthless Strategy',
    'Clear sight with no illusion. Very effective.',
    'Effective against you as easily as for you.'),
  [midpointKey('Pluto', 'Lilith')]: R('Dangerous Power',
    'The most charged point in the set. Nothing here is polite.',
    'Both bodies refuse limits. Together they refuse them absolutely.'),
  [midpointKey('Pluto', 'Eros')]: R('Consuming Desire',
    'Desire that does not negotiate. You will return against your own judgement.',
    'Compulsion is not chemistry, and from inside they are identical.'),
  [midpointKey('Pluto', 'Psyche')]: R('Soul Excavation',
    'They bring up what is buried. It is not optional and it is not gentle.',
    'Some things were buried for a reason, and they may not be able to help once it is out.'),
  [midpointKey('Pluto', 'Ceres')]: R('Devouring Care',
    'Care with total commitment behind it. Nothing withheld.',
    'Care that consumes the person receiving it. Usually framed as love.'),

  // ═══ NORTH NODE ═══
  [midpointKey('N.Node', 'Asc')]: R('Meeting Your Direction',
    'They arrive looking like where you were already going.',
    'The resemblance may be yours, projected. Check it against what they actually do.'),
  [midpointKey('N.Node', 'MC')]: R('Destined Calling',
    'They connect to your work in a way that feels arranged.',
    'A career and a person entangled are very hard to separate later.'),
  [midpointKey('N.Node', 'Chiron')]: R('Healing As Purpose',
    'The wound and the direction turn out to be the same road.',
    'Making the injury your purpose can mean never letting it close.'),
  [midpointKey('N.Node', 'Juno')]: R('Fated Partnership',
    'This one reads as meant. It genuinely may be.',
    '"Meant" has kept more people in place than any other word.'),
  [midpointKey('N.Node', 'Vesta')]: R('Sacred Purpose',
    'Devotion and direction align. You know what you are for.',
    'Certainty about purpose leaves no room to be wrong about it.'),
  [midpointKey('N.Node', 'Pallas')]: R('Wise Direction',
    'You can see the road and the reason at the same time.',
    'Seeing clearly is not the same as being willing to walk it.'),
  [midpointKey('N.Node', 'Lilith')]: R('The Untamed Path',
    'The direction forward is the one nobody approved of.',
    'Not everything unapproved is liberation. Some of it is just cost.'),
  [midpointKey('N.Node', 'Eros')]: R('Fated Desire',
    'Wanting them feels like part of the plan.',
    'Desire narrated as destiny is desire that cannot be questioned.'),
  [midpointKey('N.Node', 'Psyche')]: R('Soul Direction',
    'They know the part of you that is still becoming.',
    'Being known before you have arrived can fix you in place.'),
  [midpointKey('N.Node', 'Ceres')]: R('Nurturing Purpose',
    'Care and direction in one. They feed what you are growing into.',
    'Being fed toward a direction is still being fed a direction.'),

  // ═══ SOUTH NODE ═══
  [midpointKey('S.Node', 'Asc')]: R('The Face You Already Had',
    'They meet the version of you that existed before you worked on yourself.',
    'They may prefer that version, and slowly ask for it back.'),
  [midpointKey('S.Node', 'MC')]: R('The Old Reputation',
    'They know who you used to be professionally.',
    'Being known for the old work makes the new work invisible.'),
  [midpointKey('S.Node', 'Chiron')]: R('The Inherited Wound',
    'They touch the injury that was handed to you rather than earned.',
    'Inherited wounds have deep roots and this contact does not pull them.'),
  [midpointKey('S.Node', 'Juno')]: R('The Marriage Before',
    'The bond feels resumed rather than begun.',
    'Resumed relationships resume their problems too.'),
  [midpointKey('S.Node', 'Vesta')]: R('The Old Devotion',
    'You have given yourself to this before, and know how.',
    'Knowing how is why you will do it again without deciding to.'),
  [midpointKey('S.Node', 'Pallas')]: R('Inherited Cunning',
    'You both know the moves. Nothing has to be explained.',
    'Two people who know all the moves rarely stop making them.'),
  [midpointKey('S.Node', 'Lilith')]: R('The Old Exile',
    'They meet the part of you that was cast out a long time ago.',
    'Reunion with an exiled part is not the same as integration.'),
  [midpointKey('S.Node', 'Eros')]: R('The Desire You Return To',
    'This want is not new. You have followed it before.',
    'The type you keep choosing is visible here, and so is the reason.'),
  [midpointKey('S.Node', 'Psyche')]: R('Already Known',
    'Recognition with no origin. You have done this before, whatever you make of that.',
    'Familiar is not good. Old patterns feel like home precisely because they are old.'),
  [midpointKey('S.Node', 'Ceres')]: R('The Care You Were Given',
    'They care for you the way you were cared for as a child.',
    'Including the parts of it that were not good for you.'),

  // ═══ ASCENDANT ═══
  [midpointKey('Asc', 'MC')]: R('Who You Are In Public',
    'Your private self and public face agree while they are around.',
    'Agreement enforced by someone else is not integration.'),
  [midpointKey('Asc', 'Chiron')]: R('The Visible Wound',
    'They see the injury you thought you had covered.',
    'Being seen and being helped are different. They may only ever be the mirror.'),
  [midpointKey('Asc', 'Juno')]: R('Built For Partnership',
    'You read as someone\'s person around them, and it fits.',
    'Fitting a role is not the same as choosing it.'),
  [midpointKey('Asc', 'Vesta')]: R('Devoted Presence',
    'You show up focused, serious, unwavering.',
    'Devotion visible from outside attracts people who want to be devoted to.'),
  [midpointKey('Asc', 'Pallas')]: R('Perceptive Presence',
    'You notice things around them and they notice you noticing.',
    'Perceptiveness is also being permanently on duty.'),
  [midpointKey('Asc', 'Lilith')]: R('Dangerous Presence',
    'You are more compelling and less manageable when they are near.',
    'Compelling and safe are not the same, in either direction.'),
  [midpointKey('Asc', 'Eros')]: R('Magnetic Body',
    'Physical presence does the work. Nothing has to be said.',
    'A relationship that runs on presence struggles at distance.'),
  [midpointKey('Asc', 'Psyche')]: R('Seen Through',
    'Your surface stops working. They see past it immediately.',
    'You have no first impression to manage, which removes your protection too.'),
  [midpointKey('Asc', 'Ceres')]: R('Nurturing Presence',
    'You are easy to be cared for and easy to care for.',
    'Being easy to care for attracts people who need someone to care for.'),

  // ═══ MIDHEAVEN ═══
  [midpointKey('MC', 'Chiron')]: R('The Public Wound',
    'What hurt you becomes what you are known for. It can be a whole career.',
    'A public wound cannot heal privately. It gets performed instead.'),
  [midpointKey('MC', 'Juno')]: R('Partnership As Status',
    'Being together is part of your standing, and it works.',
    'Leaving costs your reputation as well as your heart.'),
  [midpointKey('MC', 'Vesta')]: R('The Calling',
    'The work is not a job. They understand that.',
    'A calling justifies almost any sacrifice, including ones nobody asked for.'),
  [midpointKey('MC', 'Pallas')]: R('Strategic Career',
    'You play the long game well together.',
    'Your career becomes a joint project you did not agree to co-manage.'),
  [midpointKey('MC', 'Lilith')]: R('Reputation Refused',
    'You stop performing for the room. It is freeing.',
    'The room notices, and the room has a memory.'),
  [midpointKey('MC', 'Eros')]: R('Desired In Public',
    'You are wanted visibly, and the visibility is part of it.',
    'Desire that needs an audience is not always desire for you.'),
  [midpointKey('MC', 'Psyche')]: R('Known For Depth',
    'People trust you with real things. That is your standing.',
    'Being everyone\'s depth means nobody holds yours.'),
  [midpointKey('MC', 'Ceres')]: R('Career As Care',
    'Your work looks after people, and that is why it matters.',
    'Care as a profession is care with no off switch.'),

  // ═══ CHIRON ═══
  [midpointKey('Chiron', 'Juno')]: R('The Wound In Marriage',
    'The injury shows up inside commitment, where it can finally be worked on.',
    'Or it becomes the structure of the marriage and neither of you names it.'),
  [midpointKey('Chiron', 'Vesta')]: R('Healing As Devotion',
    'You tend the wound seriously, over time, and it moves.',
    'Devotion to healing can become an identity you cannot afford to finish.'),
  [midpointKey('Chiron', 'Pallas')]: R('Understanding The Wound',
    'They can explain to you what happened. That is worth a lot.',
    'Understanding is not repair, and it can substitute for it indefinitely.'),
  [midpointKey('Chiron', 'Lilith')]: R('The Wound That Refuses',
    'The injury turns into refusal — and refusal is a kind of strength.',
    'A wound defended is a wound kept.'),
  [midpointKey('Chiron', 'Eros')]: R('Desire From The Wound',
    'You want what once hurt you, and you know it.',
    'Knowing it has never yet stopped anyone.'),
  [midpointKey('Chiron', 'Psyche')]: R('The Soul\'s Injury',
    'They reach the wound underneath the wound — the one you do not perform.',
    'That layer has no vocabulary. Bringing it up may not make it better.'),
  [midpointKey('Chiron', 'Ceres')]: R('Wounded Nurture',
    'They care for you through the injury rather than around it.',
    'Care organised around a wound needs the wound to continue.'),

  // ═══ JUNO ═══
  [midpointKey('Juno', 'Vesta')]: R('Sacred Marriage',
    'Commitment treated as something holy. Serious, tended, kept.',
    'Sacred commitments are the hardest to end when they should end.'),
  [midpointKey('Juno', 'Pallas')]: R('Wise Partnership',
    'You partner with your eyes open and negotiate well.',
    'Negotiated everything is also nothing given freely.'),
  [midpointKey('Juno', 'Lilith')]: R('The Vow Broken',
    'The part of you that will not be contained meets the part that promised.',
    'This point is where affairs live. Not always — but it is where they live.'),
  [midpointKey('Juno', 'Eros')]: R('Passionate Commitment',
    'Desire and commitment in the same place, which is rarer than people admit.',
    'When one fades the other has to carry both, and it may not.'),
  [midpointKey('Juno', 'Psyche')]: R('Soul Marriage',
    'Committed to who they actually are rather than the arrangement.',
    'Knowing someone completely and staying anyway is love or inertia, and both feel identical.'),
  [midpointKey('Juno', 'Ceres')]: R('Marriage And Family',
    'Partnership and the raising of a household, integrated.',
    'The family can outgrow the partnership, and the partnership keeps going anyway.'),

  // ═══ VESTA ═══
  [midpointKey('Vesta', 'Pallas')]: R('Focused Wisdom',
    'Deep attention aimed intelligently. Very little is wasted.',
    'Focus this narrow does not notice what it excluded.'),
  [midpointKey('Vesta', 'Lilith')]: R('Devotion Refused',
    'You stop giving yourself to what did not deserve it.',
    'The refusal can generalise until nothing gets your devotion.'),
  [midpointKey('Vesta', 'Eros')]: R('Sacred Desire',
    'Wanting treated as something serious rather than casual.',
    'Sacred desire cannot be light, and sometimes light is what a relationship needs.'),
  [midpointKey('Vesta', 'Psyche')]: R('Devoted Knowing',
    'They keep learning you, deliberately, for years.',
    'Sustained attention is also sustained scrutiny.'),
  [midpointKey('Vesta', 'Ceres')]: R('Tending The Flame',
    'The daily unglamorous keeping-going of a life together.',
    'Tending can become the whole relationship. Maintenance is not intimacy.'),

  // ═══ PALLAS ═══
  [midpointKey('Pallas', 'Lilith')]: R('Subversive Strategy',
    'You see the system and refuse it at the same time. Effective.',
    'Effective subversion is still manipulation when aimed at a person.'),
  [midpointKey('Pallas', 'Eros')]: R('Seductive Intelligence',
    'The mind is the attraction. Being outthought is the appeal.',
    'Being outthought stops being fun the moment it is used on you.'),
  [midpointKey('Pallas', 'Psyche')]: R('Insight',
    'They understand the pattern and the person at once.',
    'Complete understanding of someone is also complete access.'),
  [midpointKey('Pallas', 'Ceres')]: R('Practical Wisdom',
    'Care that is actually well aimed. The right help, not just help.',
    'Well-aimed care can be well-aimed at a version of you that has moved on.'),

  // ═══ LILITH ═══
  [midpointKey('Lilith', 'Eros')]: R('Untamed Desire',
    'Want with nothing civilised on top of it.',
    'This point has no brakes, and neither of you is the brake.'),
  [midpointKey('Lilith', 'Psyche')]: R('The Shadow Known',
    'They see the part you were told to be ashamed of, and do not flinch.',
    'Someone who knows your shadow can find it again whenever they want to.'),
  [midpointKey('Lilith', 'Ceres')]: R('Refusing To Nurture',
    'You stop caring for what was draining you. Overdue.',
    'The refusal rarely stops at the thing that deserved it.'),

  // ═══ EROS ═══
  [midpointKey('Eros', 'Psyche')]: R('The Great Love',
    'Desire and recognition in the same person — the myth this pair is named for. The rarest contact in the set.',
    'The myth has a long separation in the middle. This one asks more of both of you than either expected.'),
  [midpointKey('Eros', 'Ceres')]: R('Desire And Care',
    'You want them and you look after them, without conflict between the two.',
    'Care can quietly domesticate desire until only care is left.'),

  // ═══ PSYCHE ═══
  [midpointKey('Psyche', 'Ceres')]: R('Nurtured Soul',
    'They tend the part of you nobody else has met.',
    'Tending something that hidden makes them very hard to replace.'),
};

/** The reading for a midpoint pair, if one is written. */
export function readingForMidpoint(a: string, b: string): MidpointReading | null {
  return MIDPOINT_READINGS[midpointKey(a, b)] ?? null;
}

/** Is this one of the 13 already flagged as toxicity potential? */
export function isShadowMidpoint(a: string, b: string): boolean {
  return SHADOW_MIDPOINTS.has(midpointKey(a, b));
}

/** How the activation is phrased: their body landing on your point. */
export function describeActivation(
  activatingBody: string, a: string, b: string,
): string {
  return `Their ${activatingBody} sits on your ${a}/${b}`;
}
